import 'dotenv/config';
import { test,expect } from '@playwright/test';
test('configure weekly hours and create and release a block',async({page},info)=>{
 const name=`Horario ficticio ${Date.now()} ${info.project.name}`;
 await page.goto('/');await page.getByLabel('Correo electrónico',{exact:true}).fill('ana@alia.example');await page.getByLabel('Contraseña',{exact:true}).fill(process.env.DEMO_PASSWORD!);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page.getByRole('heading',{name:'Hola, Ana.'})).toBeVisible();
 await page.goto('/#professionals');await page.getByRole('button',{name:'Nuevo profesional',exact:true}).click();await page.getByLabel('Nombre',{exact:true}).fill(name);await page.getByRole('button',{name:'Crear profesional',exact:true}).click();await expect(page.getByRole('heading',{name:'Nuevo profesional',exact:true})).toHaveCount(0);
 await page.goto('/#agenda');await page.getByLabel('Fecha de la agenda',{exact:true}).fill('2042-02-03');await page.getByRole('button',{name:'Horarios de atención',exact:true}).click();await page.getByRole('combobox',{name:/Profesional del horario/}).fill(name);await page.getByRole('listbox').getByRole('option',{name}).click();await expect(page.getByText(/Sin configurar:/)).toBeVisible();await page.getByRole('button',{name:'Añadir turno Lunes',exact:true}).click();await page.getByLabel('Motivo del horario',{exact:true}).fill('Turno ficticio de prueba');await page.getByRole('button',{name:'Guardar horario',exact:true}).click();await expect(page.getByText('Guardado correctamente',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:`test-results/${info.project.name}-schedule.png`,fullPage:true});
 await page.getByRole('button',{name:'Cerrar formulario',exact:true}).click();await page.getByRole('button',{name:'Bloquear periodo',exact:true}).click();await page.getByRole('combobox',{name:/Recurso a bloquear/}).fill(name);await page.getByRole('listbox').getByRole('option',{name}).click();await page.getByLabel('Motivo del bloqueo',{exact:true}).fill('Vacaciones ficticias');await page.getByRole('button',{name:'Guardar bloqueo',exact:true}).click();await expect(page.getByText('Vacaciones ficticias',{exact:true})).toBeVisible();await expect(page.locator('[data-block-id]').filter({hasText:name})).toHaveCount(1);await expect(page.locator('[data-block-id]').filter({hasText:name})).toHaveCSS('background-color','rgb(162, 59, 67)');await page.locator('[data-block-id]').filter({hasText:name}).click();await expect(page.getByRole('heading',{name:'Bloqueo · '+name,exact:true})).toBeVisible();await page.screenshot({path:'test-results/'+info.project.name+'-calendar-block.png',fullPage:true});await page.getByRole('button',{name:'Cerrar formulario',exact:true}).click();await page.reload();await page.getByLabel('Fecha de la agenda',{exact:true}).fill('2042-02-03');await expect(page.getByText('Vacaciones ficticias',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.locator('.availability-block').filter({hasText:name}).getByRole('button',{name:'Liberar periodo',exact:true}).click();await page.getByLabel('Motivo de liberación',{exact:true}).fill('Fin de prueba');await page.getByRole('button',{name:'Confirmar liberación',exact:true}).click();await expect(page.getByText('Vacaciones ficticias',{exact:true})).toHaveCount(0);await expect(page.locator('[data-block-id]').filter({hasText:name})).toHaveCount(0);
});
