import 'dotenv/config';
import { test,expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
test('clinical summary and consultation note persist',async({page},info)=>{
 await page.goto('/');await page.getByLabel('Correo electrónico',{exact:true}).fill('ana@alia.example');await page.getByLabel('Contraseña',{exact:true}).fill(process.env.DEMO_PASSWORD!);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page.getByRole('heading',{name:'Hola, Ana.'})).toBeVisible();
 const me=await (await page.request.get('/api/auth/me')).json(),org=me.organizations.find((o:{name:string})=>o.name==='Clínica Dental Alia').id;
 const headers={'Origin':process.env.APP_ORIGIN!,'X-CSRF-Token':me.csrf,'X-Organization-Id':org};
 const response=await page.request.post('/api/patients',{headers,data:{request_id:randomUUID(),first_name:'Fotografía '+randomUUID().slice(0,8),last_name:'Ficticio'}});expect(response.ok()).toBe(true);const patient=await response.json();
 const branch=(await (await page.request.get('/api/organization',{headers})).json()).branches[0].id;
 const suffix=randomUUID().slice(0,8);
 const professional=await (await page.request.post('/api/catalogs/professionals',{headers,data:{name:'Doctor nota '+suffix,branch_ids:[branch]}})).json();
 const room=await (await page.request.post('/api/catalogs/rooms',{headers,data:{name:'Sala nota '+suffix,branch_id:branch}})).json();
 const service=await (await page.request.post('/api/catalogs/services',{headers,data:{name:'Consulta nota '+suffix,code:'NOTE_'+suffix.toUpperCase(),category:'Diagnóstico',duration_minutes:30,price_minor:0,currency:'MXN'}})).json();
 const appointmentResponse=await page.request.post('/api/appointments',{headers,data:{request_id:randomUUID(),branch_id:branch,patient_id:patient.id,professional_id:professional.id,room_id:room.id,service_id:service.id,start_local:'2030-01-15T09:00',duration_minutes:30}});expect(appointmentResponse.ok()).toBe(true);const appointment=await appointmentResponse.json();
 await page.goto('/#patients/'+patient.id);

 await expect(page.getByRole('heading',{name:'Expediente clínico',exact:true})).toBeVisible();await page.getByRole('button',{name:'Editar antecedentes',exact:true}).click();await page.getByLabel('Estado de alergias',{exact:true}).selectOption('reported');await page.getByLabel('Alergias reportadas',{exact:true}).fill('Alergia ficticia de prueba');await page.getByLabel('Antecedentes',{exact:true}).fill('Antecedente ficticio');await page.getByLabel('Estado · Enfermedades sistémicas',{exact:true}).selectOption('reported');await page.getByLabel('Detalle · Enfermedades sistémicas',{exact:true}).fill('Condición ficticia de prueba');await page.getByRole('button',{name:'Guardar antecedentes',exact:true}).click();await expect(page.getByText('Antecedentes guardados.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Añadir nota de consulta',exact:true}).click();await page.getByLabel('Cita relacionada',{exact:true}).selectOption(appointment.id);await page.getByLabel('Nota de consulta',{exact:true}).fill('Consulta ficticia para verificar persistencia.');await page.getByRole('button',{name:'Registrar nota',exact:true}).click();await expect(page.getByText('Nota de consulta registrada.',{exact:true})).toBeVisible();await page.reload();await expect(page.getByText('Condición ficticia de prueba',{exact:true}).first()).toBeVisible();await expect(page.getByText('Alergia ficticia de prueba',{exact:true}).first()).toBeVisible();await page.locator('.clinical-entry summary').filter({hasText:'Nota de consulta'}).click();await expect(page.getByText('Consulta ficticia para verificar persistencia.',{exact:true})).toBeVisible();await expect(page.getByText('Cita:',{exact:false})).toContainText('Doctor nota '+suffix);await page.getByRole('button',{name:'Editar antecedentes',exact:true}).click();await page.getByLabel('Antecedentes',{exact:true}).fill('Antecedente revisado');await page.getByRole('button',{name:'Guardar antecedentes',exact:true}).click();await expect(page.getByText('Antecedentes guardados.',{exact:true})).toBeVisible();await page.locator('.clinical-entry summary').filter({hasText:'Antecedentes · versión 1'}).click();await expect(page.getByText('Antecedente ficticio',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('heading',{name:'Expediente clínico',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/'+info.project.name+'-clinical-record.png'});
});
