import 'dotenv/config';
import { test,expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
test('consent templates and patient documents preserve versions',async({page},info)=>{
 await page.goto('/');await page.getByLabel('Correo electrónico',{exact:true}).fill('ana@alia.example');await page.getByLabel('Contraseña',{exact:true}).fill(process.env.DEMO_PASSWORD!);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page.getByRole('heading',{name:'Hola, Ana.'})).toBeVisible();
 const me=await (await page.request.get('/api/auth/me')).json(),org=me.organizations.find((o:{name:string})=>o.name==='Clínica Dental Alia').id;
 const headers={'Origin':process.env.APP_ORIGIN!,'X-CSRF-Token':me.csrf,'X-Organization-Id':org};
 const response=await page.request.post('/api/patients',{headers,data:{request_id:randomUUID(),first_name:'Fotografía '+randomUUID().slice(0,8),last_name:'Ficticio'}});expect(response.ok()).toBe(true);const patient=await response.json();

 const templateName='Consentimiento '+randomUUID().slice(0,8),doctorName='Doctor consentimiento '+randomUUID().slice(0,8);
 const doctor=await page.request.post('/api/catalogs/professionals',{headers,data:{name:doctorName,relationship:'external',branch_ids:[]}});expect(doctor.ok()).toBe(true);
 await page.goto('/#consent-templates');
 await page.getByRole('button',{name:'Nueva plantilla de consentimiento',exact:true}).click();
 await page.getByLabel('Nombre de la plantilla',{exact:true}).fill(templateName);
 await page.getByLabel('Especialidad o procedimiento',{exact:true}).selectOption('extraction');
 await page.getByLabel('Estado de la plantilla',{exact:true}).selectOption('available');
 await page.getByLabel('Texto del consentimiento',{exact:true}).fill('Texto ficticio para probar consentimientos. No utilizar en pacientes reales.');
 await page.getByRole('checkbox',{name:/Confirmo que el equipo/}).check();
 await page.getByRole('button',{name:'Guardar plantilla',exact:true}).click();
 await expect(page.getByText('Plantilla de consentimiento guardada.',{exact:true})).toBeVisible();
 await page.goto('/#patients/'+patient.id);
 await page.getByRole('button',{name:'Añadir procedimiento',exact:true}).click();await page.getByLabel('Procedimiento',{exact:true}).fill('Extracción de prueba');await page.getByRole('button',{name:'Aplicar al plan',exact:true}).click();await page.getByRole('button',{name:'Guardar plan',exact:true}).click();await expect(page.getByText('Plan de tratamiento guardado.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Preparar consentimiento',exact:true}).click();
 await page.getByLabel('Buscar plantilla',{exact:true}).fill(templateName);
 await page.getByRole('button',{name:templateName+' · Extracción · v1',exact:true}).click();
 await page.getByLabel('Procedimiento del consentimiento',{exact:true}).selectOption({label:'Extracción de prueba'});
 await page.getByLabel('Buscar doctor del consentimiento',{exact:true}).fill(doctorName);
 await page.getByRole('button',{name:doctorName+' · Especialidad sin registrar',exact:true}).click();
 await page.getByRole('button',{name:'Guardar consentimiento pendiente',exact:true}).click();
 await expect(page.getByText('Consentimiento preparado. Pendiente de aceptación.',{exact:true})).toBeVisible();
 await page.reload();
 await page.locator('summary').filter({hasText:templateName+' · Extracción de prueba'}).click();
 await expect(page.getByText('Texto ficticio para probar consentimientos. No utilizar en pacientes reales.',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.locator('.section').filter({has:page.getByRole('heading',{name:'Consentimientos del paciente',exact:true})}).screenshot({path:'test-results/'+info.project.name+'-consent.png'});
 await page.getByRole('button',{name:'Ver documento y decisión',exact:true}).click();
 const panel=page.locator('.prescription-review');
 await expect(page.frameLocator('iframe[title="Vista previa del consentimiento"]').getByText('Texto ficticio para probar consentimientos. No utilizar en pacientes reales.',{exact:true})).toBeVisible();
 await page.locator('iframe[title="Vista previa del consentimiento"]').evaluate((node)=>{const frame=node as HTMLIFrameElement;frame.contentWindow!.print=()=>{frame.dataset.printed='true';};});
 await panel.getByRole('button',{name:'Imprimir consentimiento / guardar PDF',exact:true}).click();
 await expect(page.locator('iframe[title="Vista previa del consentimiento"]')).toHaveAttribute('data-printed','true');
 await panel.getByRole('button',{name:'Registrar decisión',exact:true}).click();
 await page.getByLabel('Motivo o constancia',{exact:true}).fill('Prueba sin validez clínica');
 await page.getByLabel('Nombre de quien firma',{exact:true}).fill('Paciente ficticio');
 await page.getByLabel('Relación con el paciente',{exact:true}).fill('El propio paciente');
 await page.getByLabel('Evidencia firmada (PDF, JPG, PNG o WebP · máximo 5 MiB)',{exact:true}).setInputFiles({name:'prueba-ficticia.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7\nFictitious evidence\n%%EOF')});
 await page.getByRole('checkbox',{name:/Revisé que el archivo firmado/}).check();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await panel.screenshot({path:'test-results/'+info.project.name+'-consent-decision.png'});
 await page.getByRole('button',{name:'Guardar decisión',exact:true}).click();
 await expect(panel.getByRole('status').filter({hasText:'Aceptación registrada'})).toBeVisible();
 await page.reload();await page.locator('summary').filter({hasText:templateName+' · Extracción de prueba'}).click();
 await page.getByRole('button',{name:'Ver documento y decisión',exact:true}).click();
 await expect(panel.getByRole('status').filter({hasText:'Aceptación registrada'})).toBeVisible();
 const downloaded=page.waitForEvent('download');await panel.getByRole('button',{name:'Descargar evidencia: prueba-ficticia.pdf',exact:true}).click();expect((await downloaded).suggestedFilename()).toBe('prueba-ficticia.pdf');
 await panel.getByRole('button',{name:'Anular consentimiento',exact:true}).click();
 await page.getByLabel('Motivo o constancia',{exact:true}).fill('Corrección ficticia');
 await page.getByRole('button',{name:'Guardar decisión',exact:true}).click();
 await expect(panel.getByRole('status').filter({hasText:'Anulado'})).toBeVisible();
 await expect(panel.getByRole('button',{name:'Descargar evidencia: prueba-ficticia.pdf',exact:true})).toBeVisible();
 await expect(panel.getByRole('button',{name:'Registrar decisión',exact:true})).toHaveCount(0);
 await panel.screenshot({path:'test-results/'+info.project.name+'-consent-history.png'});
 await page.goto('/#consent-templates');const card=page.locator('article').filter({has:page.getByRole('heading',{name:templateName,exact:true})});await card.getByRole('button',{name:'Editar plantilla',exact:true}).click();await page.getByLabel('Estado de la plantilla',{exact:true}).selectOption('retired');await page.getByRole('button',{name:'Guardar plantilla',exact:true}).click();await expect(page.getByText('Plantilla de consentimiento guardada.',{exact:true})).toBeVisible();await card.getByRole('button',{name:'Historial de plantilla',exact:true}).click();await expect(page.getByText('Extracción · Disponible · Versión 1',{exact:true})).toBeVisible();
});

