import 'dotenv/config';
import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test('operates referral, laboratory, branch stock and refunds on desktop and mobile',async({page},info)=>{
 await page.goto('/');await page.getByLabel('Correo electrónico',{exact:true}).fill('ana@alia.example');await page.getByLabel('Contraseña',{exact:true}).fill(process.env.DEMO_PASSWORD!);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page.getByRole('heading',{name:'Hola, Ana.'})).toBeVisible();
 const me=await(await page.request.get('/api/auth/me')).json(),org=me.organizations.find((o:{name:string})=>o.name==='Clínica Dental Alia').id,headers={'Origin':process.env.APP_ORIGIN!,'X-CSRF-Token':me.csrf,'X-Organization-Id':org};
 const patient=await(await page.request.post('/api/patients',{headers,data:{request_id:randomUUID(),first_name:'Operaciones '+randomUUID().slice(0,8),last_name:'Ficticio'}})).json();const base='/api/patients/'+patient.id;
 const doctor='Externo '+randomUUID().slice(0,8);expect((await page.request.post('/api/catalogs/professionals',{headers,data:{name:doctor,relationship:'external',branch_ids:[]}})).ok()).toBe(true);
 await page.goto('/#patients/'+patient.id);const referrals=page.locator('#patient-section-referrals');await referrals.getByRole('button',{name:'Nueva remisión',exact:true}).click();await referrals.getByLabel('Buscar especialista externo',{exact:true}).fill(doctor);await referrals.getByRole('button',{name:doctor,exact:true}).click();await referrals.getByLabel('Motivo de remisión',{exact:true}).fill('Valoración externa de prueba');await referrals.getByLabel('Nota de seguimiento o motivo de corrección',{exact:true}).fill('Solicitud registrada');await referrals.getByRole('button',{name:'Guardar remisión y seguimiento',exact:true}).click();await expect(referrals.getByRole('heading',{name:doctor+' · Remisión pendiente',exact:true})).toBeVisible();await referrals.getByRole('button',{name:'Registrar seguimiento / informe',exact:true}).click();await referrals.getByLabel('Estado de la remisión',{exact:true}).selectOption('returned');await referrals.getByLabel('Nota de seguimiento o motivo de corrección',{exact:true}).fill('Informe revisado');await referrals.getByLabel('Informe del especialista',{exact:true}).fill('Informe ficticio de regreso');await referrals.getByRole('button',{name:'Guardar remisión y seguimiento',exact:true}).click();await expect(referrals.getByText('Informe ficticio de regreso',{exact:true})).toBeVisible();await referrals.screenshot({path:'test-results/'+info.project.name+'-referrals.png'});
 await page.goto('/#laboratories');await page.getByRole('button',{name:'Nuevo laboratorio',exact:true}).click();const lab='Laboratorio '+randomUUID().slice(0,8);await page.getByLabel('Nombre del laboratorio',{exact:true}).fill(lab);await page.getByLabel('Contacto del laboratorio',{exact:true}).fill('Contacto ficticio');await page.getByRole('button',{name:'Guardar laboratorio',exact:true}).click();await expect(page.getByRole('heading',{name:lab+' · Activo',exact:true})).toBeVisible();
 await page.goto('/#patients/'+patient.id);const orders=page.locator('#patient-section-laboratories');await orders.getByRole('button',{name:'Nueva orden de laboratorio',exact:true}).click();await orders.getByLabel('Laboratorio responsable',{exact:true}).selectOption({label:lab});await orders.getByLabel('Trabajo solicitado',{exact:true}).fill('Trabajo de prueba');await orders.getByLabel('Fecha prevista de recepción',{exact:true}).fill('2030-02-01');await orders.getByLabel('Nota de seguimiento del laboratorio',{exact:true}).fill('Solicitud');await orders.getByRole('button',{name:'Guardar trabajo de laboratorio',exact:true}).click();await expect(orders.getByRole('heading',{name:lab+' · Solicitado',exact:true})).toBeVisible();for(const state of ['sent','received','delivered']){await orders.getByRole('button',{name:'Actualizar trabajo de laboratorio',exact:true}).click();await orders.getByLabel('Estado del trabajo',{exact:true}).selectOption(state);await orders.getByLabel('Nota de seguimiento del laboratorio',{exact:true}).fill('Estado '+state);if(state==='received')await orders.getByLabel('Resultado o informe del laboratorio',{exact:true}).fill('Resultado ficticio recibido');await orders.getByRole('button',{name:'Guardar trabajo de laboratorio',exact:true}).click();await expect(orders.getByRole('button',{name:'Guardar trabajo de laboratorio',exact:true})).toHaveCount(0);}await expect(orders.getByText('Resultado ficticio recibido',{exact:true})).toBeVisible();await orders.screenshot({path:'test-results/'+info.project.name+'-laboratory-orders.png'});
 await page.goto('/#inventory');await page.getByRole('button',{name:'Nuevo artículo',exact:true}).click();const item='Material '+randomUUID().slice(0,8);await page.getByLabel('Nombre del artículo',{exact:true}).fill(item);await page.getByLabel('Código del artículo',{exact:true}).fill(randomUUID());await page.getByLabel('Unidad (pieza, caja, frasco…)',{exact:true}).fill('caja');await page.getByRole('button',{name:'Guardar artículo',exact:true}).click();await page.getByLabel('Buscar artículo',{exact:true}).fill(item);await page.getByRole('button',{name:'Entrada / salida / ajuste',exact:true}).click();await page.getByLabel('Cantidad de unidades',{exact:true}).fill('10');await page.getByLabel('Motivo o referencia del movimiento',{exact:true}).fill('Entrada ficticia');await page.getByRole('button',{name:'Registrar movimiento',exact:true}).click();await expect(page.getByText('10 caja',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Entrada / salida / ajuste',exact:true}).click();await page.getByLabel('Tipo de movimiento',{exact:true}).selectOption('exit');await page.getByLabel('Efecto en la existencia',{exact:true}).selectOption('subtract');await page.getByLabel('Cantidad de unidades',{exact:true}).fill('3');await page.getByLabel('Motivo o referencia del movimiento',{exact:true}).fill('Consumo ficticio');await page.getByRole('button',{name:'Registrar movimiento',exact:true}).click();await expect(page.getByText('7 caja',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.locator('.consent-detail.panel').screenshot({path:'test-results/'+info.project.name+'-inventory.png'});
 const branch=(await(await page.request.get('/api/organization',{headers})).json()).branches[0].id,planItem=randomUUID();expect((await page.request.post(base+'/treatment-plan',{headers,data:{version:0,items:[{id:planItem,title:'Tratamiento ficticio',tooth:'',status:'proposed',notes:''}]}})).ok()).toBe(true);
 async function budget(version:number,amount:number){expect((await page.request.post(base+'/budget',{headers,data:{request_id:randomUUID(),version,plan_version:1,title:'Acuerdo ficticio',currency:'MXN',items:[{plan_item_id:planItem,quantity:1,unit_minor:amount,discount_minor:0}]}})).ok()).toBe(true);}
 await budget(0,10000);const agreement=await(await page.request.post(base+'/budget/accept',{headers,data:{request_id:randomUUID(),version:1,accepted_by:'Paciente',relationship:'Titular',notes:'',reviewed:true}})).json();expect((await page.request.post(base+'/payments',{headers,data:{request_id:randomUUID(),acceptance_id:agreement.id,amount_minor:8000,kind:'advance',method:'cash',branch_id:branch,reference:'Ficticio',notes:''}})).ok()).toBe(true);await budget(1,6000);expect((await page.request.post(base+'/budget/accept',{headers,data:{request_id:randomUUID(),version:2,accepted_by:'Paciente',relationship:'Titular',notes:'Menor total pactado',reviewed:true,carry_payments:true}})).ok()).toBe(true);
 await page.goto('/#patients/'+patient.id);await expect(page.getByText('Saldo a favor:',{exact:false})).toContainText('20.00');const refunds=page.locator('section.section').filter({has:page.getByRole('heading',{name:'Devoluciones al paciente',exact:true})});await refunds.getByRole('button',{name:/disponibles/}).click();await refunds.getByLabel('Importe devuelto',{exact:true}).fill('20');await refunds.getByLabel('Motivo de devolución',{exact:true}).fill('Devolución ficticia del excedente');await refunds.getByRole('checkbox').check();await refunds.getByRole('button',{name:'Registrar devolución realizada',exact:true}).click();await expect(refunds.getByText('Devolución ficticia del excedente',{exact:false})).toBeVisible();await expect(page.getByText('Saldo a favor:',{exact:false})).toHaveCount(0);await refunds.screenshot({path:'test-results/'+info.project.name+'-refunds.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
