import 'dotenv/config';
import { test,expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
test('budget calculates exact totals and retains historical versions',async({page},info)=>{
 await page.goto('/');await page.getByLabel('Correo electrónico',{exact:true}).fill('ana@alia.example');await page.getByLabel('Contraseña',{exact:true}).fill(process.env.DEMO_PASSWORD!);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page.getByRole('heading',{name:'Hola, Ana.'})).toBeVisible();
 const me=await (await page.request.get('/api/auth/me')).json(),org=me.organizations.find((o:{name:string})=>o.name==='Clínica Dental Alia').id;
 const headers={'Origin':process.env.APP_ORIGIN!,'X-CSRF-Token':me.csrf,'X-Organization-Id':org};
 const response=await page.request.post('/api/patients',{headers,data:{request_id:randomUUID(),first_name:'Fotografía '+randomUUID().slice(0,8),last_name:'Ficticio'}});expect(response.ok()).toBe(true);const patient=await response.json();

 await page.goto('/#patients/'+patient.id);
 await page.getByRole('button',{name:'Añadir procedimiento',exact:true}).click();
 await page.getByLabel('Procedimiento',{exact:true}).fill('Tratamiento de prueba');
 await page.getByRole('button',{name:'Aplicar al plan',exact:true}).click();
 await page.getByRole('button',{name:'Guardar plan',exact:true}).click();
 await expect(page.getByText('Plan de tratamiento guardado.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Preparar desde el plan actual',exact:true}).click();
 await page.getByLabel('Nombre del presupuesto',{exact:true}).fill('Presupuesto personalizado');
 await page.getByLabel('Cantidad del procedimiento 1',{exact:true}).fill('3');
 await page.getByLabel('Precio unitario del procedimiento 1',{exact:true}).fill('100.01');
 await page.getByLabel('Descuento del procedimiento 1',{exact:true}).fill('0.02');
 await expect(page.getByText('Total del borrador:')).toContainText('300.01');
 await page.getByRole('button',{name:'Guardar presupuesto',exact:true}).click();
 await expect(page.getByText('Presupuesto guardado.',{exact:true})).toBeVisible();
 await page.reload();
 await expect(page.getByText('Total del presupuesto:')).toContainText('300.01');
 await page.getByRole('button',{name:'Editar presupuesto',exact:true}).click();
 await page.getByLabel('Precio unitario del procedimiento 1',{exact:true}).fill('200');
 await page.getByRole('button',{name:'Guardar presupuesto',exact:true}).click();
 await expect(page.getByText('Presupuesto guardado.',{exact:true})).toBeVisible();
 await expect(page.getByText('Total del presupuesto:')).toContainText('599.98');
 await page.getByText('Historial de presupuestos',{exact:true}).click();
 await page.getByLabel('Versión del presupuesto',{exact:true}).selectOption('1');
 await expect(page.getByText('Total del presupuesto:')).toContainText('300.01');
 await expect(page.getByRole('button',{name:'Editar presupuesto',exact:true})).toHaveCount(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.locator('.section').filter({has:page.getByRole('heading',{name:'Presupuestos',exact:true})}).screenshot({path:'test-results/'+info.project.name+'-budget.png'});
 await page.getByRole('button',{name:'Ver documento y aceptación',exact:true}).click();
 const panel=page.locator('.prescription-review');
 await expect(panel.getByText('Versión histórica. Abre la última versión para registrar aceptación.',{exact:true})).toBeVisible();
 await expect(panel.getByRole('button',{name:'Registrar aceptación del presupuesto',exact:true})).toHaveCount(0);
 await panel.getByRole('button',{name:'Cerrar presupuesto',exact:true}).click();
 await page.getByRole('button',{name:'Cargar presupuesto actual',exact:true}).click();
 await page.getByRole('button',{name:'Ver documento y aceptación',exact:true}).click();
 const frame=page.frameLocator('iframe[title="Vista previa del presupuesto"]');
 await expect(frame.getByText('PROPUESTA · SIN ACEPTACIÓN REGISTRADA',{exact:true})).toBeVisible();
 await expect(frame.getByText('Total:',{exact:false})).toContainText('599.98');
 await page.getByLabel('Persona que acepta el presupuesto',{exact:true}).fill('Paciente ficticio');
 await page.getByLabel('Relación de quien acepta con el paciente',{exact:true}).fill('El propio paciente');
 await page.getByLabel('Observaciones del acuerdo',{exact:true}).fill('Acuerdo ficticio de prueba');
 await page.getByRole('checkbox',{name:/Confirmo que esta persona aceptó/}).check();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await panel.screenshot({path:'test-results/'+info.project.name+'-budget-acceptance.png'});
 await page.getByRole('button',{name:'Registrar aceptación del presupuesto',exact:true}).click();
 await expect(panel.getByRole('status')).toHaveText('Aceptación del presupuesto registrada. La versión acordada se conserva.');
 await expect(frame.getByText('ACEPTACIÓN REGISTRADA',{exact:true})).toBeVisible();
 await page.locator('iframe[title="Vista previa del presupuesto"]').evaluate(node=>{const f=node as HTMLIFrameElement;f.contentWindow!.print=()=>{f.dataset.printed='true';};});
 await panel.getByRole('button',{name:'Imprimir presupuesto / guardar PDF',exact:true}).click();
 await expect(page.locator('iframe[title="Vista previa del presupuesto"]')).toHaveAttribute('data-printed','true');
 await page.reload();await page.getByRole('button',{name:'Crear nueva propuesta',exact:true}).click();
 await page.getByLabel('Precio unitario del procedimiento 1',{exact:true}).fill('300');
 await page.getByRole('button',{name:'Guardar presupuesto',exact:true}).click();
 await expect(page.getByText('Presupuesto guardado.',{exact:true})).toBeVisible();
 await expect(page.getByText('Acuerdo vigente: versión 2.',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Ver documento y aceptación',exact:true}).click();
 await expect(frame.getByText('PROPUESTA · SIN ACEPTACIÓN REGISTRADA',{exact:true})).toBeVisible();
 await page.getByLabel('Persona que acepta el presupuesto',{exact:true}).fill('Paciente ficticio');
 await page.getByLabel('Relación de quien acepta con el paciente',{exact:true}).fill('El propio paciente');
 await page.getByRole('checkbox',{name:/Confirmo que esta persona aceptó/}).check();
 await page.getByRole('button',{name:'Registrar aceptación del presupuesto',exact:true}).click();
 await expect(panel.getByRole('status')).toHaveText('Aceptación del presupuesto registrada. La versión acordada se conserva.');
 await panel.getByRole('button',{name:'Cerrar presupuesto',exact:true}).click();
 await page.getByText('Historial de presupuestos',{exact:true}).click();
 await page.getByLabel('Versión del presupuesto',{exact:true}).selectOption('2');
 await page.getByRole('button',{name:'Ver documento y aceptación',exact:true}).click();
 await expect(frame.getByText('ACUERDO ANTERIOR · SUSTITUIDO',{exact:true})).toBeVisible();
 await expect(frame.getByText('Total:',{exact:false})).toContainText('599.98');
});

