import 'dotenv/config';
import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test('captures advances, installments, settlement and an auditable correction',async({page},info)=>{
 await page.addInitScript(()=>{window.print=()=>{document.documentElement.dataset.printed='true';};});
 await page.goto('/');await page.getByLabel('Correo electrónico',{exact:true}).fill('ana@alia.example');await page.getByLabel('Contraseña',{exact:true}).fill(process.env.DEMO_PASSWORD!);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page.getByRole('heading',{name:'Hola, Ana.'})).toBeVisible();
 const me=await (await page.request.get('/api/auth/me')).json(),org=me.organizations.find((o:{name:string})=>o.name==='Clínica Dental Alia').id;
 const headers={'Origin':process.env.APP_ORIGIN!,'X-CSRF-Token':me.csrf,'X-Organization-Id':org};
 const response=await page.request.post('/api/patients',{headers,data:{request_id:randomUUID(),first_name:'Pagos '+randomUUID().slice(0,8),last_name:'Ficticio'}});expect(response.ok()).toBe(true);const patient=await response.json(),base='/api/patients/'+patient.id,item=randomUUID();
 expect((await page.request.post(base+'/treatment-plan',{headers,data:{version:0,items:[{id:item,title:'Tratamiento ficticio',tooth:'',status:'proposed',notes:''}]}})).ok()).toBe(true);
 expect((await page.request.post(base+'/budget',{headers,data:{request_id:randomUUID(),version:0,plan_version:1,title:'Presupuesto de prueba de pagos',currency:'MXN',items:[{plan_item_id:item,quantity:1,unit_minor:100050,discount_minor:0}]}})).ok()).toBe(true);
 expect((await page.request.post(base+'/budget/accept',{headers,data:{request_id:randomUUID(),version:1,accepted_by:'Paciente ficticio',relationship:'Paciente',notes:'',reviewed:true}})).ok()).toBe(true);
 await page.goto('/#patients/'+patient.id);
 const panel=page.locator('.section').filter({has:page.getByRole('heading',{name:'Pagos y saldo',exact:true})}),balance=panel.locator('.payment-summary p').filter({hasText:'Saldo pendiente'});
 await expect(balance).toContainText('1,000.50');
 await panel.getByRole('button',{name:'Registrar pago recibido',exact:true}).click();
 await page.getByLabel('Importe recibido (MXN)',{exact:true}).fill('100.25');
 await page.getByLabel('Sucursal de cobro',{exact:true}).selectOption({index:1});
 await page.getByLabel('Referencia del pago (opcional)',{exact:true}).fill('Anticipo ficticio');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await panel.screenshot({path:'test-results/'+info.project.name+'-payment-form.png'});
 await panel.getByRole('button',{name:'Guardar pago recibido',exact:true}).click();
 await expect(balance).toContainText('900.25');
 await panel.getByRole('button',{name:'Registrar pago recibido',exact:true}).click();
 await expect(page.getByLabel('Tipo de pago',{exact:true})).toHaveValue('installment');
 await page.getByLabel('Importe recibido (MXN)',{exact:true}).fill('200.25');
 await page.getByLabel('Método de pago',{exact:true}).selectOption('transfer');
 await page.getByLabel('Sucursal de cobro',{exact:true}).selectOption({index:1});
 await panel.getByRole('button',{name:'Guardar pago recibido',exact:true}).click();
 await expect(balance).toContainText('700.00');
 await panel.getByRole('button',{name:'Registrar pago recibido',exact:true}).click();
 await page.getByLabel('Tipo de pago',{exact:true}).selectOption('settlement');
 await expect(page.getByLabel('Importe recibido (MXN)',{exact:true})).toHaveValue('700.00');
 await page.getByLabel('Sucursal de cobro',{exact:true}).selectOption({index:1});
 await panel.getByRole('button',{name:'Guardar pago recibido',exact:true}).click();
 await expect(panel.getByText('Sin saldo pendiente en este acuerdo.',{exact:true})).toBeVisible();
 const advance=panel.locator('article').filter({hasText:'Anticipo ficticio'});
 await advance.getByRole('button',{name:'Ver recibo',exact:true}).click();
 const preview=page.frameLocator('iframe[title="Vista previa del recibo"]');
 await expect(preview.getByText('RECIBO DE PAGO REGISTRADO',{exact:true})).toBeVisible();
 await expect(preview.getByText('Saldo del acuerdo inmediatamente después de este registro:',{exact:false})).toContainText('900.25');
 await panel.getByRole('button',{name:'Imprimir recibo / guardar PDF',exact:true}).click();
 await expect(preview.locator('html')).toHaveAttribute('data-printed','true');
 await panel.locator('.prescription-review').screenshot({path:'test-results/'+info.project.name+'-receipt.png'});
 await panel.getByRole('button',{name:'Cerrar recibo',exact:true}).click();
 await advance.getByRole('button',{name:'Anular registro erróneo',exact:true}).click();
 await page.getByLabel('Motivo de anulación del pago',{exact:true}).fill('Captura errónea ficticia para prueba');
 await page.getByRole('checkbox',{name:/Confirmo que corrijo un registro erróneo/}).check();
 await panel.getByRole('button',{name:'Confirmar anulación del registro',exact:true}).click();
 await expect(balance).toContainText('100.25');await expect(advance).toContainText('Anulado');
 await page.reload();await expect(balance).toContainText('100.25');await expect(advance).toContainText('Captura errónea ficticia para prueba');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await panel.screenshot({path:'test-results/'+info.project.name+'-payment-history.png'});
 await advance.getByRole('button',{name:'Ver recibo',exact:true}).click();
 await expect(preview.getByText('ANULADO · NO ACREDITA UN PAGO VIGENTE',{exact:true})).toBeVisible();
 await expect(preview.getByText('Saldo del acuerdo inmediatamente después de este registro:',{exact:false})).toHaveCount(0);
 await panel.locator('.prescription-review').screenshot({path:'test-results/'+info.project.name+'-receipt-voided.png'});
});

