import 'dotenv/config';
import { test,expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
test('clinical photo annotations persist with immutable history',async({page},info)=>{
 await page.goto('/');await page.getByLabel('Correo electrónico',{exact:true}).fill('ana@alia.example');await page.getByLabel('Contraseña',{exact:true}).fill(process.env.DEMO_PASSWORD!);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page.getByRole('heading',{name:'Hola, Ana.'})).toBeVisible();
 const me=await (await page.request.get('/api/auth/me')).json(),org=me.organizations.find((o:{name:string})=>o.name==='Clínica Dental Alia').id;
 const headers={'Origin':process.env.APP_ORIGIN!,'X-CSRF-Token':me.csrf,'X-Organization-Id':org};
 const response=await page.request.post('/api/patients',{headers,data:{request_id:randomUUID(),first_name:'Fotografía '+randomUUID().slice(0,8),last_name:'Ficticio'}});expect(response.ok()).toBe(true);const patient=await response.json();
 await page.goto('/#patients/'+patient.id);
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=800;c.height=400;const x=c.getContext('2d')!;x.fillStyle='#183640';x.fillRect(0,0,800,400);x.fillStyle='#dce9e7';for(let i=0;i<6;i++)x.fillRect(130+i*90,130,65,130);x.font='24px sans-serif';x.fillText('IMAGEN DE PRUEBA',270,60);return c.toDataURL('image/webp').split(',')[1];});

 await page.locator('.profile-photo summary').click();await page.getByLabel('Fotografía de perfil',{exact:true}).setInputFiles({name:'Perfil.webp',mimeType:'image/webp',buffer:Buffer.from(png,'base64')});await expect(page.getByAltText('Vista previa de la nueva foto')).toBeVisible();await page.getByRole('button',{name:'Guardar foto de perfil',exact:true}).click();await expect(page.getByText('Foto de perfil guardada.',{exact:true})).toBeVisible();await expect(page.getByAltText('Foto de perfil del paciente')).toBeVisible();await page.reload();await expect(page.getByAltText('Foto de perfil del paciente')).toBeVisible();await page.locator('.profile-photo summary').click();const beforeProfile=await (await page.request.get('/api/patients/'+patient.id+'/attachments/profile-photo',{headers})).json();await page.getByLabel('Fotografía de perfil',{exact:true}).setInputFiles({name:'Perfil nuevo.webp',mimeType:'image/webp',buffer:Buffer.from(png,'base64')});await page.getByRole('button',{name:'Guardar foto de perfil',exact:true}).click();await expect(page.getByText('Foto de perfil guardada.',{exact:true})).toBeVisible();const afterProfile=await (await page.request.get('/api/patients/'+patient.id+'/attachments/profile-photo',{headers})).json();expect(afterProfile.attachment_id).not.toBe(beforeProfile.attachment_id);await page.locator('.patient-profile-header').screenshot({path:'test-results/'+info.project.name+'-profile-photo.png'});await page.getByRole('button',{name:'Quitar foto de perfil',exact:true}).click();await expect(page.getByText('Foto de perfil retirada.',{exact:true})).toBeVisible();await expect(page.getByAltText('Foto de perfil del paciente')).toHaveCount(0);await page.locator('.profile-photo summary').click();
 await page.getByLabel('Seleccionar fotografía',{exact:true}).setInputFiles({name:'Prueba clínica.webp',mimeType:'image/webp',buffer:Buffer.from(png,'base64')});await page.getByRole('button',{name:'Subir fotografía',exact:true}).click();await expect(page.getByText('Archivo guardado correctamente.',{exact:true})).toBeVisible();

 await page.getByRole('button',{name:'Abrir anotaciones',exact:true}).click();await expect(page.getByRole('button',{name:'Flecha',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Cambiar nombre',exact:true}).click();await page.getByLabel('Nombre de la fotografía',{exact:true}).fill('Vista frontal · control');await page.getByRole('button',{name:'Guardar nombre',exact:true}).click();await expect(page.getByRole('heading',{name:'Vista frontal · control',exact:true})).toBeVisible();expect(await page.getByRole('button',{name:'Guardar cambios',exact:true}).evaluate(el=>getComputedStyle(el).cursor)).toBe('default');
 await page.getByRole('button',{name:'Ocultar comentarios',exact:true}).click();
 const canvas=page.getByRole('img',{name:'Lienzo de anotaciones',exact:true});
 await page.getByRole('button',{name:'Flecha',exact:true}).click();await canvas.scrollIntoViewIfNeeded();let box=(await canvas.boundingBox())!;
 await canvas.click({position:{x:box.width*.2,y:box.height*.3}});await canvas.click({position:{x:box.width*.55,y:box.height*.6}});
 await page.getByLabel('Comentario de la anotación').fill('Observación inicial');await page.getByLabel('Pieza dental',{exact:true}).fill('51');await page.getByRole('button',{name:'Aplicar comentario',exact:true}).click();
 await canvas.scrollIntoViewIfNeeded();box=(await canvas.boundingBox())!;const line=canvas.locator('line').last(),oldX=Number(await line.getAttribute('x1'));
 await page.mouse.move(box.x+box.width*.375,box.y+box.height*.45);await page.mouse.down();await page.mouse.move(box.x+box.width*.425,box.y+box.height*.50,{steps:5});await page.mouse.up();expect(Number(await line.getAttribute('x1'))).toBeGreaterThan(oldX+20);
 const handle=canvas.locator('[data-handle="end"]');const hb=(await handle.boundingBox())!;const oldEnd=await line.getAttribute('x2');await page.mouse.move(hb.x+hb.width/2,hb.y+hb.height/2);await page.mouse.down();await page.mouse.move(hb.x+hb.width/2+box.width*.05,hb.y+hb.height/2,{steps:4});await page.mouse.up();expect(await line.getAttribute('x2')).not.toBe(oldEnd);
 await page.getByLabel('Comentario de la anotación').fill('Comentario editado');await page.getByRole('button',{name:'Aplicar comentario',exact:true}).click();
 await page.getByRole('button',{name:'Duplicar',exact:true}).click();await expect(canvas.locator('g')).toHaveCount(2);await page.getByRole('button',{name:'Eliminar',exact:true}).click();await expect(canvas.locator('g')).toHaveCount(1);await page.getByRole('button',{name:'Deshacer',exact:true}).click();await expect(canvas.locator('g')).toHaveCount(2);await page.getByRole('button',{name:'Rehacer',exact:true}).click();await expect(canvas.locator('g')).toHaveCount(1);
 await page.getByRole('button',{name:'Nota',exact:true}).click();await canvas.click({position:{x:box.width*.75,y:box.height*.3}});await page.getByLabel('Comentario de la anotación').fill('Nota independiente');await page.getByRole('button',{name:'Aplicar comentario',exact:true}).click();


 await page.getByRole('button',{name:'Círculo',exact:true}).click();await canvas.click({position:{x:box.width*.1,y:box.height*.75}});await canvas.click({position:{x:box.width*.25,y:box.height*.9}});await page.getByLabel('Comentario de la anotación').fill('Comentario propio del círculo');await page.getByRole('button',{name:'Aplicar comentario',exact:true}).click();await expect(canvas.locator('ellipse')).toHaveCount(1);await page.getByRole('button',{name:'Quitar comentario sin borrar figura',exact:true}).click();await expect(canvas.locator('ellipse')).toHaveCount(1);await page.getByRole('button',{name:'Eliminar',exact:true}).click();await expect(canvas.locator('ellipse')).toHaveCount(0);await page.getByRole('button',{name:'Seleccionar anotación 2',exact:true}).click();await expect(canvas.locator('foreignObject')).toHaveCount(1);
 await page.getByLabel('Comentario de la anotación').fill('Nota final guardada directamente');

 await page.getByRole('button',{name:'Mostrar comentarios',exact:true}).click();const card=canvas.locator('foreignObject').last();await expect(card).toContainText('Nota final guardada directamente');await canvas.scrollIntoViewIfNeeded();const cardBox=(await card.boundingBox())!,originalLabelX=await card.getAttribute('x');const originalArrowX=await line.getAttribute('x1');
 await page.mouse.move(cardBox.x+cardBox.width/2,cardBox.y+15);await page.mouse.down();await page.mouse.move(cardBox.x+cardBox.width/2-30,cardBox.y+30,{steps:4});await page.mouse.up();expect(await card.getAttribute('x')).not.toBe(originalLabelX);expect(await line.getAttribute('x1')).toBe(originalArrowX);const savedLabelX=await card.getAttribute('x');

 let failSave=true;await page.route('**/photos/*/annotations',async route=>{if(route.request().method()==='POST'&&failSave){failSave=false;await route.fulfill({status:503,json:{message:'Guardado interrumpido de prueba'}});}else if(route.request().method()==='GET')await route.fulfill({status:503,json:{message:'Historial no disponible'}});else await route.continue();});
 await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();await expect(page.getByText('Guardado interrumpido de prueba',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Guardar cambios',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();await expect(page.getByText('Los cambios sí se guardaron. No pudimos actualizar el historial; puedes volver a abrir la foto.',{exact:true})).toBeVisible();await page.unroute('**/photos/*/annotations');await expect(page.getByText('Versión guardada.',{exact:true})).toBeVisible();

 if(info.project.name==='mobile'){
  await page.getByRole('button',{name:'Flecha',exact:true}).click();await canvas.scrollIntoViewIfNeeded();const b=(await canvas.boundingBox())!,session=await page.context().newCDPSession(page);const count=await canvas.locator('g').count(),startX=await line.getAttribute('x1'),startY=await line.getAttribute('y1');
  const fingers=(a:number,z:number)=>[{id:1,x:b.x+b.width*a,y:b.y+b.height*.8},{id:2,x:b.x+b.width*z,y:b.y+b.height*.8}];
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:fingers(.35,.65)});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:fingers(.15,.85)});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(async()=>Number(await page.getByLabel('Zoom de fotografía').inputValue())).toBeGreaterThan(1.5);expect(await canvas.locator('g').count()).toBe(count);expect(await line.getAttribute('x1')).toBe(startX);expect(await line.getAttribute('y1')).toBe(startY);
  await page.getByRole('button',{name:'Seleccionar',exact:true}).click();const view=page.locator('.studio-canvas');await view.scrollIntoViewIfNeeded();const v=(await view.boundingBox())!,initialScroll=await view.evaluate(el=>el.scrollLeft);
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:v.x+v.width*.8,y:v.y+v.height*.85}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:v.x+v.width*.5,y:v.y+v.height*.85}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(()=>view.evaluate(el=>el.scrollLeft)).toBeGreaterThan(initialScroll);
  await page.getByLabel('Zoom de fotografía').selectOption('1');await session.detach();
 }
 const savedX=await line.getAttribute('x1');await page.getByLabel('Zoom de fotografía').selectOption('2');expect(await line.getAttribute('x1')).toBe(savedX);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByLabel('Zoom de fotografía').selectOption('1');
 await page.getByRole('button',{name:'Ver original sin marcas',exact:true}).click();await expect(canvas.locator('g')).toHaveCount(0);await page.getByRole('button',{name:'Mostrar anotaciones',exact:true}).click();await expect(canvas.locator('g')).toHaveCount(1);
 await page.reload();await expect(page.getByText('Vista frontal · control',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Abrir anotaciones',exact:true}).click();await page.getByRole('button',{name:'Seleccionar anotación 2',exact:true}).click();expect(await canvas.locator('foreignObject').last().getAttribute('x')).toBe(savedLabelX);await page.getByRole('button',{name:'Seleccionar anotación 1',exact:true}).click();await expect(page.getByLabel('Comentario de la anotación')).toHaveValue('Comentario editado');expect(await line.getAttribute('x1')).toBe(savedX);
 await page.getByRole('button',{name:'Eliminar',exact:true}).click();await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();await expect(page.getByText('Versión guardada.',{exact:true})).toBeVisible();await page.locator('.studio-history summary').click();await page.getByLabel('Versión de anotaciones').selectOption('1');await expect(canvas.locator('g')).toHaveCount(1);await page.getByRole('button',{name:'Seleccionar anotación 1',exact:true}).click();await expect(page.getByLabel('Comentario de la anotación')).toBeDisabled();await expect(page.getByRole('button',{name:'Guardar cambios',exact:true})).toBeDisabled();

 if(info.project.name==='mobile'){
  await canvas.scrollIntoViewIfNeeded();const b=(await canvas.boundingBox())!;await page.touchscreen.tap(b.x+b.width*.05,b.y+b.height*.95);await expect(page.locator('.studio-mark-list button[aria-pressed="true"]')).toHaveCount(0);for(const card of await canvas.locator('foreignObject span').all())await expect(card).toBeHidden();
 }
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.locator('.photo-studio').screenshot({path:'test-results/'+info.project.name+'-clinical-photo.png'});
});
