import 'dotenv/config';
import { test,expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
test('prescription draft snapshots persist and version medication edits',async({page},info)=>{
 await page.goto('/');await page.getByLabel('Correo electrónico',{exact:true}).fill('ana@alia.example');await page.getByLabel('Contraseña',{exact:true}).fill(process.env.DEMO_PASSWORD!);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page.getByRole('heading',{name:'Hola, Ana.'})).toBeVisible();
 const me=await (await page.request.get('/api/auth/me')).json(),org=me.organizations.find((o:{name:string})=>o.name==='Clínica Dental Alia').id;
 const headers={'Origin':process.env.APP_ORIGIN!,'X-CSRF-Token':me.csrf,'X-Organization-Id':org};
 const response=await page.request.post('/api/patients',{headers,data:{request_id:randomUUID(),first_name:'Fotografía '+randomUUID().slice(0,8),last_name:'Ficticio'}});expect(response.ok()).toBe(true);const patient=await response.json();

 const name='Doctor borrador '+randomUUID().slice(0,8);
 const professional=await page.request.post('/api/catalogs/professionals',{headers,data:{name,relationship:'external',branch_ids:[],professional_title:'Título ficticio',license:'TEST-'+randomUUID().slice(0,8),practice_address:'Dirección ficticia',training_institution:'Institución ficticia'}});expect(professional.ok()).toBe(true);
 await page.goto('/#patients/'+patient.id);
 await page.getByRole('button',{name:'Nuevo borrador de receta',exact:true}).click();
 await page.getByLabel('Buscar doctor responsable',{exact:true}).fill(name);
 await page.getByRole('button',{name:name+' · Especialidad sin registrar',exact:true}).click();
 await page.getByLabel('Medicamento 1',{exact:true}).fill('Medicamento ficticio');
 for(const field of ['Presentación','Dosis','Vía','Frecuencia','Duración'])await page.getByLabel(field+' 1',{exact:true}).fill('Dato ficticio de prueba');
 await page.getByLabel('Indicaciones 1',{exact:true}).fill('Texto de prueba sin indicación clínica');
 await page.getByRole('button',{name:'Guardar borrador de receta',exact:true}).click();
 await expect(page.getByText('Borrador de receta guardado.',{exact:true})).toBeVisible();
 await page.reload();
 await page.locator('summary').filter({hasText:'Receta en preparación · versión 1'}).click();
 await expect(page.getByText('Medicamento ficticio',{exact:true})).toBeVisible();
 await expect(page.getByText('Doctor: '+name,{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Editar este borrador',exact:true}).click();
 await page.getByRole('button',{name:'Añadir medicamento',exact:true}).click();
 await page.getByLabel('Medicamento 2',{exact:true}).fill('Segundo medicamento ficticio');
 await page.getByRole('button',{name:'Guardar borrador de receta',exact:true}).click();
 await expect(page.getByText('Borrador de receta guardado.',{exact:true})).toBeVisible();
 await page.locator('summary').filter({hasText:'Receta en preparación · versión 2'}).click();
 await expect(page.getByText('Segundo medicamento ficticio',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Revisar / imprimir versión 2',exact:true}).click();
 await expect(page.getByText('Falta completar:',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Preparar para firma',exact:true})).toHaveCount(0);
 const preview=page.frameLocator('iframe[title="Vista previa de receta"]');
 await expect(preview.getByText('BORRADOR · NO VÁLIDO PARA DISPENSACIÓN',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Cerrar revisión',exact:true}).click();
 await page.locator('details').filter({has:page.locator('summary').filter({hasText:'Receta en preparación · versión 2'})}).getByRole('button',{name:'Editar este borrador',exact:true}).click();
 for(const field of ['Presentación','Dosis','Vía','Frecuencia','Duración'])await page.getByLabel(field+' 2',{exact:true}).fill('Dato ficticio');
 await page.getByRole('button',{name:'Guardar borrador de receta',exact:true}).click();
 await expect(page.getByText('Borrador de receta guardado.',{exact:true})).toBeVisible();
 await page.locator('summary').filter({hasText:'Receta en preparación · versión 3'}).click();
 await page.getByRole('button',{name:'Revisar / imprimir versión 3',exact:true}).click();
 await expect(page.getByRole('button',{name:'Preparar para firma',exact:true})).toBeDisabled();
 await page.getByRole('checkbox',{name:/Revisé los datos/}).check();
 await page.getByRole('button',{name:'Preparar para firma',exact:true}).click();
 await expect(preview.getByText('PREPARADA PARA FIRMA AUTÓGRAFA · SIN FIRMA',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Imprimir / guardar PDF',exact:true})).toBeEnabled();
 await page.locator('iframe[title="Vista previa de receta"]').evaluate((element)=>{const frame=element as HTMLIFrameElement;frame.contentWindow!.print=()=>{frame.dataset.printRequested='true';};});
 await page.getByRole('button',{name:'Imprimir / guardar PDF',exact:true}).click();
 await expect(page.locator('iframe[title="Vista previa de receta"]')).toHaveAttribute('data-print-requested','true');
 await page.getByRole('button',{name:'Cerrar revisión',exact:true}).click();
 await page.reload();await page.locator('summary').filter({hasText:'Receta en preparación · versión 3'}).click();
 await expect(page.getByRole('button',{name:'Copiar a nuevo borrador',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Revisar / imprimir versión 3',exact:true}).click();
 await expect(preview.getByText('PREPARADA PARA FIRMA AUTÓGRAFA · SIN FIRMA',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.locator('.section').filter({has:page.getByRole('heading',{name:'Borradores de recetas',exact:true})}).screenshot({path:'test-results/'+info.project.name+'-prescription.png'});
});
