import 'dotenv/config';
import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test('assigns and corrects a professional share from the accepted total',async({page},info)=>{
 await page.goto('/');await page.getByLabel('Correo electrónico',{exact:true}).fill('ana@alia.example');await page.getByLabel('Contraseña',{exact:true}).fill(process.env.DEMO_PASSWORD!);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page.getByRole('heading',{name:'Hola, Ana.'})).toBeVisible();
 const me=await(await page.request.get('/api/auth/me')).json(),org=me.organizations.find((o:{name:string})=>o.name==='Clínica Dental Alia').id,headers={'Origin':process.env.APP_ORIGIN!,'X-CSRF-Token':me.csrf,'X-Organization-Id':org};
 const patient=await(await page.request.post('/api/patients',{headers,data:{request_id:randomUUID(),first_name:'Participación '+randomUUID().slice(0,8),last_name:'Ficticio'}})).json(),base='/api/patients/'+patient.id,item=randomUUID();
 expect((await page.request.post(base+'/treatment-plan',{headers,data:{version:0,items:[{id:item,title:'Tratamiento ficticio',tooth:'',status:'proposed',notes:''}]}})).ok()).toBe(true);
 expect((await page.request.post(base+'/budget',{headers,data:{request_id:randomUUID(),version:0,plan_version:1,title:'Acuerdo de prueba',currency:'MXN',items:[{plan_item_id:item,quantity:1,unit_minor:110050,discount_minor:10000}]}})).ok()).toBe(true);
 expect((await page.request.post(base+'/budget/accept',{headers,data:{request_id:randomUUID(),version:1,accepted_by:'Paciente ficticio',relationship:'Paciente',notes:'',reviewed:true}})).ok()).toBe(true);
 await page.goto('/#patients/'+patient.id+'/shares');const panel=page.locator('#patient-section-shares');await panel.getByRole('button',{name:'Asignar participación',exact:true}).click();
 const options=await(await page.request.get(base+'/professional-shares/professionals',{headers})).json();expect(options.items.length).toBeGreaterThan(0);const doctor=options.items[0];
 await panel.getByLabel('Buscar doctor responsable',{exact:true}).fill(doctor.name);await panel.getByRole('button',{name:new RegExp(doctor.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'))}).first().click();
 await panel.getByLabel('Porcentaje del doctor',{exact:true}).fill('33.33');await expect(panel.getByRole('status').filter({hasText:'Participación calculada'})).toContainText('333.47');
 await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'Guardar participación',exact:true}).click();await expect(panel.getByRole('status').filter({hasText:'Participación guardada'})).toBeVisible();
 await panel.getByRole('button',{name:'Corregir participación',exact:true}).click();await panel.getByLabel('Porcentaje del doctor',{exact:true}).fill('50');await panel.getByLabel('Motivo de la nueva asignación o corrección',{exact:true}).fill('Porcentaje corregido con el doctor');await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'Guardar participación',exact:true}).click();await expect(panel.getByText('Asignación vigente, versión 2.',{exact:false})).toBeVisible();
 await page.reload();await expect(panel.getByText('Asignación vigente, versión 2.',{exact:false})).toBeVisible();await panel.locator('summary').click();await expect(panel.getByRole('heading',{name:'Asignación 1 · '+doctor.name,exact:true})).toBeVisible();await expect(panel.getByText('50% del acuerdo',{exact:false})).toContainText('500.25');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await panel.screenshot({path:'test-results/'+info.project.name+'-professional-share.png'});

 const payouts=panel.locator('.professional-payments');await payouts.getByRole('button',{name:'Registrar pago al doctor',exact:true}).click();await payouts.getByLabel('Importe pagado al doctor (MXN)',{exact:true}).fill('100');await payouts.getByLabel('Método de pago al doctor',{exact:true}).selectOption('cash');await payouts.getByLabel('Referencia del pago al doctor',{exact:true}).fill('Transferencia ficticia');await payouts.getByRole('checkbox').check();await payouts.getByRole('button',{name:'Guardar pago al doctor',exact:true}).click();await expect(payouts.getByRole('status').filter({hasText:'Pago al doctor registrado.'})).toBeVisible();
 await expect(payouts.locator('.payment-summary p').filter({hasText:'Pendiente del doctor'})).toContainText('400.25');await expect(panel.getByRole('button',{name:'Corregir participación',exact:true})).toHaveCount(0);
 await payouts.getByRole('button',{name:'Registrar pago al doctor',exact:true}).click();await payouts.getByLabel('Tipo de pago al doctor',{exact:true}).selectOption('settlement');await expect(payouts.getByLabel('Importe pagado al doctor (MXN)',{exact:true})).toHaveValue('400.25');await payouts.getByRole('checkbox').check();await payouts.getByRole('button',{name:'Guardar pago al doctor',exact:true}).click();await expect(payouts.getByText('Participación liquidada según los registros vigentes.',{exact:true})).toBeVisible();
 await payouts.getByRole('button',{name:'Anular captura de $100.00 MXN',exact:true}).click();await payouts.getByLabel('Motivo de anulación del pago al doctor',{exact:true}).fill('Captura ficticia duplicada');await payouts.getByRole('checkbox').check();await payouts.getByRole('button',{name:'Confirmar anulación del pago al doctor',exact:true}).click();await expect(payouts.locator('.payment-summary p').filter({hasText:'Pendiente del doctor'})).toContainText('100.00');await page.reload();await expect(payouts.getByRole('heading',{name:'ANULADO · Abono · $100.00 MXN',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await payouts.screenshot({path:'test-results/'+info.project.name+'-professional-payments.png'});


 await payouts.getByRole('button',{name:'Ver recibo del doctor',exact:true}).first().click();const receiptFrame=page.frameLocator('iframe[title="Vista previa del recibo del doctor"]');await expect(receiptFrame.getByText('REGISTRO DE PAGO AL PROFESIONAL',{exact:true})).toBeVisible();await expect(receiptFrame.getByText('Saldo histórico;', {exact:false})).toBeVisible();
 const paymentRows=await(await page.request.get(base+'/professional-payments',{headers})).json(),settled=paymentRows.items.find((r:{kind:string})=>r.kind==='settlement');expect((await page.request.post(base+'/professional-payments/'+settled.id+'/void',{headers,data:{request_id:randomUUID(),reason:'Prueba de anulación antes de imprimir',reviewed:true}})).ok()).toBe(true);
 await page.addInitScript(()=>{window.print=()=>window.parent.postMessage('professional-receipt-print','*');});await page.evaluate(()=>{window.addEventListener('message',e=>{if(e.data==='professional-receipt-print')document.body.dataset.receiptPrinted='true';});});await payouts.getByRole('button',{name:'Imprimir recibo del doctor / guardar PDF',exact:true}).click();await expect(page.locator('body')).toHaveAttribute('data-receipt-printed','true');await expect(receiptFrame.getByText('ANULADO · NO ACREDITA UN PAGO VIGENTE',{exact:true})).toBeVisible();await expect(receiptFrame.getByText('Saldo histórico;', {exact:false})).toHaveCount(0);await page.locator('iframe[title="Vista previa del recibo del doctor"]').screenshot({path:'test-results/'+info.project.name+'-professional-receipt.png'});await payouts.getByRole('button',{name:'Cerrar recibo del doctor',exact:true}).click();await expect(page.locator('iframe[title="Vista previa del recibo del doctor"]')).toHaveCount(0);
 const optionsCash=await(await page.request.get('/api/cash-closures/options',{headers})).json();const filters={from:optionsCash.today,to:optionsCash.today,branch_id:optionsCash.branches[0].id};const preview=await(await page.request.get('/api/cash-closures/preview?'+new URLSearchParams(filters),{headers})).json();expect(preview.snapshot.schema_version).toBe(3);expect(preview.snapshot.events.some((e:{type:string})=>e.type==='professional_payment')).toBe(true);
 const saved=await(await page.request.post('/api/cash-closures',{headers,data:{request_id:randomUUID(),filters,token:preview.token,notes:'Prueba con egresos',reviewed:true}})).json();
 await page.goto('/#cash-closures');await page.getByRole('button',{name:'Ver corte guardado',exact:true}).first().click();await expect(page.getByRole('status').filter({hasText:'Corte conservado'})).toContainText(saved.id);
 const cashCount=page.locator('.cash-count');await cashCount.getByRole('button',{name:'Registrar arqueo',exact:true}).click();for(const t of preview.snapshot.totals.filter((t:{method:string})=>t.method==='cash')){await page.getByLabel('Fondo inicial ('+t.currency+')',{exact:true}).fill(((t.paid_minor+10000)/100).toFixed(2));await page.getByLabel('Efectivo contado ('+t.currency+')',{exact:true}).fill(((t.received_minor+10000)/100).toFixed(2));}
 await cashCount.getByRole('checkbox',{name:/Revisé el efectivo, fondo, ajustes/}).check();await expect(cashCount.getByRole('button',{name:'Guardar arqueo',exact:true})).toBeDisabled();await cashCount.getByRole('checkbox',{name:/Revisé los egresos: doctor y devoluciones descontados/}).check();await cashCount.getByRole('button',{name:'Guardar arqueo',exact:true}).click();await expect(cashCount.getByRole('status').filter({hasText:'Arqueo guardado'})).toBeVisible();await expect(cashCount.getByText('Sin diferencia',{exact:false}).first()).toBeVisible();await cashCount.screenshot({path:'test-results/'+info.project.name+'-cash-expenses.png'});
 await page.getByRole('button',{name:'Ver documento del corte',exact:true}).click();await expect(page.frameLocator('iframe[title="Vista previa del corte"]').getByText('Egresos: doctor y devoluciones descontados',{exact:true}).first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
