import 'dotenv/config';
import {test,expect} from '@playwright/test';
test('consults professional periods and current balance from report hub',async({page},info)=>{
 await page.addInitScript(()=>{window.print=()=>window.parent.postMessage('report-printed','*');});
 await page.goto('/');await page.getByLabel('Correo electrónico',{exact:true}).fill('ana@alia.example');await page.getByLabel('Contraseña',{exact:true}).fill(process.env.DEMO_PASSWORD!);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page.getByRole('heading',{name:'Hola, Ana.'})).toBeVisible();
 await page.goto('/#reports');await page.getByRole('button',{name:'Abrir reporte profesional',exact:true}).click();await expect(page.getByRole('heading',{name:'Pagos y saldo por profesional',exact:true})).toBeVisible();
 await page.getByLabel('Buscar profesional del reporte',{exact:true}).fill('Doctor borrador');await page.getByRole('button',{name:/Doctor borrador.*Activo/}).first().click();await page.getByRole('button',{name:'Consultar reporte profesional',exact:true}).click();await expect(page.getByRole('heading',{name:'Saldo actual · todas las fechas',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Movimientos del periodo',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.locator('section.panel').screenshot({path:'test-results/'+info.project.name+'-professional-report.png'});

 await page.getByRole('button',{name:'Ver documento del reporte profesional',exact:true}).click();const printFrame=page.frameLocator('iframe[title="Vista previa del reporte profesional"]');await expect(printFrame.getByRole('heading',{name:'Saldo actual · todas las fechas',exact:true})).toBeVisible();await expect(printFrame.getByText('no al cierre del periodo',{exact:false})).toBeVisible();await page.evaluate(()=>{window.addEventListener('message',e=>{if(e.data==='report-printed')document.body.dataset.reportPrinted='true';});});await page.getByRole('button',{name:'Imprimir reporte profesional / guardar PDF',exact:true}).click();await expect(page.locator('body')).toHaveAttribute('data-report-printed','true');await page.locator('iframe[title="Vista previa del reporte profesional"]').screenshot({path:'test-results/'+info.project.name+'-professional-report-print.png'});await page.getByRole('button',{name:'Cerrar documento profesional',exact:true}).click();await expect(page.locator('iframe[title="Vista previa del reporte profesional"]')).toHaveCount(0);
 const receipts=page.getByRole('button',{name:'Ver recibo del movimiento',exact:true});if(await receipts.count()){await receipts.first().click();await expect(page.locator('iframe[title="Vista previa del recibo del doctor"]')).toBeVisible();await page.getByRole('button',{name:'Cerrar recibo del doctor',exact:true}).click();}
 await page.getByRole('button',{name:'Ver documento del reporte profesional',exact:true}).click();
 await page.getByLabel('Desde',{exact:true}).fill('2019-01-01');await expect(page.getByRole('heading',{name:'Saldo actual · todas las fechas',exact:true})).toHaveCount(0);await expect(page.locator('iframe[title="Vista previa del reporte profesional"]')).toHaveCount(0);await page.getByLabel('Hasta (incluido)',{exact:true}).fill('2019-01-01');await page.getByRole('button',{name:'Consultar reporte profesional',exact:true}).click();await expect(page.getByText('No hay movimientos en este periodo.',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Saldo actual · todas las fechas',exact:true})).toBeVisible();
});
