import 'dotenv/config';
import { test,expect } from '@playwright/test';
test('reserve a weekly series from reception and see its next occurrence',async({page},info)=>{
 const date=info.project.name==='desktop'?'2047-08-05':'2047-09-05';
 await page.goto('/');await page.getByLabel('Correo electrónico',{exact:true}).fill('ana@alia.example');await page.getByLabel('Contraseña',{exact:true}).fill(process.env.DEMO_PASSWORD!);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page.getByRole('heading',{name:'Hola, Ana.'})).toBeVisible();
 await page.goto('/#agenda');await page.getByLabel('Fecha de la agenda',{exact:true}).fill(date);await page.getByRole('button',{name:'Nueva cita',exact:true}).click();
 await page.getByRole('combobox',{name:'Paciente *',exact:true}).fill('María Fernanda');await page.getByRole('listbox').getByRole('option').first().click();
 for(const [name,search] of [['Profesional','Carlos'],['Consultorio','Consultorio 1'],['Servicio','Limpieza']]){await page.getByRole('combobox',{name:name+' *',exact:true}).fill(search);await page.getByRole('listbox').getByRole('option').first().click();}
 await page.getByRole('button',{name:'Buscar horarios disponibles',exact:true}).click();await expect(page.getByRole('button',{name:'Usar 09:15',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'test-results/'+info.project.name+'-suggestions.png',fullPage:true});await page.getByRole('button',{name:'Usar 09:15',exact:true}).click();await expect(page.getByLabel('Inicio de la cita',{exact:true})).toHaveValue(date+'T09:15');
 await page.getByRole('combobox',{name:'Repetir cita',exact:true}).selectOption('1');await page.getByRole('spinbutton',{name:'Número de citas',exact:true}).fill('2');await page.getByRole('button',{name:'Reservar serie',exact:true}).click();await expect(page.getByRole('heading',{name:'Nueva cita',exact:true})).toHaveCount(0);
 for(const day of [date,date.slice(0,8)+'12']){await page.getByLabel('Fecha de la agenda',{exact:true}).fill(day);const card=page.locator('article').filter({hasText:'Cita de una serie'}).filter({has:page.getByRole('button',{name:'Reprogramar',exact:true})});await expect(card).toHaveCount(1);await card.getByRole('button',{name:'Ver cita',exact:true}).click();await page.getByRole('combobox',{name:'Nuevo estado',exact:true}).selectOption('canceled');await page.getByLabel('Motivo del cambio',{exact:true}).fill('Fin de prueba ficticia');await page.getByRole('button',{name:'Cambiar estado',exact:true}).click();await expect(card).toHaveCount(0);}
});
