import {it,expect} from 'vitest';
import {cashDocumentHtml,type CashDocument,type CountDocument} from '../apps/web/lib/cash-document';
const date='2026-10-01T12:00:00Z';
const closure:CashDocument={id:'corte',author:'<b>Autor</b>',notes:'<script>alert(1)</script>',created_at:date,snapshot:{organization:'Clínica',branch:'Centro',collector:'Todos',timezone:'America/Mexico_City',filters:{from:'2026-09-30',to:'2026-10-01'},totals:[{currency:'MXN',method:'cash',received_minor:12345,voided_minor:20000,net_minor:-7655},{currency:'USD',method:'card',received_minor:500,voided_minor:0,net_minor:500}],events:Array.from({length:25},(_,i)=>({payment_id:'pago-'+i,type:i===24?'void':'payment',occurred_at:date,amount_minor:12345,currency:'MXN',method:'cash',collector:'Personal',reference:'<img src=x onerror=alert(1)>'}))}};
const count:CountDocument={id:'arqueo',version:1,author:'Personal',notes:'Recuento',created_at:date,result:[{currency:'MXN',opening_minor:10000,received_minor:12345,voided_records_minor:20000,adjustment_minor:-1000,expected_minor:21345,counted_minor:21000,difference_minor:-345,difference_reason:'Revisar <faltante>',adjustments:[{direction:'out',amount_minor:1000,reason:'Salida documentada'}]}]};
it('prints complete saved records, keeps currencies separate and escapes all user text',()=>{const html=cashDocumentHtml(closure,count,2,date);expect(html).toContain('pago-24');expect(html).toContain('Movimientos incluidos (25)');expect(html).toContain('-$76.55 MXN');expect(html).toContain('USD');expect(html).toContain('VERSIÓN ANTERIOR');expect(html).toContain('Faltante');expect(html).toContain('-$3.45 MXN');expect(html).toContain('Salida documentada');expect(html).toContain('&lt;faltante&gt;');expect(html).toContain('&lt;script&gt;');expect(html).toContain('&lt;img');expect(html).not.toContain('<script>');expect(html).not.toContain('<img');expect(html).toContain('sin descuento automático');expect(html).toContain('Content-Security-Policy');});
it('distinguishes missing, omitted and latest saved counts',()=>{expect(cashDocumentHtml(closure,null,0,date)).toContain('no significa diferencia cero');expect(cashDocumentHtml(closure,null,2,date)).toContain('no incluido');expect(cashDocumentHtml(closure,count,1,date)).toContain('Última versión consultada');const empty={...closure,snapshot:{...closure.snapshot,totals:[],events:[]}};expect(cashDocumentHtml(empty,null,0,date)).toContain('Sin movimientos en el corte.');});
it('prints expense totals, reversal labels and distinguishes legacy cuts',()=>{
 const current={...closure,snapshot:{...closure.snapshot,schema_version:2,totals:[{currency:'MXN',method:'cash',received_minor:12345,voided_minor:0,paid_minor:1000,payout_voided_minor:500,net_minor:11845}],events:[{...closure.snapshot.events[0],type:'professional_payment',amount_minor:-1000},{...closure.snapshot.events[0],type:'professional_void',amount_minor:500}]}};
 const html=cashDocumentHtml(current,{...count,result:[{...count.result[0],paid_minor:1000,payout_voided_records_minor:500}]},1,date);expect(html).toContain('Pago al doctor');expect(html).toContain('Anulación de pago al doctor');expect(html).toContain('Egresos: doctor y devoluciones descontados');expect(html).toContain('sin reintegro automático');expect(html).toContain('-$10.00 MXN');expect(cashDocumentHtml(closure,count,1,date)).toContain('Corte histórico: no incluye egresos profesionales');
});
