import 'dotenv/config';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import request from 'supertest';
import type { INestApplication } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { createApp } from '../apps/api/src/app';
import { hashPassword, totp } from '../apps/api/src/auth';
import { digest, encrypt } from '../apps/api/src/core';
import { pool, query } from '../packages/database/src/client';
let app:INestApplication;
const origin=process.env.APP_ORIGIN!;
const password='Integration-test-only!2026';
const suffix=randomUUID().slice(0,8);
let userId:string,cookie:string,csrf:string,orgA:string,orgB:string,branchA:string,branchB:string,reader:string,readerCookie:string,readerCsrf:string,ownerRole:string;
function call(method:'get'|'post'|'patch'|'delete',path:string,org=orgA){return request(app.getHttpServer())[method](`/api/${path}`).set('Origin',origin).set('Cookie',cookie).set('X-CSRF-Token',csrf).set('X-Organization-Id',org||'');}
beforeAll(async()=>{
 if(process.env.NODE_ENV==='production')throw new Error('Integration tests must never run in production');
 if(!/^alia_test_[a-f0-9]{12}$/.test(process.env.TEST_DATABASE_NAME||''))throw new Error('Use npm test to create an isolated database');
 app=await createApp();await app.init();
 const [user]=await query('INSERT INTO users(email,name,password_hash) VALUES($1,$2,$3) RETURNING id',[`test-${suffix}@alia.example`,'Integration Owner',await hashPassword(password)]);userId=user.id;
 const login=await request(app.getHttpServer()).post('/api/auth/login').set('Origin',origin).send({email:`test-${suffix}@alia.example`,password});expect(login.status).toBe(201);cookie=login.headers['set-cookie'][0].split(';')[0];
 const me=await request(app.getHttpServer()).get('/api/auth/me').set('Cookie',cookie);csrf=me.body.csrf;
 orgA=(await call('post','organizations').send({name:`Test A ${suffix}`,branch:'A principal'})).body.id;
 orgB=(await call('post','organizations').send({name:`Test B ${suffix}`,branch:'B principal'})).body.id;
 expect(orgA).toBeTruthy();expect(orgB).toBeTruthy();
 branchA=(await call('get','organization')).body.branches[0].id;branchB=(await call('get','organization',orgB)).body.branches[0].id;
 const roles=(await call('get','roles')).body as {id:string;name:string}[];ownerRole=roles.find(r=>r.name==='Propietario')!.id;reader=roles.find(r=>r.name==='Solo lectura')!.id;
 const [u]=await query('INSERT INTO users(email,name,password_hash) VALUES($1,$2,$3) RETURNING id',[`reader-${suffix}@alia.example`,'Reader',await hashPassword(password)]);
 await query('INSERT INTO memberships(organization_id,user_id,role_id) VALUES($1,$2,$3)',[orgA,u.id,reader]);
 const loginReader=await request(app.getHttpServer()).post('/api/auth/login').set('Origin',origin).send({email:`reader-${suffix}@alia.example`,password});readerCookie=loginReader.headers['set-cookie'][0].split(';')[0];readerCsrf=(await request(app.getHttpServer()).get('/api/auth/me').set('Cookie',readerCookie)).body.csrf;
});
afterAll(async()=>{await app?.close();await pool.end();});
describe('Authenticated tenant foundation against real PostgreSQL',()=>{
 it('rejects unknown origins and anonymous access',async()=>{expect((await request(app.getHttpServer()).post('/api/auth/login').set('Origin','https://attacker.invalid').send({email:'x@y.com',password})).status).toBe(403);expect((await request(app.getHttpServer()).get('/api/organization')).status).toBe(401);});
 it('issues HttpOnly same-site sessions without exposing hashes',async()=>{const response=await call('get','auth/me');expect(response.body.user.email).toContain(suffix);expect(JSON.stringify(response.body)).not.toContain('password_hash');expect(response.body.organizations).toHaveLength(2);});
 it('rejects forged CSRF tokens',async()=>{const response=await call('post','branches').set('X-CSRF-Token','fake').send({name:'Bad',address:'',phone:'',active:true});expect(response.status).toBe(403);});
 it('denies tenant B to a member of A even with a valid session',async()=>{const result=await request(app.getHttpServer()).get('/api/organization').set('Cookie',readerCookie).set('X-Organization-Id',orgB);expect(result.status).toBe(403);});
 it('enforces permissions on backend independently of UI',async()=>{const result=await request(app.getHttpServer()).post('/api/branches').set('Origin',origin).set('Cookie',readerCookie).set('X-CSRF-Token',readerCsrf).set('X-Organization-Id',orgA).send({name:'Not allowed',address:'',phone:'',active:true});expect(result.status).toBe(403);});
 it('does not update a branch through another tenant id',async()=>{const result=await call('patch',`branches/${branchB}`).send({name:'Stolen branch',address:'',phone:'',active:true});expect(result.status).toBe(404);const [row]=await query('SELECT name FROM branches WHERE id=$1',[branchB]);expect(row.name).toBe('B principal');});
 it('rejects foreign roles at the database layer',async()=>{const [u]=await query('SELECT id FROM users WHERE email=$1',[`reader-${suffix}@alia.example`]);await expect(query('INSERT INTO memberships(organization_id,user_id,role_id) VALUES($1,$2,$3)',[orgB,u.id,reader])).rejects.toMatchObject({code:'23503',constraint:'memberships_organization_id_role_id_fkey'});});
 it('strictly validates inputs and refuses unrecognized properties',async()=>{const result=await call('post','branches').send({name:'Test',address:'',phone:'',active:true,organization_id:orgB});expect(result.status).toBe(400);});
 it('records successful changes atomically',async()=>{const result=await call('patch',`branches/${branchA}`).send({name:'Renamed A',address:'Fictional',phone:'',active:true});expect(result.status).toBe(200);const [audit]=await query("SELECT before,after FROM audit_logs WHERE entity_id=$1 AND action='branch.updated'",[branchA]);expect(audit.before.name).toBe('A principal');expect(audit.after.name).toBe('Renamed A');});
 it('prevents audit mutation at database level',async()=>{await expect(query('DELETE FROM audit_logs WHERE organization_id=$1',[orgA])).rejects.toMatchObject({code:'42501'});});
 it('protects system roles and self demotion',async()=>{expect((await call('patch',`roles/${ownerRole}`).send({name:'Altered',permissions:[]})).status).toBe(400);expect((await call('patch',`members/${userId}`).send({role_id:reader,active:false})).status).toBe(400);});
 it('creates custom roles with persisted permission grants',async()=>{const result=await call('post','roles').send({name:`Reception ${suffix}`,permissions:['organizations.view','patients.view']});expect(result.status).toBe(201);const [r]=await query('SELECT count(*)::int AS count FROM role_permissions WHERE role_id=$1',[result.body.id]);expect(r.count).toBe(2);});
 it('uses cursor pagination scoped to the current organization',async()=>{for(let n=0;n<35;n++)await query("INSERT INTO audit_logs(organization_id,action,entity) VALUES($1,'test.event','test')",[orgA]);const first=await call('get','audit');expect(first.body.items).toHaveLength(30);expect(first.body.nextCursor).toBeTruthy();const second=await call('get',`audit?cursor=${encodeURIComponent(first.body.nextCursor)}`);expect(second.status).toBe(200);const firstIds=new Set(first.body.items.map((i:{id:string})=>i.id));expect(second.body.items.some((i:{id:string})=>firstIds.has(i.id))).toBe(false);});
 it('persists progressive login lockout',async()=>{const email=`lock-${suffix}@alia.example`;const [u]=await query('INSERT INTO users(email,name,password_hash) VALUES($1,$2,$3) RETURNING id',[email,'Lock test',await hashPassword(password)]);for(let i=0;i<5;i++)expect((await request(app.getHttpServer()).post('/api/auth/login').set('Origin',origin).send({email,password:'wrong-password'})).status).toBe(401);const [row]=await query('SELECT failed_attempts,locked_until FROM users WHERE id=$1',[u.id]);expect(row.failed_attempts).toBe(5);expect(new Date(row.locked_until).getTime()).toBeGreaterThan(Date.now());});
 it('MFA validates TOTP, prevents replay, and consumes recovery codes once',async()=>{const email=`mfa-${suffix}@alia.example`,secret='JBSWY3DPEHPK3PXP';const [u]=await query('INSERT INTO users(email,name,password_hash,mfa_secret) VALUES($1,$2,$3,$4) RETURNING id',[email,'MFA test',await hashPassword(password),encrypt(secret)]);const code=totp(secret).generate();const attempt=(code:string)=>request(app.getHttpServer()).post('/api/auth/login').set('Origin',origin).send({email,password,code});expect((await attempt(code)).status).toBe(201);expect((await attempt(code)).status).toBe(401);await query('INSERT INTO recovery_codes(user_id,code_hash) VALUES($1,$2)',[u.id,digest('single-use-recovery')]);expect((await attempt('single-use-recovery')).status).toBe(201);expect((await attempt('single-use-recovery')).status).toBe(401);});
 it('password reset is single-use and revokes sessions',async()=>{const raw=`reset-${randomUUID()}`;await query("INSERT INTO password_resets(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '5 minutes')",[userId,digest(raw)]);const reset=()=>request(app.getHttpServer()).post('/api/auth/reset-password').set('Origin',origin).send({token:raw,password:'new-integration-password!'});expect((await reset()).status).toBe(201);expect((await reset()).status).toBe(400);expect((await call('get','auth/me')).status).toBe(401);});
});
