export type BudgetSnapshot={budget:{version:number;plan_version:number;title:string;currency:string;total_minor:number;created_at:string;items:{title:string;tooth:string;quantity:number;unit_minor:number;discount_minor:number;total_minor:number}[]};patient:{first_name:string;last_name:string;record_number:string};organization:{name:string;address:string;phone:string;timezone:string}};
export type BudgetAcceptance={id:string;version:number;accepted_by:string;relationship:string;notes:string;created_at:string;author:string};
export type BudgetDocument={payment_locked?:boolean;snapshot:BudgetSnapshot;acceptance:BudgetAcceptance|null;latest:number;current_accepted_version:number|null};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function budgetHtml(data:BudgetDocument){
 const {budget:b,patient:p,organization:o}=data.snapshot,a=data.acceptance;
 const money=(n:number)=>esc(new Intl.NumberFormat('es-MX',{style:'currency',currency:b.currency}).format(n/100));
 const date=(s:string)=>esc(new Date(s).toLocaleString('es-MX',{timeZone:o.timezone||'America/Mexico_City'}));
 return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${esc(b.title)}</title><style>@page{size:A4;margin:18mm}*{box-sizing:border-box}body{margin:0;padding:24px;font:14px/1.5 Arial,sans-serif;color:#173544;overflow-wrap:anywhere}header{border-bottom:2px solid #078177;padding-bottom:12px}h1{font-size:23px}p{white-space:pre-wrap}.state{padding:10px;border:2px solid;font-weight:bold}.line{padding:16px 0;border-bottom:1px solid #ccd9dd;break-inside:avoid}.line h2{font-size:16px;margin:0}.amounts{display:flex;gap:16px;flex-wrap:wrap}.total{font-size:22px;font-weight:bold;text-align:right}.meta,footer{font-size:12px}footer{margin-top:24px}@media print{body{padding:0;font-size:11pt}}</style></head><body><header><p class="state">${a?(a.version===data.current_accepted_version?'ACEPTACIÓN REGISTRADA':'ACUERDO ANTERIOR · SUSTITUIDO'):'PROPUESTA · SIN ACEPTACIÓN REGISTRADA'}</p><h1>${esc(b.title)}</h1><p>${esc(o.name)}<br>${esc(o.address)}${o.phone?'<br>Teléfono: '+esc(o.phone):''}</p><p>Paciente: ${esc(p.first_name)} ${esc(p.last_name)}<br>Expediente: ${esc(p.record_number)}</p><p class="meta">Presupuesto versión ${esc(b.version)} · Plan versión ${esc(b.plan_version)} · Moneda ${esc(b.currency)}<br>Preparado: ${date(b.created_at)}</p></header>${b.items.map((i,n)=>`<section class="line"><h2>${n+1}. ${esc(i.title)}</h2>${i.tooth?`<p>Pieza ${esc(i.tooth)}</p>`:''}<div class="amounts"><span>Cantidad: ${esc(i.quantity)}</span><span>Precio unitario: ${money(i.unit_minor)}</span><span>Descuento: ${money(i.discount_minor)}</span></div><p>Importe: <strong>${money(i.total_minor)}</strong></p></section>`).join('')}<p class="total">Total: ${money(b.total_minor)} ${esc(b.currency)}</p>${a?`<section><h2>Registro de aceptación</h2><p>Folio: ${esc(a.id)}<br>Persona que acepta: ${esc(a.accepted_by)} · ${esc(a.relationship)}<br>Registrado por: ${esc(a.author)} · ${date(a.created_at)}</p>${a.notes?`<p>Observaciones: ${esc(a.notes)}</p>`:''}</section>`:'<p>Propuesta pendiente de aceptación. Los datos del paciente y clínica se conservarán al registrar el acuerdo.</p>'}<footer>Este documento no es comprobante de pago ni factura. La aceptación la registra el personal; no constituye firma electrónica ni consentimiento clínico. No se han registrado pagos mediante esta operación.</footer></body></html>`;
}

