import {BadRequestException,Body,ConflictException,Controller,Get,Inject,NotFoundException,Param,Post,Query,Req} from '@nestjs/common';
import {Temporal} from '@js-temporal/polyfill';
import {z} from 'zod';
import type {PoolClient} from 'pg';
import {Access,type AuthRequest,audit,digest,parse,uuid} from './core';
import {patientTransaction} from './patients';
import {query} from '../../../packages/database/src/client';
const filters=z.object({from:z.iso.date(),to:z.iso.date(),branch_id:uuid,collector_id:uuid.optional()}).strict();
async function report(org:string,f:z.infer<typeof filters>,c:PoolClient){
 const [organization]=await query('SELECT name,timezone FROM organizations WHERE id=$1',[org],c),[branch]=await query('SELECT name FROM branches WHERE organization_id=$1 AND id=$2',[org,f.branch_id],c);
 if(!branch)throw new BadRequestException('Selecciona una sucursal de esta clínica.');
 const start=Temporal.PlainDate.from(f.from),end=Temporal.PlainDate.from(f.to);if(Temporal.PlainDate.compare(start,end)>0||start.until(end).days>30)throw new BadRequestException('El periodo debe abarcar de 1 a 31 días.');
 const today=Temporal.Now.plainDateISO(organization.timezone);if(Temporal.PlainDate.compare(end,today)>0)throw new BadRequestException('El periodo no puede terminar en una fecha futura.');
 let collector='Todos los responsables';if(f.collector_id){const [u]=await query('SELECT u.name FROM users u WHERE u.id=$2 AND (EXISTS(SELECT 1 FROM memberships m WHERE m.organization_id=$1 AND m.user_id=u.id) OR EXISTS(SELECT 1 FROM patient_payments p WHERE p.organization_id=$1 AND p.created_by=u.id) OR EXISTS(SELECT 1 FROM professional_payments p WHERE p.organization_id=$1 AND p.created_by=u.id))',[org,f.collector_id],c);if(!u)throw new BadRequestException('El responsable no pertenece a esta clínica.');collector=u.name;}
 const from=start.toZonedDateTime(organization.timezone).toInstant().toString(),to=end.add({days:1}).toZonedDateTime(organization.timezone).toInstant().toString();
 const events=await query("SELECT p.id AS payment_id,'payment' AS type,p.created_at AS occurred_at,p.amount_minor::float8 AS amount_minor,p.method,b.snapshot->'budget'->>'currency' AS currency,coalesce(p.receipt_context->>'recorded_by',u.name) AS collector,p.reference FROM patient_payments p JOIN budget_acceptances b ON b.organization_id=p.organization_id AND b.id=p.acceptance_id JOIN users u ON u.id=p.created_by WHERE p.organization_id=$1 AND p.branch_id=$2 AND ($3::uuid IS NULL OR p.created_by=$3) AND p.created_at >= $4 AND p.created_at < $5 UNION ALL SELECT p.id,'void',v.created_at,-p.amount_minor::float8,p.method,b.snapshot->'budget'->>'currency',coalesce(p.receipt_context->>'recorded_by',u.name),v.reason FROM payment_voids v JOIN patient_payments p ON p.organization_id=v.organization_id AND p.id=v.payment_id JOIN budget_acceptances b ON b.organization_id=p.organization_id AND b.id=p.acceptance_id JOIN users u ON u.id=p.created_by WHERE p.organization_id=$1 AND p.branch_id=$2 AND ($3::uuid IS NULL OR p.created_by=$3) AND v.created_at >= $4 AND v.created_at < $5 UNION ALL SELECT p.id,'professional_payment',p.created_at,-p.amount_minor::float8,p.method,s.currency,u.name,p.reference FROM professional_payments p JOIN professional_shares s ON s.organization_id=p.organization_id AND s.id=p.share_id JOIN users u ON u.id=p.created_by WHERE p.organization_id=$1 AND p.branch_id=$2 AND ($3::uuid IS NULL OR p.created_by=$3) AND p.created_at >= $4 AND p.created_at < $5 UNION ALL SELECT p.id,'professional_void',v.created_at,p.amount_minor::float8,p.method,s.currency,u.name,v.reason FROM professional_payment_voids v JOIN professional_payments p ON p.organization_id=v.organization_id AND p.id=v.payment_id JOIN professional_shares s ON s.organization_id=p.organization_id AND s.id=p.share_id JOIN users u ON u.id=p.created_by WHERE p.organization_id=$1 AND p.branch_id=$2 AND ($3::uuid IS NULL OR p.created_by=$3) AND v.created_at >= $4 AND v.created_at < $5 UNION ALL SELECT r.id,'refund',r.created_at,-r.amount_minor::float8,r.method,r.currency,u.name,r.reference FROM patient_refunds r JOIN users u ON u.id=r.created_by WHERE r.organization_id=$1 AND r.branch_id=$2 AND ($3::uuid IS NULL OR r.created_by=$3) AND r.created_at>=$4 AND r.created_at<$5 ORDER BY occurred_at,payment_id,type LIMIT 2001",[org,f.branch_id,f.collector_id||null,from,to],c);
 if(events.length>2000)throw new BadRequestException('Hay más de 2000 movimientos. Reduce el periodo o selecciona un responsable.');
 const totals:Record<string,{currency:string;method:string;received_minor:number;voided_minor:number;paid_minor:number;payout_voided_minor:number;net_minor:number}>={};
 for(const e of events){const key=e.currency+':'+e.method;const t=totals[key]||={currency:e.currency,method:e.method,received_minor:0,voided_minor:0,paid_minor:0,payout_voided_minor:0,net_minor:0};if(e.type==='payment')t.received_minor+=e.amount_minor;else if(e.type==='void')t.voided_minor-=e.amount_minor;else if((e.type==='professional_payment'||e.type==='refund'))t.paid_minor-=e.amount_minor;else t.payout_voided_minor+=e.amount_minor;t.net_minor+=e.amount_minor;}
 return {schema_version:3,filters:f,organization:organization.name,timezone:organization.timezone,branch:branch.name,collector,totals:Object.values(totals).sort((a,b)=>(a.currency+a.method).localeCompare(b.currency+b.method)),events};
}
@Controller('api/cash-closures')
export class CashClosuresController{
 constructor(@Inject(Access)private access:Access){}
 @Get('options') async options(@Req()req:AuthRequest){const a=await this.access.tenant(req,'cash_closures.view');return patientTransaction(a.organizationId!,async c=>{const branches=await query('SELECT id,name FROM branches WHERE organization_id=$1 ORDER BY name,id',[a.organizationId],c),collectors=await query('SELECT u.id,u.name FROM users u WHERE EXISTS(SELECT 1 FROM patient_payments p WHERE p.created_by=u.id AND p.organization_id=$1) OR EXISTS(SELECT 1 FROM professional_payments p WHERE p.created_by=u.id AND p.organization_id=$1) OR EXISTS(SELECT 1 FROM patient_refunds p WHERE p.created_by=u.id AND p.organization_id=$1) ORDER BY u.name,u.id',[a.organizationId],c);const [o]=await query('SELECT timezone FROM organizations WHERE id=$1',[a.organizationId],c);return {branches,collectors,today:Temporal.Now.plainDateISO(o.timezone).toString(),timezone:o.timezone};});}
 @Get('preview') async preview(@Query()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'cash_closures.view'),f=parse(filters,raw);return patientTransaction(a.organizationId!,async c=>{const snapshot=await report(a.organizationId!,f,c);await audit(req,'cash.previewed','organization',a.organizationId!,a.organizationId!,a.id,{},c);return {snapshot,token:digest(JSON.stringify(snapshot))};});}
 @Get() async list(@Query()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'cash_closures.view'),{page}=parse(z.object({page:z.coerce.number().int().min(1).max(100000).default(1)}).strict(),raw);return patientTransaction(a.organizationId!,async c=>{const rows=await query("SELECT x.id,x.created_at,u.name AS author,x.snapshot->>'branch' AS branch,x.snapshot->'filters' AS filters FROM cash_closures x JOIN users u ON u.id=x.created_by WHERE organization_id=$1 ORDER BY created_at DESC,id LIMIT 21 OFFSET $2",[a.organizationId,(page-1)*20],c);return {items:rows.slice(0,20),hasMore:rows.length>20};});}
 @Get(':id') async detail(@Param('id')id:string,@Req()req:AuthRequest){const a=await this.access.tenant(req,'cash_closures.view');parse(uuid,id);return patientTransaction(a.organizationId!,async c=>{const [row]=await query('SELECT x.id,x.snapshot,x.notes,x.created_at,u.name AS author FROM cash_closures x JOIN users u ON u.id=x.created_by WHERE organization_id=$1 AND x.id=$2',[a.organizationId,id],c);if(!row)throw new NotFoundException('No encontramos ese corte.');await audit(req,'cash.viewed','cash-closure',id,a.organizationId!,a.id,{},c);return row;});}
 @Post() async save(@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'cash_closures.view');await this.access.tenant(req,'cash_closures.create');const input=parse(z.object({request_id:uuid,filters,token:z.string().regex(/^[a-f0-9]{64}$/),notes:z.string().trim().max(2000),reviewed:z.literal(true)}).strict(),raw),hash=digest(JSON.stringify(input));return patientTransaction(a.organizationId!,async c=>{
 await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':cash:'+input.request_id],c);
 const [prior]=await query('SELECT id,request_hash FROM cash_closures WHERE organization_id=$1 AND request_id=$2',[a.organizationId,input.request_id],c);if(prior){if(prior.request_hash!==hash)throw new ConflictException('La solicitud ya se usó con otro contenido.');return {id:prior.id};}
 const snapshot=await report(a.organizationId!,input.filters,c);if(digest(JSON.stringify(snapshot))!==input.token)throw new ConflictException('Los movimientos cambiaron. Actualiza y revisa el corte antes de guardarlo.');
 const [row]=await query('INSERT INTO cash_closures(organization_id,request_id,request_hash,snapshot,notes,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[a.organizationId,input.request_id,hash,JSON.stringify(snapshot),input.notes,a.id],c);await audit(req,'cash.saved','cash-closure',row.id,a.organizationId!,a.id,{},c);return row;
 });}
}
