import {Body,ConflictException,Controller,Get,Inject,NotFoundException,Param,Patch,Post,Query,Req} from '@nestjs/common';
import {z} from 'zod';
import {Access,type AuthRequest,audit,digest,parse,uuid} from './core';
import {patientTransaction} from './patients';
import {query} from '../../../packages/database/src/client';
const itemFields=z.object({sku:z.string().trim().min(1).max(60),name:z.string().trim().min(1).max(160),unit:z.string().trim().min(1).max(40),minimum:z.number().int().min(0).max(1000000)}).strict();
@Controller('api/inventory')
export class InventoryController{
 constructor(@Inject(Access)private access:Access){}
 @Get('options') async options(@Req()req:AuthRequest){const a=await this.access.tenant(req,'inventory.view');return patientTransaction(a.organizationId!,async c=>({branches:await query('SELECT id,name,active FROM branches WHERE organization_id=$1 ORDER BY name,id',[a.organizationId],c)}));}
 @Get() async list(@Query()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'inventory.view'),input=parse(z.object({branch_id:uuid,q:z.string().trim().max(100).default(''),page:z.coerce.number().int().min(1).max(100000).default(1)}).strict(),raw);return patientTransaction(a.organizationId!,async c=>{if(!(await query('SELECT id FROM branches WHERE organization_id=$1 AND id=$2',[a.organizationId,input.branch_id],c)).length)throw new NotFoundException('No encontramos la sucursal.');const rows=await query("SELECT i.id,i.sku,i.name,i.unit,i.minimum,i.active,i.version,coalesce((SELECT sum(quantity) FROM inventory_movements m WHERE m.organization_id=i.organization_id AND m.item_id=i.id AND m.branch_id=$2),0)::float8 AS stock FROM inventory_items i WHERE i.organization_id=$1 AND (i.name ILIKE $3 OR i.sku ILIKE $3) ORDER BY i.name,i.id LIMIT 21 OFFSET $4",[a.organizationId,input.branch_id,'%'+input.q.replace(/[\\%_]/g,'\\$&')+'%',(input.page-1)*20],c);return {items:rows.slice(0,20),hasMore:rows.length>20};});}
 @Post() async create(@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'inventory.edit'),input=parse(itemFields.extend({request_id:uuid}),raw),hash=digest(JSON.stringify(input));return patientTransaction(a.organizationId!,async c=>{await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':inventory:'+input.request_id],c);const [prior]=await query('SELECT id,request_hash FROM inventory_items WHERE organization_id=$1 AND request_id=$2',[a.organizationId,input.request_id],c);if(prior){if(prior.request_hash!==hash)throw new ConflictException('La solicitud ya se usó con otros datos.');return {id:prior.id};}const [row]=await query('INSERT INTO inventory_items(organization_id,request_id,request_hash,sku,name,unit,minimum,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[a.organizationId,input.request_id,hash,input.sku,input.name,input.unit,input.minimum,a.id],c);await audit(req,'inventory.item_created','inventory_item',row.id,a.organizationId!,a.id,{},c);return row;});}
 @Patch(':id') async edit(@Param('id')id:string,@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'inventory.edit');parse(uuid,id);const input=parse(z.object({version:z.number().int().positive(),name:z.string().trim().min(1).max(160),minimum:z.number().int().min(0).max(1000000),active:z.boolean()}).strict(),raw);return patientTransaction(a.organizationId!,async c=>{const [row]=await query('UPDATE inventory_items SET name=$3,minimum=$4,active=$5,version=version+1 WHERE organization_id=$1 AND id=$2 AND version=$6 RETURNING id,version',[a.organizationId,id,input.name,input.minimum,input.active,input.version],c);if(!row)throw new ConflictException('El artículo cambió o no está disponible. Actualiza.');await audit(req,'inventory.item_updated','inventory_item',id,a.organizationId!,a.id,{after:input},c);return row;});}
 @Get(':id/movements') async history(@Param('id')id:string,@Query()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'inventory.view');parse(uuid,id);const input=parse(z.object({branch_id:uuid,page:z.coerce.number().int().min(1).max(100000).default(1)}).strict(),raw);return patientTransaction(a.organizationId!,async c=>{const rows=await query('SELECT m.id,m.quantity,m.kind,m.reason,m.created_at,u.name AS author FROM inventory_movements m JOIN users u ON u.id=m.created_by WHERE m.organization_id=$1 AND m.item_id=$2 AND m.branch_id=$3 ORDER BY m.created_at DESC,m.id DESC LIMIT 21 OFFSET $4',[a.organizationId,id,input.branch_id,(input.page-1)*20],c);return {items:rows.slice(0,20),hasMore:rows.length>20};});}
 @Post(':id/movements') async move(@Param('id')id:string,@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'inventory.edit');parse(uuid,id);const input=parse(z.object({request_id:uuid,branch_id:uuid,quantity:z.number().int().min(-1000000).max(1000000).refine(v=>v!==0),kind:z.enum(['entry','exit','adjustment']),reason:z.string().trim().min(1).max(1000)}).strict(),raw),hash=digest(JSON.stringify({...input,id}));if(input.kind==='entry'&&input.quantity<0||input.kind==='exit'&&input.quantity>0)throw new ConflictException('Entradas positivas y salidas negativas.');return patientTransaction(a.organizationId!,async c=>{
  await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':inventory:'+input.request_id],c);const [prior]=await query('SELECT id,request_hash FROM inventory_movements WHERE organization_id=$1 AND request_id=$2',[a.organizationId,input.request_id],c);if(prior){if(prior.request_hash!==hash)throw new ConflictException('La solicitud ya se usó con otros datos.');return {id:prior.id};}
  const [item]=await query('SELECT active FROM inventory_items WHERE organization_id=$1 AND id=$2 FOR UPDATE',[a.organizationId,id],c);if(!item?.active)throw new ConflictException('Selecciona un artículo activo.');if(!(await query('SELECT id FROM branches WHERE organization_id=$1 AND id=$2 AND active FOR SHARE',[a.organizationId,input.branch_id],c)).length)throw new ConflictException('Selecciona una sucursal activa.');
  const [stock]=await query('SELECT coalesce(sum(quantity),0)::float8 AS stock FROM inventory_movements WHERE organization_id=$1 AND item_id=$2 AND branch_id=$3',[a.organizationId,id,input.branch_id],c);if(stock.stock+input.quantity<0)throw new ConflictException('La salida supera la existencia disponible. Actualiza el inventario.');
  const [row]=await query('INSERT INTO inventory_movements(organization_id,item_id,branch_id,quantity,kind,reason,request_id,request_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[a.organizationId,id,input.branch_id,input.quantity,input.kind,input.reason,input.request_id,hash,a.id],c);await audit(req,'inventory.movement_recorded','inventory_item',id,a.organizationId!,a.id,{after:{movement_id:row.id,quantity:input.quantity,branch_id:input.branch_id}},c);return row;
 });}
}
