import {Body,ConflictException,Controller,Get,Inject,NotFoundException,Param,Post,Patch,Query,Req} from '@nestjs/common';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {Access,type AuthRequest,audit,digest,parse,uuid} from './core';
import {patientTransaction} from './patients';
import {query} from '../../../packages/database/src/client';
const fields=z.object({name:z.string().trim().min(1).max(160),contact:z.string().trim().max(180),phone:z.string().trim().max(30)}).strict();
@Controller('api/laboratories')
export class LaboratoriesController{
 constructor(@Inject(Access)private access:Access){}
 @Get() async list(@Query()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'catalogs.view'),input=parse(z.object({q:z.string().trim().max(100).default('')}).strict(),raw);return patientTransaction(a.organizationId!,async c=>{const items=await query('SELECT * FROM laboratories WHERE organization_id=$1 AND name ILIKE $2 ORDER BY name,id LIMIT 51',[a.organizationId,'%'+input.q.replace(/[\\%_]/g,'\\$&')+'%'],c);return {items:items.slice(0,50),hasMore:items.length>50};});}
 @Post() async create(@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'catalogs.manage'),input=parse(fields,raw);return patientTransaction(a.organizationId!,async c=>{const [r]=await query('INSERT INTO laboratories(organization_id,name,contact,phone) VALUES($1,$2,$3,$4) RETURNING id',[a.organizationId,input.name,input.contact,input.phone],c);await audit(req,'laboratory.created','laboratory',r.id,a.organizationId!,a.id,{},c);return r;});}
 @Patch(':id') async edit(@Param('id')id:string,@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'catalogs.manage');parse(uuid,id);const input=parse(fields.extend({version:z.number().int().positive(),active:z.boolean()}),raw);return patientTransaction(a.organizationId!,async c=>{const [r]=await query('UPDATE laboratories SET name=$3,contact=$4,phone=$5,active=$6,version=version+1 WHERE organization_id=$1 AND id=$2 AND version=$7 RETURNING id,version',[a.organizationId,id,input.name,input.contact,input.phone,input.active,input.version],c);if(!r)throw new ConflictException('El laboratorio cambió. Actualiza antes de guardar.');await audit(req,'laboratory.updated','laboratory',id,a.organizationId!,a.id,{},c);return r;});}
}
@Controller('api/patients/:patientId/laboratory-orders')
export class LaboratoryOrdersController{
 constructor(@Inject(Access)private access:Access){}
 private async actor(req:AuthRequest,id:string,edit=false){const a=await this.access.tenant(req,'patients.view');await this.access.tenant(req,'clinical_records.view');if(edit)await this.access.tenant(req,'clinical_records.edit');parse(uuid,id);return a;}
 @Get('options') async options(@Param('patientId')id:string,@Req()req:AuthRequest){const a=await this.actor(req,id);return patientTransaction(a.organizationId!,async c=>({laboratories:await query('SELECT id,name FROM laboratories WHERE organization_id=$1 AND active ORDER BY name,id LIMIT 100',[a.organizationId],c),branches:await query('SELECT id,name FROM branches WHERE organization_id=$1 AND active ORDER BY name,id',[a.organizationId],c)}));}
 @Get() async list(@Param('patientId')id:string,@Req()req:AuthRequest){const a=await this.actor(req,id);return patientTransaction(a.organizationId!,async c=>{if(!(await query('SELECT id FROM patients WHERE organization_id=$1 AND id=$2',[a.organizationId,id],c)).length)throw new NotFoundException('No encontramos al paciente.');const rows=await query('SELECT * FROM (SELECT DISTINCT ON (r.id) r.*,to_char(due_date,\'YYYY-MM-DD\') AS due,u.name AS author,b.name AS branch FROM laboratory_order_versions r JOIN users u ON u.id=r.created_by JOIN branches b ON b.organization_id=r.organization_id AND b.id=r.branch_id WHERE r.organization_id=$1 AND patient_id=$2 ORDER BY r.id,version DESC) latest ORDER BY created_at DESC,id LIMIT 51',[a.organizationId,id],c);await audit(req,'laboratory_orders.viewed','patient',id,a.organizationId!,a.id,{},c);return {items:rows.slice(0,50),hasMore:rows.length>50};});}
 @Get(':id/history') async history(@Param('patientId')patient:string,@Param('id')id:string,@Req()req:AuthRequest){const a=await this.actor(req,patient);parse(uuid,id);return patientTransaction(a.organizationId!,async c=>{const items=await query('SELECT r.*,u.name AS author FROM laboratory_order_versions r JOIN users u ON u.id=r.created_by WHERE organization_id=$1 AND patient_id=$2 AND r.id=$3 ORDER BY version DESC LIMIT 100',[a.organizationId,patient,id],c);if(!items.length)throw new NotFoundException('No encontramos la orden.');await audit(req,'laboratory_order.history_viewed','patient',patient,a.organizationId!,a.id,{after:{order_id:id}},c);return {items};});}
 @Post() async save(@Param('patientId')patient:string,@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.actor(req,patient,true),input=parse(z.object({request_id:uuid,id:uuid.optional(),version:z.number().int().nonnegative(),laboratory_id:uuid.optional(),branch_id:uuid.optional(),description:z.string().trim().max(3000).default(''),due_date:z.iso.date().optional(),state:z.enum(['requested','sent','received','delivered','canceled']),notes:z.string().trim().min(1).max(3000),report:z.string().trim().max(10000).default('')}).strict(),raw),hash=digest(JSON.stringify({...input,patient}));return patientTransaction(a.organizationId!,async c=>{
  await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':laboratory-orders:'+patient],c);const [prior]=await query('SELECT id,version,request_hash FROM laboratory_order_versions WHERE organization_id=$1 AND request_id=$2',[a.organizationId,input.request_id],c);if(prior){if(prior.request_hash!==hash)throw new ConflictException('La solicitud ya se usó.');return {id:prior.id,version:prior.version};}
  const [p]=await query('SELECT active FROM patients WHERE organization_id=$1 AND id=$2',[a.organizationId,patient],c);if(!p)throw new NotFoundException('No encontramos al paciente.');if(!p.active)throw new ConflictException('La ficha está inactiva.');
  let lab=input.laboratory_id,name='',branch=input.branch_id,description=input.description,due=input.due_date,report=input.report;
  if(input.id){const [old]=await query('SELECT * FROM laboratory_order_versions WHERE organization_id=$1 AND patient_id=$2 AND id=$3 ORDER BY version DESC LIMIT 1',[a.organizationId,patient,input.id],c);if(!old)throw new NotFoundException('No encontramos la orden.');if(old.version!==input.version)throw new ConflictException('La orden cambió. Actualiza antes de guardar.');const transitions:Record<string,string[]>={requested:['sent','canceled'],sent:['sent','received','canceled'],received:['received','delivered','canceled'],delivered:[],canceled:[]};if(!transitions[old.state].includes(input.state))throw new ConflictException('Ese cambio de estado no está permitido.');lab=old.laboratory_id;name=old.laboratory_name;branch=old.branch_id;description=old.description;due=old.due_date;report=input.report||old.report;
  }else{if(input.version!==0||input.state!=='requested'||!lab||!branch||!description||!due)throw new ConflictException('Completa laboratorio, sucursal, trabajo y fecha prevista.');const [l]=await query('SELECT name FROM laboratories WHERE organization_id=$1 AND id=$2 AND active',[a.organizationId,lab],c);if(!l||!(await query('SELECT id FROM branches WHERE organization_id=$1 AND id=$2 AND active',[a.organizationId,branch],c)).length)throw new ConflictException('Selecciona laboratorio y sucursal activos.');name=l.name;}
  if(['received','delivered'].includes(input.state)&&!report)throw new ConflictException('Registra el resultado recibido del laboratorio.');const id=input.id||randomUUID();await query('INSERT INTO laboratory_order_versions(organization_id,patient_id,id,version,laboratory_id,laboratory_name,branch_id,description,due_date,state,notes,report,request_id,request_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)',[a.organizationId,patient,id,input.version+1,lab,name,branch,description,due,input.state,input.notes,report,input.request_id,hash,a.id],c);await audit(req,'laboratory_order.recorded','patient',patient,a.organizationId!,a.id,{after:{order_id:id,state:input.state,version:input.version+1}},c);return {id,version:input.version+1};
 });}
}
