import { Body, Controller, Delete, Get, Inject, Param, Patch, Post, Query, Req, BadRequestException, NotFoundException, ForbiddenException } from '@nestjs/common';
import { ApiTags } from '@nestjs/swagger';
import { z } from 'zod';
import { query, transaction, type Connection } from '../../../packages/database/src/client';
import { rolePermissions } from '../../../packages/database/src/roles';
import { Access, type AuthRequest, parse, uuid, email, audit, token, digest } from './core';
import { enqueueMail } from './mail-worker';
const name=z.string().trim().min(2).max(160);
const orgInput=z.object({name,legal_name:z.string().max(200),rfc:z.string().max(13).regex(/^[A-ZÑ&0-9]*$/),phone:z.string().max(30),email:z.union([z.literal(''),email]),address:z.string().max(500),timezone:z.string().refine(v=>{try{new Intl.DateTimeFormat('es',{timeZone:v});return true;}catch{return false;}},'Zona horaria inválida'),currency:z.enum(['MXN','USD','EUR']),locale:z.enum(['es-MX','en-US']),record_prefix:z.string().regex(/^[A-Z]{1,6}$/)}).strict();
const branchInput=z.object({name,address:z.string().max(500),phone:z.string().max(30),active:z.boolean()}).strict();
async function roleAllowed(id:string,org:string,permissions:string[],c?:Connection){
 const [role]=await query('SELECT id FROM roles WHERE id=$1 AND organization_id=$2',[id,org],c);if(!role)throw new NotFoundException('No encontramos ese rol.');
 const codes=await query<{permission_code:string}>('SELECT permission_code FROM role_permissions WHERE role_id=$1 AND organization_id=$2',[id,org],c);
 if(codes.some(r=>!permissions.includes(r.permission_code)))throw new ForbiddenException('No puedes conceder permisos que no tienes.');
}
@ApiTags('Organizaciones, sucursales y RBAC')
@Controller('api')
export class OrganizationsController {
 constructor(@Inject(Access)private access:Access){}
 @Get('organization') async current(@Req()req:AuthRequest){const a=await this.access.tenant(req);const [organization]=await query('SELECT id,name,legal_name,rfc,phone,email,address,timezone,currency,locale,record_prefix,created_at FROM organizations WHERE id=$1',[a.organizationId]);const branches=await query('SELECT id,name,address,phone,active FROM branches WHERE organization_id=$1 ORDER BY name',[a.organizationId]);const [counts]=await query('SELECT (SELECT count(*)::int FROM memberships WHERE organization_id=$1 AND active) AS members,(SELECT count(*)::int FROM roles WHERE organization_id=$1) AS roles',[a.organizationId]);return {organization,branches,permissions:a.permissions,counts};}
 @Post('organizations') async create(@Body()body:unknown,@Req()req:AuthRequest){const a=await this.access.session(req);const input=parse(z.object({name,branch:name}).strict(),body);await this.access.rate(`org-create:${a.id}`,5,3600);return transaction(async c=>{
  const [account]=await query('INSERT INTO accounts(name) VALUES($1) RETURNING id',[input.name],c);const [org]=await query('INSERT INTO organizations(account_id,name) VALUES($1,$2) RETURNING id',[account.id,input.name],c);
  await query('INSERT INTO branches(organization_id,name) VALUES($1,$2)',[org.id,input.branch],c);const all=(await query<{code:string}>('SELECT code FROM permissions',[],c)).map(r=>r.code);let owner='';
  for(const [name,codes] of Object.entries(rolePermissions)){const [r]=await query('INSERT INTO roles(organization_id,name,system) VALUES($1,$2,true) RETURNING id',[org.id,name],c);if(name==='Propietario')owner=r.id;for(const code of codes[0]==='*'?all:codes)await query('INSERT INTO role_permissions VALUES($1,$2,$3)',[org.id,r.id,code],c);}
  await query('INSERT INTO memberships(organization_id,user_id,role_id) VALUES($1,$2,$3)',[org.id,a.id,owner],c);await audit(req,'organization.created','organization',org.id,org.id,a.id,{after:input},c);return org;
 });}
 @Patch('organization') async update(@Body()body:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'settings.manage');const input=parse(orgInput,body);return transaction(async c=>{const [before]=await query('SELECT name,legal_name,rfc,phone,email,address,timezone,currency,locale,record_prefix FROM organizations WHERE id=$1 FOR UPDATE',[a.organizationId],c);await query('UPDATE organizations SET name=$2,legal_name=$3,rfc=$4,phone=$5,email=$6,address=$7,timezone=$8,currency=$9,locale=$10,record_prefix=$11,updated_at=now() WHERE id=$1',[a.organizationId,...Object.values(input)],c);await audit(req,'organization.updated','organization',a.organizationId!,a.organizationId!,a.id,{before,after:input},c);return {ok:true};});}
 @Post('branches') async branch(@Body()body:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'settings.manage');const input=parse(branchInput,body);return transaction(async c=>{const [b]=await query('INSERT INTO branches(organization_id,name,address,phone,active) VALUES($1,$2,$3,$4,$5) RETURNING id',[a.organizationId,input.name,input.address,input.phone,input.active],c);await audit(req,'branch.created','branch',b.id,a.organizationId!,a.id,{after:input},c);return b;});}
 @Patch('branches/:id') async updateBranch(@Param('id')id:string,@Body()body:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'settings.manage');parse(uuid,id);const input=parse(branchInput,body);return transaction(async c=>{const [before]=await query('SELECT name,address,phone,active FROM branches WHERE id=$1 AND organization_id=$2 FOR UPDATE',[id,a.organizationId],c);if(!before)throw new NotFoundException('No encontramos esa sucursal.');await query('UPDATE branches SET name=$3,address=$4,phone=$5,active=$6,updated_at=now() WHERE id=$1 AND organization_id=$2',[id,a.organizationId,input.name,input.address,input.phone,input.active],c);await audit(req,'branch.updated','branch',id,a.organizationId!,a.id,{before,after:input},c);return {ok:true};});}
 @Get('members') async members(@Req()req:AuthRequest){const a=await this.access.tenant(req,'users.view');return query('SELECT u.id,u.name,u.email,m.active,r.id AS role_id,r.name AS role FROM memberships m JOIN users u ON u.id=m.user_id JOIN roles r ON r.id=m.role_id WHERE m.organization_id=$1 ORDER BY u.name LIMIT 200',[a.organizationId]);}
 @Patch('members/:id') async member(@Param('id')id:string,@Body()body:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'users.manage');parse(uuid,id);const input=parse(z.object({role_id:uuid,active:z.boolean()}).strict(),body);return transaction(async c=>{
  await query('SELECT id FROM organizations WHERE id=$1 FOR UPDATE',[a.organizationId],c);await roleAllowed(input.role_id,a.organizationId!,a.permissions,c);
  const [before]=await query('SELECT m.role_id,m.active,r.name FROM memberships m JOIN roles r ON r.id=m.role_id WHERE m.organization_id=$1 AND m.user_id=$2',[a.organizationId,id],c);if(!before)throw new NotFoundException('No encontramos a ese miembro.');
  if(id===a.id)throw new BadRequestException('Otro propietario debe modificar tu acceso para evitar que pierdas la administración.');
  await roleAllowed(before.role_id,a.organizationId!,a.permissions,c);
  if(before.name==='Propietario'&&before.active){const [owners]=await query("SELECT count(*)::int AS count FROM memberships m JOIN roles r ON r.id=m.role_id WHERE m.organization_id=$1 AND m.active AND r.name='Propietario' AND r.system",[a.organizationId],c);if(owners.count<=1)throw new BadRequestException('Debe permanecer al menos un propietario activo.');}
  await query('UPDATE memberships SET role_id=$3,active=$4 WHERE organization_id=$1 AND user_id=$2',[a.organizationId,id,input.role_id,input.active],c);await audit(req,'membership.updated','user',id,a.organizationId!,a.id,{before,after:input},c);return {ok:true};
 });}
 @Get('roles') async roles(@Req()req:AuthRequest){const a=await this.access.tenant(req,'users.view');return query("SELECT r.id,r.name,r.system,coalesce(array_agg(p.permission_code) FILTER(WHERE p.permission_code IS NOT NULL),'{}') AS permissions FROM roles r LEFT JOIN role_permissions p ON p.role_id=r.id AND p.organization_id=r.organization_id WHERE r.organization_id=$1 GROUP BY r.id ORDER BY r.system DESC,r.name",[a.organizationId]);}
 @Get('permissions') async permissions(@Req()req:AuthRequest){await this.access.tenant(req,'users.view');return query('SELECT code,description FROM permissions ORDER BY code');}
 @Post('roles') async role(@Body()body:unknown,@Req()req:AuthRequest){return this.saveRole(null,body,req);}
 @Patch('roles/:id') async updateRole(@Param('id')id:string,@Body()body:unknown,@Req()req:AuthRequest){parse(uuid,id);return this.saveRole(id,body,req);}
 private async saveRole(id:string|null,body:unknown,req:AuthRequest){const a=await this.access.tenant(req,'roles.manage');const input=parse(z.object({name,permissions:z.array(z.string()).max(100)}).strict(),body);if(input.permissions.some(p=>!a.permissions.includes(p)))throw new ForbiddenException('No puedes conceder permisos que no tienes.');return transaction(async c=>{let target=id;let before:unknown=null;if(id){const [r]=await query('SELECT name,system FROM roles WHERE id=$1 AND organization_id=$2 FOR UPDATE',[id,a.organizationId],c);if(!r)throw new NotFoundException('No encontramos ese rol.');if(r.system)throw new BadRequestException('Los roles base se conservan. Crea un rol personalizado.');before={name:r.name,permissions:await query('SELECT permission_code FROM role_permissions WHERE role_id=$1',[id],c)};await query('UPDATE roles SET name=$3 WHERE id=$1 AND organization_id=$2',[id,a.organizationId,input.name],c);await query('DELETE FROM role_permissions WHERE role_id=$1 AND organization_id=$2',[id,a.organizationId],c);}else{const [r]=await query('INSERT INTO roles(organization_id,name) VALUES($1,$2) RETURNING id',[a.organizationId,input.name],c);target=r.id;}for(const code of new Set(input.permissions))await query('INSERT INTO role_permissions VALUES($1,$2,$3)',[a.organizationId,target,code],c);await audit(req,id?'role.updated':'role.created','role',target,a.organizationId!,a.id,{before,after:input},c);return {id:target};});}
 @Get('invitations') async invitations(@Req()req:AuthRequest){const a=await this.access.tenant(req,'users.manage');return query("SELECT i.id,i.email,r.name AS role,i.expires_at,i.accepted_at,m.status AS delivery_status FROM invitations i JOIN roles r ON r.id=i.role_id LEFT JOIN mail_outbox m ON m.entity_id=i.id AND m.kind='invite' WHERE i.organization_id=$1 ORDER BY i.created_at DESC LIMIT 100",[a.organizationId]);}
 @Post('invitations') async invite(@Body()body:unknown,@Req()req:AuthRequest){
  const a=await this.access.tenant(req,'users.manage');const input=parse(z.object({email,role_id:uuid}).strict(),body);
  await this.access.rate(`invite-send:${a.id}`,20,3600);
  await transaction(async c=>{
   await roleAllowed(input.role_id,a.organizationId!,a.permissions,c);const raw=token();
   const [inv]=await query("INSERT INTO invitations(organization_id,email,role_id,token_hash,expires_at) VALUES($1,$2,$3,$4,now()+interval '48 hours') RETURNING id,expires_at",[a.organizationId,input.email,input.role_id,digest(raw)],c);
   await enqueueMail(c,{organizationId:a.organizationId,userId:a.id,kind:'invite',entityId:inv.id,email:input.email,token:raw,expiresAt:inv.expires_at});
   await audit(req,'invitation.queued','invitation',inv.id,a.organizationId!,a.id,{after:{email:input.email,role_id:input.role_id}},c);
  });return {ok:true};
 }
 @Delete('invitations/:id') async revokeInvitation(@Param('id')id:string,@Req()req:AuthRequest){const a=await this.access.tenant(req,'users.manage');parse(uuid,id);await transaction(async c=>{await query('UPDATE invitations SET expires_at=now() WHERE id=$1 AND organization_id=$2 AND accepted_at IS NULL',[id,a.organizationId],c);await audit(req,'invitation.revoked','invitation',id,a.organizationId!,a.id,{},c);});return {ok:true};}
 @Get('audit') async logs(@Query('cursor')cursor:string|undefined,@Req()req:AuthRequest){const a=await this.access.tenant(req,'audit.view');let time:string|null=null,id:string|null=null;if(cursor){const parts=cursor.split('|');parse(z.tuple([z.iso.datetime({offset:true}),uuid]),parts);[time,id]=parts;}const rows=await query("SELECT l.id,l.action,l.entity,l.entity_id,l.created_at,l.reason,u.name AS actor FROM audit_logs l LEFT JOIN users u ON u.id=l.user_id WHERE l.organization_id=$1 AND ($2::timestamptz IS NULL OR (l.created_at,l.id)<($2::timestamptz,$3::uuid)) ORDER BY l.created_at DESC,l.id DESC LIMIT 31",[a.organizationId,time,id]);const more=rows.length>30;const items=rows.slice(0,30);const last=items.at(-1);await audit(req,'audit.viewed','audit',null,a.organizationId!,a.id);return {items,nextCursor:more&&last?`${new Date(last.created_at).toISOString()}|${last.id}`:null};}
}
