import {BadRequestException,Controller,Get,Inject,NotFoundException,Query,Req} from '@nestjs/common';
import {Temporal} from '@js-temporal/polyfill';
import {z} from 'zod';
import {Access,type AuthRequest,audit,parse,uuid} from './core';
import {patientTransaction} from './patients';
import {query,transaction} from '../../../packages/database/src/client';
@Controller('api/professional-report')
export class ProfessionalReportController{
 constructor(@Inject(Access)private access:Access){}
 private async actor(req:AuthRequest){const a=await this.access.tenant(req,'patients.view');await this.access.tenant(req,'professional_shares.view');return a;}
 @Get('options') async options(@Query()raw:unknown,@Req()req:AuthRequest){const a=await this.actor(req),{q}=parse(z.object({q:z.string().trim().max(100).default('')}).strict(),raw);return patientTransaction(a.organizationId!,async c=>{const items=await query('SELECT id,name,active,relationship FROM professionals WHERE organization_id=$1 AND strpos(lower(name),lower($2))>0 ORDER BY name,id LIMIT 21',[a.organizationId,q],c),[o]=await query('SELECT timezone FROM organizations WHERE id=$1',[a.organizationId],c);return {items:items.slice(0,20),hasMore:items.length>20,timezone:o.timezone,today:Temporal.Now.plainDateISO(o.timezone).toString()};});}
 @Get() async report(@Query()raw:unknown,@Req()req:AuthRequest){const a=await this.actor(req),f=parse(z.object({professional_id:uuid,from:z.iso.date(),to:z.iso.date()}).strict(),raw);return transaction(async c=>{
 await c.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');await c.query("SELECT set_config('app.organization_id',$1,true)",[a.organizationId]);
 const [o]=await query('SELECT name,timezone FROM organizations WHERE id=$1',[a.organizationId],c),[professional]=await query('SELECT id,name,active,relationship FROM professionals WHERE organization_id=$1 AND id=$2',[a.organizationId,f.professional_id],c);if(!professional)throw new NotFoundException('No encontramos al profesional en esta clínica.');
 const start=Temporal.PlainDate.from(f.from),end=Temporal.PlainDate.from(f.to);if(Temporal.PlainDate.compare(start,end)>0||start.until(end).days>30)throw new BadRequestException('Selecciona un periodo de 1 a 31 días.');if(Temporal.PlainDate.compare(end,Temporal.Now.plainDateISO(o.timezone))>0)throw new BadRequestException('El periodo no puede terminar en el futuro.');
 const from=start.toZonedDateTime(o.timezone).toInstant().toString(),to=end.add({days:1}).toZonedDateTime(o.timezone).toInstant().toString();
 const events=await query("SELECT p.id AS payment_id,p.patient_id,p.share_id,s.version AS share_version,s.professional_name,s.currency,p.method,p.branch_name,p.reference,p.amount_minor::float8 AS amount_minor,p.created_at AS occurred_at,'payment' AS type,coalesce(p.receipt_context->>'recorded_by',u.name) AS author FROM professional_payments p JOIN professional_shares s ON s.organization_id=p.organization_id AND s.id=p.share_id JOIN users u ON u.id=p.created_by WHERE p.organization_id=$1 AND s.professional_id=$2 AND p.created_at >= $3 AND p.created_at < $4 UNION ALL SELECT p.id,p.patient_id,p.share_id,s.version,s.professional_name,s.currency,p.method,p.branch_name,v.reason,-p.amount_minor::float8,v.created_at,'void',u.name FROM professional_payment_voids v JOIN professional_payments p ON p.organization_id=v.organization_id AND p.id=v.payment_id JOIN professional_shares s ON s.organization_id=p.organization_id AND s.id=p.share_id JOIN users u ON u.id=v.created_by WHERE p.organization_id=$1 AND s.professional_id=$2 AND v.created_at >= $3 AND v.created_at < $4 ORDER BY occurred_at,payment_id,type LIMIT 2001",[a.organizationId,f.professional_id,from,to],c);
 if(events.length>2000)throw new BadRequestException('Hay más de 2000 movimientos. Reduce el periodo.');
 const totals:Record<string,{currency:string;paid_minor:number;voided_minor:number;net_minor:number}>={};for(const e of events){const t=totals[e.currency]||={currency:e.currency,paid_minor:0,voided_minor:0,net_minor:0};if(e.type==='payment')t.paid_minor+=e.amount_minor;else t.voided_minor-=e.amount_minor;t.net_minor+=e.amount_minor;}
 // Choose latest shares BEFORE filtering by professional, so reassigned doctors have no stale balance.
 const balances=await query("WITH agreements AS (SELECT DISTINCT ON(patient_id) patient_id,id FROM budget_acceptances WHERE organization_id=$1 ORDER BY patient_id,version DESC),current_shares AS (SELECT DISTINCT ON(s.patient_id) s.* FROM professional_shares s JOIN agreements b ON b.id=s.acceptance_id AND b.patient_id=s.patient_id WHERE s.organization_id=$1 ORDER BY s.patient_id,s.version DESC),paid AS (SELECT p.share_id,sum(p.amount_minor) AS amount FROM professional_payments p WHERE p.organization_id=$1 AND NOT EXISTS(SELECT 1 FROM professional_payment_voids v WHERE v.organization_id=p.organization_id AND v.payment_id=p.id) GROUP BY p.share_id) SELECT s.currency,count(*)::int AS assignments,sum(s.amount_minor)::float8 AS assigned_minor,sum(coalesce(p.amount,0))::float8 AS paid_minor,sum(s.amount_minor-coalesce(p.amount,0))::float8 AS balance_minor FROM current_shares s LEFT JOIN paid p ON p.share_id=s.id WHERE s.professional_id=$2 GROUP BY s.currency ORDER BY s.currency",[a.organizationId,f.professional_id],c);
 await audit(req,'professional_report.viewed','professional',f.professional_id,a.organizationId!,a.id,{after:{from:f.from,to:f.to}},c);
 return {filters:f,organization:o.name,timezone:o.timezone,professional,consulted_at:new Date().toISOString(),totals:Object.values(totals).sort((a,b)=>a.currency.localeCompare(b.currency)),balances,events};
 });}
}
