import {hasProfessionalPayments} from './professional-payments';
import {BadRequestException,Body,ConflictException,Controller,Get,Inject,NotFoundException,Param,Post,Query,Req} from '@nestjs/common';
import {z} from 'zod';
import {Access,type AuthRequest,audit,digest,parse,uuid} from './core';
import {patientTransaction} from './patients';
import {query} from '../../../packages/database/src/client';
export function shareAmount(total:number,bps:number){if(!Number.isSafeInteger(total)||total<0||!Number.isInteger(bps)||bps<0||bps>10000)throw new BadRequestException('Importe o porcentaje inválido.');return Number((BigInt(total)*BigInt(bps)+5000n)/10000n);}
@Controller('api/patients/:patientId/professional-shares')
export class ProfessionalSharesController{
 constructor(@Inject(Access)private access:Access){}
 private async actor(req:AuthRequest,id:string,manage=false){const a=await this.access.tenant(req,'patients.view');await this.access.tenant(req,'professional_shares.view');if(manage)await this.access.tenant(req,'professional_shares.manage');parse(uuid,id);return a;}
 @Get('professionals') async professionals(@Param('patientId')id:string,@Query()raw:unknown,@Req()req:AuthRequest){const a=await this.actor(req,id,true),input=parse(z.object({q:z.string().trim().max(100).default('')}).strict(),raw);return patientTransaction(a.organizationId!,async c=>{if(!(await query('SELECT id FROM patients WHERE organization_id=$1 AND id=$2',[a.organizationId,id],c)).length)throw new NotFoundException('No encontramos al paciente.');const rows=await query('SELECT id,name,relationship FROM professionals WHERE organization_id=$1 AND active AND strpos(lower(name),lower($2))>0 ORDER BY name,id LIMIT 21',[a.organizationId,input.q],c);return {items:rows.slice(0,20),hasMore:rows.length>20};});}
 @Get() async read(@Param('patientId')id:string,@Req()req:AuthRequest){const a=await this.actor(req,id);return patientTransaction(a.organizationId!,async c=>{
 if(!(await query('SELECT id FROM patients WHERE organization_id=$1 AND id=$2',[a.organizationId,id],c)).length)throw new NotFoundException('No encontramos al paciente.');
 const [agreement]=await query("SELECT id,version,snapshot->'budget'->>'title' AS title,snapshot->'budget'->>'currency' AS currency,(snapshot->'budget'->>'total_minor')::float8 AS total_minor FROM budget_acceptances WHERE organization_id=$1 AND patient_id=$2 ORDER BY version DESC LIMIT 1",[a.organizationId,id],c);
 const items=await query('SELECT s.id,s.version,s.acceptance_id,s.professional_id,s.professional_name,s.relationship,s.percentage_bps,s.base_minor::float8 AS base_minor,s.amount_minor::float8 AS amount_minor,s.currency,s.notes,s.created_at,u.name AS author,b.version AS budget_version FROM professional_shares s JOIN users u ON u.id=s.created_by JOIN budget_acceptances b ON b.organization_id=s.organization_id AND b.id=s.acceptance_id WHERE s.organization_id=$1 AND s.patient_id=$2 ORDER BY s.version DESC LIMIT 25',[a.organizationId,id],c);
 await audit(req,'professional_share.viewed','patient',id,a.organizationId!,a.id,{},c);return {payment_locked:await hasProfessionalPayments(a.organizationId!,id,c),agreement:agreement||null,version:items[0]?.version||0,current:items.find(s=>s.acceptance_id===agreement?.id)||null,items};
 });}
 @Post() async save(@Param('patientId')id:string,@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.actor(req,id,true),input=parse(z.object({request_id:uuid,version:z.number().int().nonnegative(),acceptance_id:uuid,professional_id:uuid,percentage_bps:z.number().int().min(0).max(10000),notes:z.string().trim().max(2000),reviewed:z.literal(true)}).strict(),raw),hash=digest(JSON.stringify({...input,patientId:id}));return patientTransaction(a.organizationId!,async c=>{
 await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':professional-share:'+input.request_id],c);
 await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':budget:'+id],c);
 const [retry]=await query('SELECT id,version,request_hash FROM professional_shares WHERE organization_id=$1 AND request_id=$2',[a.organizationId,input.request_id],c);if(retry){if(retry.request_hash!==hash)throw new ConflictException('La solicitud ya se usó con otros datos.');return {id:retry.id,version:retry.version};}
 const [patient]=await query('SELECT active FROM patients WHERE organization_id=$1 AND id=$2 FOR SHARE',[a.organizationId,id],c);if(!patient)throw new NotFoundException('No encontramos al paciente.');if(!patient.active)throw new BadRequestException('La ficha está inactiva.');
 const [agreement]=await query("SELECT id,(snapshot->'budget'->>'total_minor')::float8 AS total_minor,snapshot->'budget'->>'currency' AS currency FROM budget_acceptances WHERE organization_id=$1 AND patient_id=$2 ORDER BY version DESC LIMIT 1",[a.organizationId,id],c);if(!agreement||agreement.id!==input.acceptance_id)throw new ConflictException('El acuerdo cambió o aún no está aceptado. Actualiza antes de continuar.');
 const [last]=await query('SELECT max(version) AS version FROM professional_shares WHERE organization_id=$1 AND patient_id=$2',[a.organizationId,id],c);if((last.version||0)!==input.version)throw new ConflictException('La participación cambió. Actualiza antes de continuar.');if((input.version>0||input.percentage_bps===0)&&!input.notes)throw new BadRequestException('Explica el motivo de la corrección o de la participación cero.');
 if(await hasProfessionalPayments(a.organizationId!,id,c))throw new ConflictException('La participación tiene pagos vigentes. No se puede sustituir sin un ajuste financiero. No anules pagos reales para cambiarla.');
 const [professional]=await query('SELECT name,relationship FROM professionals WHERE organization_id=$1 AND id=$2 AND active FOR SHARE',[a.organizationId,input.professional_id],c);if(!professional)throw new BadRequestException('Selecciona un profesional activo de esta clínica.');
 const amount=shareAmount(agreement.total_minor,input.percentage_bps),version=input.version+1;
 const [row]=await query('INSERT INTO professional_shares(organization_id,patient_id,version,acceptance_id,professional_id,professional_name,relationship,percentage_bps,base_minor,amount_minor,currency,notes,request_id,request_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING id,version',[a.organizationId,id,version,agreement.id,input.professional_id,professional.name,professional.relationship,input.percentage_bps,agreement.total_minor,amount,agreement.currency,input.notes,input.request_id,hash,a.id],c);
 await audit(req,'professional_share.recorded','patient',id,a.organizationId!,a.id,{after:{id:row.id,version}},c);return row;
 });}
}
