import {BadRequestException,Body,ConflictException,Controller,Get,Inject,NotFoundException,Param,Post,Query,Req} from '@nestjs/common';
import type {PoolClient} from 'pg';
import {z} from 'zod';
import {Access,type AuthRequest,audit,digest,parse,uuid} from './core';
import {patientTransaction} from './patients';
import {query} from '../../../packages/database/src/client';
export async function hasProfessionalPayments(org:string,patient:string,c:PoolClient){return (await query('SELECT p.id FROM professional_payments p WHERE p.organization_id=$1 AND p.patient_id=$2 AND NOT EXISTS(SELECT 1 FROM professional_payment_voids v WHERE v.organization_id=p.organization_id AND v.payment_id=p.id) LIMIT 1',[org,patient],c)).length>0;}
async function currentShare(org:string,patient:string,c:PoolClient){return (await query("SELECT s.id,s.version,s.professional_name,s.professional_id,s.amount_minor::float8 AS amount_minor,s.currency FROM professional_shares s WHERE s.organization_id=$1 AND s.patient_id=$2 AND s.acceptance_id=(SELECT id FROM budget_acceptances WHERE organization_id=$1 AND patient_id=$2 ORDER BY version DESC LIMIT 1) ORDER BY s.version DESC LIMIT 1",[org,patient],c))[0];}
async function paidAmount(org:string,share:string,c:PoolClient){return (await query('SELECT coalesce(sum(p.amount_minor),0)::float8 AS total FROM professional_payments p WHERE p.organization_id=$1 AND p.share_id=$2 AND NOT EXISTS(SELECT 1 FROM professional_payment_voids v WHERE v.organization_id=p.organization_id AND v.payment_id=p.id)',[org,share],c))[0].total as number;}
@Controller('api/patients/:patientId/professional-payments')
export class ProfessionalPaymentsController{
 constructor(@Inject(Access)private access:Access){}
 private async actor(req:AuthRequest,id:string,permission?:string){const a=await this.access.tenant(req,'patients.view');await this.access.tenant(req,'professional_shares.view');if(permission)await this.access.tenant(req,permission);parse(uuid,id);return a;}
 @Get() async read(@Param('patientId')id:string,@Query()raw:unknown,@Req()req:AuthRequest){const a=await this.actor(req,id),{page}=parse(z.object({page:z.coerce.number().int().min(1).max(100000).default(1)}).strict(),raw);return patientTransaction(a.organizationId!,async c=>{
 if(!(await query('SELECT id FROM patients WHERE organization_id=$1 AND id=$2',[a.organizationId,id],c)).length)throw new NotFoundException('No encontramos al paciente.');
 const share=await currentShare(a.organizationId!,id,c),paid=share?await paidAmount(a.organizationId!,share.id,c):0;
 const items=await query('SELECT p.id,p.share_id,p.amount_minor::float8 AS amount_minor,p.kind,p.method,p.branch_name,p.reference,p.notes,p.created_at,u.name AS author,s.professional_name,s.version AS share_version,s.currency,v.reason AS void_reason,v.created_at AS voided_at,vu.name AS voided_by FROM professional_payments p JOIN professional_shares s ON s.organization_id=p.organization_id AND s.id=p.share_id JOIN users u ON u.id=p.created_by LEFT JOIN professional_payment_voids v ON v.organization_id=p.organization_id AND v.payment_id=p.id LEFT JOIN users vu ON vu.id=v.created_by WHERE p.organization_id=$1 AND p.patient_id=$2 ORDER BY p.created_at DESC,p.id DESC LIMIT 21 OFFSET $3',[a.organizationId,id,(page-1)*20],c);
 const branches=await query('SELECT id,name FROM branches WHERE organization_id=$1 AND active ORDER BY name,id',[a.organizationId],c);
 await audit(req,'professional_payments.viewed','patient',id,a.organizationId!,a.id,{},c);return {share:share?{...share,paid_minor:paid,balance_minor:share.amount_minor-paid}:null,items:items.slice(0,20),hasMore:items.length>20,branches};
 });}
 @Get(':paymentId/receipt') async receipt(@Param('patientId')id:string,@Param('paymentId')paymentId:string,@Req()req:AuthRequest){const a=await this.actor(req,id);parse(uuid,paymentId);return patientTransaction(a.organizationId!,async c=>{
 const [p]=await query("SELECT p.id,p.amount_minor::float8 AS amount_minor,p.kind,p.method,p.branch_name,p.reference,p.created_at,p.receipt_context,u.name AS author,s.id AS share_id,s.version AS share_version,s.professional_name,s.relationship,s.currency,s.amount_minor::float8 AS assigned_minor,s.percentage_bps,b.version AS budget_version,b.snapshot->'organization' AS organization,v.created_at AS voided_at,v.reason AS void_reason,vu.name AS voided_by FROM professional_payments p JOIN professional_shares s ON s.organization_id=p.organization_id AND s.id=p.share_id JOIN budget_acceptances b ON b.organization_id=s.organization_id AND b.id=s.acceptance_id JOIN users u ON u.id=p.created_by LEFT JOIN professional_payment_voids v ON v.organization_id=p.organization_id AND v.payment_id=p.id LEFT JOIN users vu ON vu.id=v.created_by WHERE p.organization_id=$1 AND p.patient_id=$2 AND p.id=$3",[a.organizationId,id,paymentId],c);
 if(!p)throw new NotFoundException('No encontramos el recibo de este pago al doctor.');
 const context=p.receipt_context||{organization:p.organization,recorded_by:p.author,balance_after_minor:null};
 await audit(req,'professional_payment.receipt_viewed','patient',id,a.organizationId!,a.id,{after:{payment_id:paymentId}},c);
 return {id:p.id,amount_minor:p.amount_minor,kind:p.kind,method:p.method,branch_name:p.branch_name,reference:p.reference,created_at:p.created_at,share_id:p.share_id,share_version:p.share_version,professional_name:p.professional_name,relationship:p.relationship,currency:p.currency,assigned_minor:p.assigned_minor,percentage_bps:p.percentage_bps,budget_version:p.budget_version,context,legacy:!p.receipt_context,voided_at:p.voided_at,void_reason:p.void_reason,voided_by:p.voided_by,consulted_at:new Date().toISOString()};
 });}
 @Post() async create(@Param('patientId')id:string,@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.actor(req,id,'professional_payments.create'),input=parse(z.object({request_id:uuid,share_id:uuid,amount_minor:z.number().int().positive().max(1000000000000),kind:z.enum(['installment','settlement']),method:z.enum(['cash','transfer','other']),branch_id:uuid,reference:z.string().trim().max(160),notes:z.string().trim().max(2000),reviewed:z.literal(true)}).strict(),raw),hash=digest(JSON.stringify({...input,patientId:id}));return patientTransaction(a.organizationId!,async c=>{
 await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':professional-payment:'+input.request_id],c);
 await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':budget:'+id],c);
 const [retry]=await query('SELECT id,request_hash FROM professional_payments WHERE organization_id=$1 AND request_id=$2',[a.organizationId,input.request_id],c);if(retry){if(retry.request_hash!==hash)throw new ConflictException('La solicitud ya se usó con otros datos.');return {id:retry.id};}
 const share=await currentShare(a.organizationId!,id,c);if(!share||share.id!==input.share_id)throw new ConflictException('La participación cambió o no está asignada. Actualiza antes de registrar el pago.');
 const [branch]=await query('SELECT name FROM branches WHERE organization_id=$1 AND id=$2 AND active FOR SHARE',[a.organizationId,input.branch_id],c);if(!branch)throw new BadRequestException('Selecciona una sucursal activa de esta clínica.');
 const balance=share.amount_minor-await paidAmount(a.organizationId!,share.id,c);if(input.amount_minor>balance)throw new ConflictException('El importe supera el saldo pendiente del doctor. Actualiza los pagos.');if(input.kind==='settlement'&&input.amount_minor!==balance)throw new BadRequestException('La liquidación debe cubrir exactamente el saldo pendiente.');
 const [organization]=await query('SELECT name,address,phone,timezone FROM organizations WHERE id=$1',[a.organizationId],c);
 const [row]=await query('INSERT INTO professional_payments(organization_id,patient_id,share_id,request_id,request_hash,amount_minor,kind,method,branch_id,branch_name,reference,notes,created_by,receipt_context) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id',[a.organizationId,id,share.id,input.request_id,hash,input.amount_minor,input.kind,input.method,input.branch_id,branch.name,input.reference,input.notes,a.id,JSON.stringify({organization,recorded_by:a.name,balance_after_minor:balance-input.amount_minor})],c);
 await audit(req,'professional_payment.recorded','patient',id,a.organizationId!,a.id,{after:{payment_id:row.id,share_id:share.id}},c);return row;
 });}
 @Post(':paymentId/void') async void(@Param('patientId')id:string,@Param('paymentId')paymentId:string,@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.actor(req,id,'professional_payments.void');parse(uuid,paymentId);const input=parse(z.object({request_id:uuid,reason:z.string().trim().min(1).max(2000),reviewed:z.literal(true)}).strict(),raw),hash=digest(JSON.stringify({...input,patientId:id,paymentId}));return patientTransaction(a.organizationId!,async c=>{
 await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':professional-payment-void:'+input.request_id],c);await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':budget:'+id],c);
 if(!(await query('SELECT id FROM professional_payments WHERE organization_id=$1 AND patient_id=$2 AND id=$3',[a.organizationId,id,paymentId],c)).length)throw new NotFoundException('No encontramos el pago al profesional.');
 const [retry]=await query('SELECT id,request_hash FROM professional_payment_voids WHERE organization_id=$1 AND request_id=$2',[a.organizationId,input.request_id],c);if(retry){if(retry.request_hash!==hash)throw new ConflictException('La solicitud ya se usó con otros datos.');return {id:retry.id};}
 if((await query('SELECT id FROM professional_payment_voids WHERE organization_id=$1 AND payment_id=$2',[a.organizationId,paymentId],c)).length)throw new ConflictException('La captura ya está anulada. Actualiza el historial.');
 const [row]=await query('INSERT INTO professional_payment_voids(organization_id,payment_id,request_id,request_hash,reason,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[a.organizationId,paymentId,input.request_id,hash,input.reason,a.id],c);await audit(req,'professional_payment.voided','patient',id,a.organizationId!,a.id,{after:{payment_id:paymentId,void_id:row.id}},c);return row;
 });}
}
