import {Body,ConflictException,Controller,Get,Inject,NotFoundException,Param,Post,Query,Req} from '@nestjs/common';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {Access,type AuthRequest,audit,digest,parse,uuid} from './core';
import {patientTransaction} from './patients';
import {query} from '../../../packages/database/src/client';
@Controller('api/patients/:patientId/referrals')
export class ReferralsController{
 constructor(@Inject(Access)private access:Access){}
 private async actor(req:AuthRequest,id:string,edit=false){const a=await this.access.tenant(req,'patients.view');await this.access.tenant(req,'clinical_records.view');if(edit)await this.access.tenant(req,'clinical_records.edit');parse(uuid,id);return a;}
 @Get('professionals') async professionals(@Param('patientId')id:string,@Query()raw:unknown,@Req()req:AuthRequest){const a=await this.actor(req,id);const input=parse(z.object({q:z.string().trim().max(100).default('')}).strict(),raw);return patientTransaction(a.organizationId!,async c=>{
  if(!(await query('SELECT id FROM patients WHERE organization_id=$1 AND id=$2',[a.organizationId,id],c)).length)throw new NotFoundException('No encontramos al paciente.');
  const rows=await query("SELECT id,name,external_organization FROM professionals WHERE organization_id=$1 AND active AND relationship='external' AND name ILIKE $2 ORDER BY name,id LIMIT 21",[a.organizationId,'%'+input.q.replace(/[\\%_]/g,'\\$&')+'%'],c);return {items:rows.slice(0,20),hasMore:rows.length>20};});}
 @Get() async list(@Param('patientId')id:string,@Req()req:AuthRequest){const a=await this.actor(req,id);return patientTransaction(a.organizationId!,async c=>{if(!(await query('SELECT id FROM patients WHERE organization_id=$1 AND id=$2',[a.organizationId,id],c)).length)throw new NotFoundException('No encontramos al paciente.');const rows=await query('SELECT * FROM (SELECT DISTINCT ON (r.id) r.*,u.name AS author FROM patient_referral_versions r JOIN users u ON u.id=r.created_by WHERE organization_id=$1 AND patient_id=$2 ORDER BY r.id,version DESC) latest ORDER BY created_at DESC,id LIMIT 51',[a.organizationId,id],c);await audit(req,'referrals.viewed','patient',id,a.organizationId!,a.id,{},c);return {items:rows.slice(0,50),hasMore:rows.length>50};});}
 @Get(':id/history') async history(@Param('patientId')patient:string,@Param('id')id:string,@Req()req:AuthRequest){const a=await this.actor(req,patient);parse(uuid,id);return patientTransaction(a.organizationId!,async c=>{const rows=await query('SELECT r.*,u.name AS author FROM patient_referral_versions r JOIN users u ON u.id=r.created_by WHERE organization_id=$1 AND patient_id=$2 AND r.id=$3 ORDER BY version DESC LIMIT 100',[a.organizationId,patient,id],c);if(!rows.length)throw new NotFoundException('No encontramos la remisión.');await audit(req,'referral.history_viewed','patient',patient,a.organizationId!,a.id,{after:{referral_id:id}},c);return {items:rows};});}
 @Post() async save(@Param('patientId')patient:string,@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.actor(req,patient,true);const input=parse(z.object({request_id:uuid,id:uuid.optional(),version:z.number().int().nonnegative(),professional_id:uuid.optional(),reason:z.string().trim().max(3000).default(''),state:z.enum(['requested','attended','returned','canceled']),notes:z.string().trim().min(1).max(3000),report:z.string().trim().max(10000).default('')}).strict(),raw),hash=digest(JSON.stringify({...input,patient}));return patientTransaction(a.organizationId!,async c=>{
  await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':referrals:'+patient],c);
  const [prior]=await query('SELECT id,version,request_hash FROM patient_referral_versions WHERE organization_id=$1 AND request_id=$2',[a.organizationId,input.request_id],c);if(prior){if(prior.request_hash!==hash)throw new ConflictException('La solicitud ya se usó con otros datos.');return {id:prior.id,version:prior.version};}
  const [p]=await query('SELECT active FROM patients WHERE organization_id=$1 AND id=$2',[a.organizationId,patient],c);if(!p)throw new NotFoundException('No encontramos al paciente.');if(!p.active)throw new ConflictException('Activa la ficha antes de registrar atención.');
  let professional=input.professional_id,name='',reason=input.reason;
  if(input.id){const [old]=await query('SELECT * FROM patient_referral_versions WHERE organization_id=$1 AND patient_id=$2 AND id=$3 ORDER BY version DESC LIMIT 1',[a.organizationId,patient,input.id],c);if(!old)throw new NotFoundException('No encontramos la remisión.');if(old.version!==input.version)throw new ConflictException('La remisión cambió. Actualiza antes de guardar.');const transitions:Record<string,string[]>={requested:['attended','returned','canceled'],attended:['attended','returned','canceled'],returned:['returned'],canceled:[]};if(!transitions[old.state].includes(input.state))throw new ConflictException('Ese cambio de estado no está permitido.');professional=old.professional_id;name=old.professional_name;reason=old.reason;
  }else{if(input.version!==0||input.state!=='requested'||!professional||!reason)throw new ConflictException('Selecciona especialista externo y motivo para una nueva remisión.');const [p]=await query("SELECT name FROM professionals WHERE organization_id=$1 AND id=$2 AND active AND relationship='external'",[a.organizationId,professional],c);if(!p)throw new ConflictException('Selecciona un especialista externo activo.');name=p.name;}
  if(input.state==='returned'&&!input.report)throw new ConflictException('Captura el informe de regreso antes de cerrar la atención.');
  const id=input.id||randomUUID();await query('INSERT INTO patient_referral_versions(organization_id,patient_id,id,version,professional_id,professional_name,reason,state,notes,report,request_id,request_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[a.organizationId,patient,id,input.version+1,professional,name,reason,input.state,input.notes,input.report,input.request_id,hash,a.id],c);await audit(req,'referral.recorded','patient',patient,a.organizationId!,a.id,{after:{referral_id:id,version:input.version+1,state:input.state}},c);return {id,version:input.version+1};
 });}
}
