import {Body,ConflictException,Controller,Get,Inject,NotFoundException,Param,Post,Query,Req} from '@nestjs/common';
import {z} from 'zod';
import {Access,type AuthRequest,audit,digest,parse,uuid} from './core';
import {patientTransaction} from './patients';
import {query} from '../../../packages/database/src/client';
@Controller('api/patients/:patientId/refunds')
export class RefundsController{
 constructor(@Inject(Access)private access:Access){}
 @Get() async list(@Param('patientId')patient:string,@Query()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'patients.view');await this.access.tenant(req,'payments.view');parse(uuid,patient);const input=parse(z.object({page:z.coerce.number().int().min(1).max(100000).default(1)}).strict(),raw);return patientTransaction(a.organizationId!,async c=>{if(!(await query('SELECT id FROM patients WHERE organization_id=$1 AND id=$2',[a.organizationId,patient],c)).length)throw new NotFoundException('No encontramos al paciente.');const items=await query('SELECT r.id,r.payment_id,r.amount_minor::float8 AS amount_minor,r.method,r.currency,r.reason,r.reference,r.created_at,u.name AS author,b.name AS branch FROM patient_refunds r JOIN users u ON u.id=r.created_by JOIN branches b ON b.organization_id=r.organization_id AND b.id=r.branch_id WHERE r.organization_id=$1 AND patient_id=$2 ORDER BY created_at DESC,r.id LIMIT 21 OFFSET $3',[a.organizationId,patient,(input.page-1)*20],c);return {items:items.slice(0,20),hasMore:items.length>20};});}
 @Post() async create(@Param('patientId')patient:string,@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.access.tenant(req,'patients.view');await this.access.tenant(req,'payments.view');await this.access.tenant(req,'payments.refund');parse(uuid,patient);const input=parse(z.object({request_id:uuid,payment_id:uuid,amount_minor:z.number().int().positive().max(1000000000000),branch_id:uuid,method:z.enum(['cash','card','transfer','other']),reason:z.string().trim().min(1).max(2000),reference:z.string().trim().max(160),reviewed:z.literal(true)}).strict(),raw),hash=digest(JSON.stringify({...input,patient}));return patientTransaction(a.organizationId!,async c=>{
  await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':refund:'+input.request_id],c);await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':budget:'+patient],c);
  const [prior]=await query('SELECT id,request_hash FROM patient_refunds WHERE organization_id=$1 AND request_id=$2',[a.organizationId,input.request_id],c);if(prior){if(prior.request_hash!==hash)throw new ConflictException('La solicitud ya se usó con otros datos.');return {id:prior.id};}
  const [p]=await query("SELECT p.amount_minor::float8 AS amount,b.snapshot->'budget'->>'currency' AS currency FROM patient_payments p JOIN budget_acceptances b ON b.organization_id=p.organization_id AND b.id=p.acceptance_id WHERE p.organization_id=$1 AND p.patient_id=$2 AND p.id=$3 AND NOT EXISTS(SELECT 1 FROM payment_voids v WHERE v.organization_id=p.organization_id AND v.payment_id=p.id)",[a.organizationId,patient,input.payment_id],c);if(!p)throw new NotFoundException('No encontramos un pago vigente del paciente.');
  const [returned]=await query('SELECT coalesce(sum(amount_minor),0)::float8 AS amount FROM patient_refunds WHERE organization_id=$1 AND payment_id=$2',[a.organizationId,input.payment_id],c);if(input.amount_minor>p.amount-returned.amount)throw new ConflictException('La devolución supera lo disponible de ese pago. Actualiza.');if(!(await query('SELECT id FROM branches WHERE organization_id=$1 AND id=$2 AND active FOR SHARE',[a.organizationId,input.branch_id],c)).length)throw new ConflictException('Selecciona una sucursal activa.');
  const [row]=await query('INSERT INTO patient_refunds(organization_id,patient_id,payment_id,amount_minor,branch_id,method,currency,reason,reference,request_id,request_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id',[a.organizationId,patient,input.payment_id,input.amount_minor,input.branch_id,input.method,p.currency,input.reason,input.reference,input.request_id,hash,a.id],c);await audit(req,'payment.refunded','patient',patient,a.organizationId!,a.id,{after:{refund_id:row.id,payment_id:input.payment_id}},c);return row;
 });}
}
