import {BadRequestException,Body,ConflictException,Controller,Get,Inject,NotFoundException,Param,Post,Req} from '@nestjs/common';
import {z} from 'zod';
import {Access,type AuthRequest,audit,parse,uuid} from './core';
import {patientTransaction} from './patients';
import {query} from '../../../packages/database/src/client';
const normalizeEmail=(v:string)=>v.trim().toLowerCase();
const normalizeWhatsApp=(v:string)=>v.replace(/[\s().-]/g,'');
export function reminderPreview(preference:{email_enabled:boolean;whatsapp_enabled:boolean;email:string;whatsapp:string;offsets_hours:number[]}|null,patient:{email:string;whatsapp:string;active:boolean},appointments:{id:string;version:number;starts_at:Date|string;status:string;timezone:string}[],now:Date){
 const contacts=[{channel:'email',enabled:preference?.email_enabled===true,destination:normalizeEmail(patient.email),saved:preference?.email||'',valid:z.email().safeParse(normalizeEmail(patient.email)).success},{channel:'whatsapp',enabled:preference?.whatsapp_enabled===true,destination:normalizeWhatsApp(patient.whatsapp),saved:preference?.whatsapp||'',valid:/^\+[1-9]\d{7,14}$/.test(normalizeWhatsApp(patient.whatsapp))}].map(c=>({...c,ready:patient.active&&c.enabled&&c.valid&&c.destination===c.saved,reason:!patient.active?'Paciente inactivo':!c.enabled?'Canal no autorizado':!c.valid?'Contacto inválido':c.destination!==c.saved?'Contacto cambió: revisa la autorización':'Listo para futura programación'}));
 const items=appointments.filter(a=>['pending','confirmed'].includes(a.status)&&new Date(a.starts_at)>now).flatMap(a=>(preference?.offsets_hours||[]).flatMap(hours=>contacts.filter(c=>c.enabled).map(c=>{const due=new Date(new Date(a.starts_at).getTime()-hours*3600000);return {appointment_id:a.id,appointment_version:a.version,starts_at:a.starts_at,timezone:a.timezone,status:a.status,hours,channel:c.channel,due_at:due.toISOString(),eligible:c.ready&&due>now,reason:!c.ready?c.reason:due<=now?'Hora de recordatorio pasada; no se enviaría retroactivamente':'Vista previa; envío aún no habilitado'};})));
 return {contacts:contacts.map(({channel,destination,ready,reason})=>({channel,destination,ready,reason})),items};
}
@Controller('api/patients/:patientId/reminder-preferences')
export class ReminderPreferencesController{
 constructor(@Inject(Access)private access:Access){}
 @Get('queue') async queue(@Param('patientId')id:string,@Req()req:AuthRequest){const a=await this.actor(req,id);await this.access.tenant(req,'appointments.view');return patientTransaction(a.organizationId!,async c=>{
  if(!(await query('SELECT id FROM patients WHERE organization_id=$1 AND id=$2',[a.organizationId,id],c)).length)throw new NotFoundException('No encontramos al paciente.');
  const rows=await query("SELECT id,appointment_id,appointment_version,preference_version,channel,starts_at,due_at,timezone,CASE WHEN state='held' AND due_at<=clock_timestamp() THEN 'expired' ELSE state END AS state,created_at FROM appointment_reminders WHERE organization_id=$1 AND patient_id=$2 ORDER BY created_at DESC,id DESC LIMIT 51",[a.organizationId,id],c);
  await audit(req,'reminder.queue_viewed','patient',id,a.organizationId!,a.id,{},c);return {items:rows.slice(0,50),hasMore:rows.length>50,delivery_enabled:false};
 });}
 private async actor(req:AuthRequest,id:string,edit=false){const a=await this.access.tenant(req,'patients.view');if(edit)await this.access.tenant(req,'patients.edit');parse(uuid,id);return a;}
 @Get() async read(@Param('patientId')id:string,@Req()req:AuthRequest){const a=await this.actor(req,id);return patientTransaction(a.organizationId!,async c=>{const [patient]=await query('SELECT email,whatsapp,active FROM patients WHERE organization_id=$1 AND id=$2',[a.organizationId,id],c);if(!patient)throw new NotFoundException('No encontramos al paciente.');const history=await query('SELECT p.version,p.email_enabled,p.whatsapp_enabled,p.email,p.whatsapp,p.offsets_hours,p.notes,p.created_at,u.name AS author FROM patient_reminder_preferences p JOIN users u ON u.id=p.created_by WHERE p.organization_id=$1 AND p.patient_id=$2 ORDER BY version DESC LIMIT 20',[a.organizationId,id],c);await audit(req,'reminder.preferences_viewed','patient',id,a.organizationId!,a.id,{},c);return {patient,preference:history[0]||null,history};});}
 @Get('preview') async preview(@Param('patientId')id:string,@Req()req:AuthRequest){const a=await this.actor(req,id);await this.access.tenant(req,'appointments.view');return patientTransaction(a.organizationId!,async c=>{
 const [patient]=await query('SELECT email,whatsapp,active FROM patients WHERE organization_id=$1 AND id=$2',[a.organizationId,id],c);if(!patient)throw new NotFoundException('No encontramos al paciente.');
 const [preference]=await query('SELECT * FROM patient_reminder_preferences WHERE organization_id=$1 AND patient_id=$2 ORDER BY version DESC LIMIT 1',[a.organizationId,id],c);
 const appointments=await query("SELECT id,version,starts_at,status,timezone FROM appointments WHERE organization_id=$1 AND patient_id=$2 AND starts_at>now() AND status IN ('pending','confirmed') ORDER BY starts_at,id LIMIT 51",[a.organizationId,id],c),now=new Date();
 const result=reminderPreview(preference as Parameters<typeof reminderPreview>[0],patient as Parameters<typeof reminderPreview>[1],appointments.slice(0,50) as Parameters<typeof reminderPreview>[2],now);await audit(req,'reminder.previewed','patient',id,a.organizationId!,a.id,{},c);return {...result,hasMore:appointments.length>50,consulted_at:now.toISOString(),delivery_enabled:false};
 });}
 @Post() async save(@Param('patientId')id:string,@Body()raw:unknown,@Req()req:AuthRequest){const a=await this.actor(req,id,true),input=parse(z.object({version:z.number().int().nonnegative(),email_enabled:z.boolean(),whatsapp_enabled:z.boolean(),email:z.string().max(254),whatsapp:z.string().max(30),offsets_hours:z.tuple([z.literal(24)]),notes:z.string().trim().min(1).max(1000),reviewed:z.literal(true)}).strict(),raw);if(new Set(input.offsets_hours).size!==input.offsets_hours.length)throw new BadRequestException('No repitas horarios de recordatorio.');return patientTransaction(a.organizationId!,async c=>{
 await query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[a.organizationId+':reminder-preferences:'+id],c);
 const [patient]=await query('SELECT email,whatsapp,active FROM patients WHERE organization_id=$1 AND id=$2 FOR SHARE',[a.organizationId,id],c);if(!patient)throw new NotFoundException('No encontramos al paciente.');
 const [last]=await query('SELECT max(version) AS version FROM patient_reminder_preferences WHERE organization_id=$1 AND patient_id=$2',[a.organizationId,id],c);if((last.version||0)!==input.version)throw new ConflictException('Las preferencias cambiaron. Actualiza antes de guardar.');
 const email=normalizeEmail(input.email),whatsapp=normalizeWhatsApp(input.whatsapp);if(input.email_enabled&&(!z.email().safeParse(email).success||email!==normalizeEmail(patient.email)))throw new BadRequestException('Revisa el correo actual de la ficha antes de autorizarlo.');if(input.whatsapp_enabled&&(!/^\+[1-9]\d{7,14}$/.test(whatsapp)||whatsapp!==normalizeWhatsApp(patient.whatsapp)))throw new BadRequestException('Revisa el WhatsApp de la ficha con código de país, por ejemplo +529991234567.');if(!patient.active&&(input.email_enabled||input.whatsapp_enabled))throw new BadRequestException('Solo puedes desactivar canales de un paciente inactivo.');
 const version=input.version+1;await query('INSERT INTO patient_reminder_preferences(organization_id,patient_id,version,email_enabled,whatsapp_enabled,email,whatsapp,offsets_hours,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[a.organizationId,id,version,input.email_enabled,input.whatsapp_enabled,input.email_enabled?email:'',input.whatsapp_enabled?whatsapp:'',[...input.offsets_hours].sort((a,b)=>b-a),input.notes,a.id],c);await audit(req,'reminder.preferences_saved','patient',id,a.organizationId!,a.id,{after:{version}},c);return {version};
 });}
}
