'use client';
import { useCallback, useEffect, useState } from 'react';
import { FileClock } from 'lucide-react';
import { api } from '../lib/api';
import { Empty, ErrorMessage, Heading } from './ui';
interface Entry {id:string;action:string;entity:string;entity_id:string;created_at:string;actor:string|null;reason:string|null}
interface Page {items:Entry[];nextCursor:string|null}
const labels:Record<string,string>={'organization.created':'Organización creada','organization.updated':'Datos de organización actualizados','branch.created':'Sucursal creada','branch.updated':'Sucursal actualizada','membership.joined':'Miembro incorporado','membership.updated':'Acceso de miembro actualizado','role.created':'Rol creado','role.updated':'Permisos de rol actualizados','invitation.sent':'Invitación enviada','invitation.queued':'Invitación en cola de correo','invite.email_sent':'Correo de invitación enviado','invitation.revoked':'Invitación revocada','audit.viewed':'Consulta de auditoría','demo.seed':'Datos de demostración creados'};
export function Audit(){const [rows,setRows]=useState<Entry[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const load=useCallback(async(next?:string)=>{setBusy(true);setError('');try{const page=await api<Page>(`audit${next?`?cursor=${encodeURIComponent(next)}`:''}`);setRows(prior=>next?[...prior,...page.items]:page.items);setCursor(page.nextCursor);}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[]);useEffect(()=>{void load();},[load]);return <><Heading eyebrow="TRAZABILIDAD" title="Actividad de tu organización" description="Un registro de los cambios y accesos administrativos." action={<span className="pill green">Historial protegido</span>}/><ErrorMessage message={error}/>{rows.length?<div className="audit-timeline">{rows.map(row=><article className="audit-entry" key={row.id}><span className="timeline-dot"/><div><strong>{labels[row.action]||row.action}</strong><p>{row.actor||'Sistema'}<span>·</span>{new Date(row.created_at).toLocaleString('es-MX')}</p><small>{row.entity}{row.reason?` · ${row.reason}`:''}</small></div><code>{row.entity_id?.slice(0,8)}</code></article>)}</div>:!busy?<Empty icon={<FileClock/>} title="El historial comienza aquí" description="Los cambios de tu organización aparecerán en este espacio."/>:null}{busy&&<p role="status">Cargando actividad…</p>}{cursor&&<button className="button secondary" disabled={busy} onClick={()=>void load(cursor)}>Cargar actividad anterior</button>}</>;}
