'use client';
import { useEffect,useState } from 'react';
import { api } from '../lib/api';
import { Resource,type Choice } from './resource-picker';
import { ErrorMessage,Field,Form,InlinePanel } from './ui';
type Slot={day:number;start:string;end:string};
type Block={id:string;professional_id:string|null;room_id:string|null;resource_name:string;starts_at:string;ends_at:string;reason:string;version:number};
const days=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
export function Availability({branch,day,zone,manage,edit,onChanged}:{onChanged?:()=>void;branch:string;day:string;zone:string;manage:boolean;edit:boolean}){
 const [scheduleKind,setScheduleKind]=useState<'professionals'|'rooms'>('professionals');
 const [mode,setMode]=useState<'schedule'|'block'|null>(null),[professional,setProfessional]=useState<Choice|null>(null),[blocks,setBlocks]=useState<Block[]>([]),[page,setPage]=useState(1),[more,setMore]=useState(false),[revision,setRevision]=useState(0),[error,setError]=useState(''),[release,setRelease]=useState<Block|null>(null);
 useEffect(()=>{let live=true;api<{items:Block[];hasMore:boolean}>(`availability/blocks?branch_id=${branch}&date=${day}&page=${page}`).then(r=>{if(live){setBlocks(r.items);setMore(r.hasMore);setError('');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[branch,day,page,revision]);
 const format=(s:string)=>new Intl.DateTimeFormat('es-MX',{timeZone:zone,dateStyle:'short',timeStyle:'short'}).format(new Date(s));
 return <section className="availability-section"><div className="form-actions"><button className="button secondary" onClick={()=>setMode(mode==='schedule'?null:'schedule')}>Horarios de atención</button>{edit&&<button className="button secondary" onClick={()=>setMode(mode==='block'?null:'block')}>Bloquear periodo</button>}<button className="text-button" onClick={()=>{setRevision(v=>v+1);setPage(1);}}>Actualizar bloqueos</button></div><ErrorMessage message={error}/>
 {mode==='schedule'&&<InlinePanel title="Horarios de atención" onClose={()=>setMode(null)}><p className="muted">Turnos semanales por recurso y sucursal · {zone}. Divide el día en dos turnos para reservar un descanso.</p><label className="field"><span>Horario de</span><select aria-label="Horario de" value={scheduleKind} onChange={e=>{setScheduleKind(e.target.value as typeof scheduleKind);setProfessional(null);}}><option value="professionals">Profesional</option><option value="rooms">Consultorio</option></select></label><Resource key={scheduleKind} kind={scheduleKind} branch={branch} label={scheduleKind==='rooms'?'Consultorio del horario':'Profesional del horario'} value={professional} onChange={setProfessional}/>{professional&&<Schedule key={professional.id} branch={branch} professional={professional.id} room={scheduleKind==='rooms'} manage={manage}/>}</InlinePanel>}
 {mode==='block'&&<BlockEditor branch={branch} day={day} zone={zone} close={()=>setMode(null)} saved={()=>{setMode(null);setPage(1);setRevision(v=>v+1);onChanged?.();}}/>}
 {blocks.length>0&&<div className="panel"><h3>Periodos bloqueados · {day}</h3><p className="muted">Los bloqueos de un profesional aplican en todas sus sucursales.</p>{blocks.map(b=><div className="availability-block" key={b.id}><div><strong>{b.resource_name}</strong><p>{format(b.starts_at)} — {format(b.ends_at)}</p><small>{b.reason}</small></div>{edit&&<button className="text-button" onClick={()=>setRelease(b)}>Liberar periodo</button>}</div>)}{(more||page>1)&&<div className="form-actions"><button className="button secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page}</span><button className="button secondary" disabled={!more} onClick={()=>setPage(p=>p+1)}>Más bloqueos</button></div>}</div>}
 {release&&<InlinePanel title={`Liberar periodo · ${release.resource_name}`} onClose={()=>setRelease(null)}><Form label="Confirmar liberación" onSubmit={async values=>{await api(`availability/blocks/${release.id}/release`,'PATCH',{version:release.version,reason:values.reason});setRelease(null);setPage(1);setRevision(v=>v+1);onChanged?.();}}><Field label="Motivo de liberación" name="reason" required maxLength={500}/></Form></InlinePanel>}</section>;
}
function Schedule({branch,professional,manage,room=false}:{branch:string;professional:string;manage:boolean;room?:boolean}){
 const endpoint=room?'room-schedule':'schedule',resourceKey=room?'room_id':'professional_id';
 const [data,setData]=useState<{weekly:Slot[];version:number}|null>(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;api<{weekly:Slot[];version:number}>(`availability/${endpoint}?branch_id=${branch}&${resourceKey}=${professional}`).then(r=>{if(live)setData(r);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[branch,professional,endpoint,resourceKey]);
 if(!data)return <><ErrorMessage message={error}/><p>Cargando horario…</p></>;
 function change(i:number,key:'start'|'end',value:string){setData(d=>d?{...d,weekly:d.weekly.map((s,j)=>j===i?{...s,[key]:value}:s)}:d);}
 return <><p className="muted">{data.version===0?'Sin configurar: no se restringen horas semanales. Al guardar, solo se permitirán citas dentro de los turnos indicados.':data.weekly.length?'Horario configurado. Los días sin turno no admiten citas.':'Sin turnos: no se admiten citas para este recurso.'}</p><Form disabled={!manage} label="Guardar horario" onSubmit={async values=>{const r=await api<{version:number}>('availability/'+endpoint,'POST',{[resourceKey]:professional,branch_id:branch,weekly:data.weekly,version:data.version,reason:values.reason});setData({...data,version:r.version});}}><div className="weekly-schedule">{days.map((day,index)=><div className="schedule-day" key={day}><strong>{day}</strong><div>{data.weekly.map((s,i)=>s.day===index+1?<div className="schedule-slot" key={i}><input aria-label={`${day} inicio ${i}`} type="time" required disabled={!manage} value={s.start} onChange={e=>change(i,'start',e.target.value)}/><span>a</span><input aria-label={`${day} fin ${i}`} type="time" required disabled={!manage} value={s.end} onChange={e=>change(i,'end',e.target.value)}/>{manage&&<button type="button" className="text-button" aria-label={`Quitar turno ${day} ${i}`} onClick={()=>setData({...data,weekly:data.weekly.filter((_,j)=>j!==i)})}>Quitar</button>}</div>:null)}{!data.weekly.some(s=>s.day===index+1)&&<small>Sin turnos</small>}</div>{manage&&<button type="button" className="text-button" disabled={data.weekly.length>=28} onClick={()=>setData({...data,weekly:[...data.weekly,{day:index+1,start:'09:00',end:'18:00'}]})}>Añadir turno {day}</button>}</div>)}</div>{manage?<Field label="Motivo del horario" name="reason" required maxLength={500}/>:<p>Solo administración puede modificar el horario.</p>}</Form></>;
}
function BlockEditor({branch,day,zone,close,saved}:{branch:string;day:string;zone:string;close:()=>void;saved:()=>void}){
 const [kind,setKind]=useState<'professional'|'room'>('professional'),[resource,setResource]=useState<Choice|null>(null);
 return <InlinePanel title="Bloquear periodo" onClose={close}><p className="muted">Descanso, vacaciones o mantenimiento · {zone}. Las citas existentes deben reprogramarse antes de bloquear su horario.</p><Form label="Guardar bloqueo" onSubmit={async values=>{if(!resource)throw new Error('Selecciona el recurso.');await api('availability/blocks','POST',{branch_id:branch,kind,resource_id:resource.id,start_local:values.start,end_local:values.end,reason:values.reason});saved();}}><div className="form-grid"><label className="field"><span>Tipo de recurso</span><select aria-label="Tipo de recurso" value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setResource(null);}}><option value="professional">Profesional · todas sus sucursales</option><option value="room">Consultorio</option></select></label><Resource key={kind} kind={kind==='professional'?'professionals':'rooms'} branch={branch} label="Recurso a bloquear" value={resource} onChange={setResource}/><Field label="Inicio del bloqueo" name="start" type="datetime-local" value={`${day}T09:00`} required/><Field label="Fin del bloqueo" name="end" type="datetime-local" value={`${day}T10:00`} required/><Field label="Motivo del bloqueo" name="reason" required maxLength={500}/></div></Form></InlinePanel>;
}
