'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {api} from '../lib/api';
import {cashDocumentHtml,type CashDocument,type CountDocument} from '../lib/cash-document';
import {ErrorMessage} from './ui';
type Bundle={closure:CashDocument;counts:{items:CountDocument[];version:number};consultedAt:string};
export function CashPrint({closureId,close}:{closureId:string;close:()=>void}){
 const [data,setData]=useState<Bundle|null>(null),[selected,setSelected]=useState('latest'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[frameKey,setFrameKey]=useState(0);
 const frame=useRef<HTMLIFrameElement>(null),pending=useRef(false);
 const load=useCallback(async():Promise<Bundle>=>{const [closure,counts]=await Promise.all([api<CashDocument>('cash-closures/'+closureId,'GET',undefined,15000),api<Bundle['counts']>('cash-closures/'+closureId+'/counts','GET',undefined,15000)]);return {closure,counts,consultedAt:new Date().toISOString()};},[closureId]);
 useEffect(()=>{let live=true;setData(null);setError('');load().then(r=>{if(live)setData(r);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[load,revision]);
 async function print(){setBusy(true);setError('');try{const fresh=await load();if(selected!=='latest'&&selected!=='none'&&!fresh.counts.items.some(r=>r.id===selected))throw new Error('La versión seleccionada ya no está entre las últimas 25. Cierra la vista previa y vuelve a consultar.');setData(fresh);pending.current=true;setFrameKey(v=>v+1);}catch(e){setError((e as Error).message);setBusy(false);}}
 const count=data?(selected==='latest'?data.counts.items[0]||null:data.counts.items.find(r=>r.id===selected)||null):null;
 return <section className="panel consent-detail"><div className="form-actions"><h2>Documento del corte</h2><button className="text-button" disabled={busy} onClick={close}>Cerrar documento</button></div><ErrorMessage message={error}/>{error&&<button className="text-button" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Reintentar documento</button>}{!data&&!error&&<p role="status">Cargando documento…</p>}{data&&<><label className="field"><span>Arqueo a incluir</span><select aria-label="Arqueo a incluir" value={selected} disabled={busy} onChange={e=>setSelected(e.target.value)}><option value="latest">Último arqueo guardado{data.counts.version?' · versión '+data.counts.version:' · sin registro'}</option><option value="none">Solo corte, sin arqueo</option>{data.counts.items.map(r=><option key={r.id} value={r.id}>Versión {r.version} · {r.author}</option>)}</select></label><p>Incluye todos los movimientos del corte guardado. Antes de imprimir se consultan nuevamente las versiones del arqueo. Elige “Guardar como PDF” en el diálogo de impresión para descargarlo.</p><button className="button primary" disabled={busy} aria-busy={busy} onClick={()=>void print()}>{busy?'Preparando documento…':'Imprimir corte / guardar PDF'}</button><iframe key={frameKey} ref={frame} title="Vista previa del corte" className="prescription-frame" sandbox="allow-same-origin allow-modals" srcDoc={cashDocumentHtml(data.closure,count,data.counts.version,data.consultedAt)} onLoad={()=>{if(pending.current){pending.current=false;try{if(!frame.current?.contentWindow)throw new Error();frame.current.contentWindow.focus();frame.current.contentWindow.print();}catch{setError('No se pudo abrir la impresión. Prueba en un navegador de escritorio.');}finally{setBusy(false);}}}}/></>}</section>;
}
