'use client';
import {useEffect,useRef,useState} from 'react';
import {api} from '../lib/api';
import {CashCount} from './cash-count';
import {Heading,ErrorMessage} from './ui';
type Filters={from:string;to:string;branch_id:string;collector_id?:string};
type Snapshot={filters:Filters;organization:string;timezone:string;branch:string;collector:string;totals:{currency:string;method:string;received_minor:number;voided_minor:number;net_minor:number}[];events:{payment_id:string;type:string;occurred_at:string;amount_minor:number;currency:string;method:string;collector:string;reference:string}[]};
type Preview={snapshot:Snapshot;token:string};
type Saved={id:string;snapshot:Snapshot;notes:string;created_at:string;author:string};
const methods:Record<string,string>={cash:'Efectivo',card:'Tarjeta',transfer:'Transferencia',other:'Otro'};
const money=(n:number,c:string)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:c}).format(n/100);
export function CashClosures({editable}:{editable:boolean}){
 const [options,setOptions]=useState<{branches:{id:string;name:string}[];collectors:{id:string;name:string}[];timezone:string}|null>(null),[filters,setFilters]=useState<Filters>({from:'',to:'',branch_id:''}),[preview,setPreview]=useState<Preview|null>(null),[saved,setSaved]=useState<Saved|null>(null),[rows,setRows]=useState<{id:string;created_at:string;author:string;branch:string;filters:Filters}[]>([]),[more,setMore]=useState(false),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notes,setNotes]=useState(''),[checked,setChecked]=useState(false),[eventPage,setEventPage]=useState(1);
 const [countDirty,setCountDirty]=useState(false);const request=useRef<{body:string;id:string}|null>(null);
 useEffect(()=>{let live=true;api<{branches:{id:string;name:string}[];collectors:{id:string;name:string}[];timezone:string;today:string}>('cash-closures/options','GET',undefined,15000).then(r=>{if(live){setOptions(r);setFilters(f=>f.from?f:{from:r.today,to:r.today,branch_id:r.branches[0]?.id||''});}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[revision]);
 useEffect(()=>{let live=true;api<{items:typeof rows;hasMore:boolean}>('cash-closures?page='+page,'GET',undefined,15000).then(r=>{if(live){setRows(r.items);setMore(r.hasMore);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[page,revision]);
 function change(f:Filters){setFilters(f);setPreview(null);setSaved(null);setChecked(false);setEventPage(1);}
 async function consult(){setBusy(true);setError('');setPreview(null);setSaved(null);setChecked(false);try{setPreview(await api<Preview>('cash-closures/preview?'+new URLSearchParams(filters as Record<string,string>),'GET',undefined,15000));setEventPage(1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){if(!preview)return;setBusy(true);setError('');try{const payload={filters:preview.snapshot.filters,token:preview.token,notes,reviewed:checked},body=JSON.stringify(payload);if(request.current?.body!==body)request.current={body,id:crypto.randomUUID()};const result=await api<{id:string}>('cash-closures','POST',{...payload,request_id:request.current!.id},15000);setSaved(await api<Saved>('cash-closures/'+result.id,'GET',undefined,15000));setPreview(null);setNotes('');setChecked(false);setPage(1);setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const snapshot=saved?.snapshot||preview?.snapshot;
 return <><Heading eyebrow="ADMINISTRACIÓN" title="Corte de caja" description="Consulta los registros del periodo y conserva una copia para revisión."/><div className="consent-detail"><ErrorMessage message={error}/><p>Pagos y anulaciones según la fecha en que se registraron. Los importes se separan por moneda y método. No representa efectivo contado ni incluye devoluciones, gastos o fondo inicial.</p><form className="form panel" onSubmit={e=>{e.preventDefault();void consult();}}><fieldset className="budget-fields" disabled={busy||!options||countDirty}><legend>Periodo y responsables</legend><div className="form-grid"><label className="field"><span>Desde</span><input type="date" required value={filters.from} onChange={e=>change({...filters,from:e.target.value})}/></label><label className="field"><span>Hasta (incluido)</span><input type="date" required value={filters.to} onChange={e=>change({...filters,to:e.target.value})}/></label><label className="field"><span>Sucursal del corte</span><select aria-label="Sucursal del corte" required value={filters.branch_id} onChange={e=>change({...filters,branch_id:e.target.value})}><option value="">Selecciona una sucursal</option>{options?.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="field"><span>Responsable del cobro</span><select aria-label="Responsable del cobro" value={filters.collector_id||''} onChange={e=>{const next={...filters};if(e.target.value)next.collector_id=e.target.value;else delete next.collector_id;change(next);}}><option value="">Todos los responsables</option>{options?.collectors.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label></div><small>Hasta 31 días · Zona horaria: {options?.timezone}. Las anulaciones se atribuyen al responsable y sucursal del pago original.</small><button className="button primary" aria-busy={busy}>Consultar corte</button></fieldset></form>{!options&&<button className="text-button" onClick={()=>setRevision(v=>v+1)}>Reintentar carga</button>}
 {snapshot&&<section className="panel"><h2>{saved?'Corte guardado':'Vista previa del corte'}</h2>{saved&&<p role="status" className="saved">Corte conservado · Folio: {saved.id} · {saved.author} · {new Date(saved.created_at).toLocaleString('es-MX')}</p>}<p>{snapshot.branch} · {snapshot.collector}<br/>{snapshot.filters.from} al {snapshot.filters.to} · {snapshot.timezone}</p><p>Es una copia de los registros consultados. No bloquea el periodo. Otros cortes pueden solaparse: no sumes sus totales entre sí.</p>{!snapshot.totals.length&&<p>No hay movimientos para estos filtros.</p>}{snapshot.totals.map(t=><article className="clinical-entry" key={t.currency+t.method}><h3>{t.currency} · {methods[t.method]}</h3><div className="payment-summary"><p>Pagos registrados<strong>{money(t.received_minor,t.currency)}</strong></p><p>Anulaciones registradas<strong>{money(t.voided_minor,t.currency)}</strong></p><p>Neto de registros<strong>{money(t.net_minor,t.currency)}</strong></p></div></article>)}{saved?.notes&&<p className="patient-notes">Observaciones: {saved.notes}</p>}{editable&&preview&&<form className="form" onSubmit={e=>{e.preventDefault();void save();}}><fieldset className="budget-fields" disabled={busy}><legend>Conservar corte revisado</legend><label className="field"><span>Observaciones del corte</span><textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="check-field"><input type="checkbox" required checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>Revisé periodo, responsables y movimientos. Entiendo que este corte no es un arqueo físico de efectivo.</span></label><button className="button primary" disabled={busy||!checked} aria-busy={busy}>Guardar corte revisado</button></fieldset></form>}<details><summary>Movimientos incluidos ({snapshot.events.length})</summary>{snapshot.events.slice((eventPage-1)*20,eventPage*20).map((e,i)=><article className="clinical-entry" key={e.payment_id+e.type+i}><strong>{e.type==='void'?'Anulación':'Pago'} · {money(e.amount_minor,e.currency)} {e.currency}</strong><p>{methods[e.method]} · {e.collector} · {new Date(e.occurred_at).toLocaleString('es-MX',{timeZone:snapshot.timezone})}</p><p>Pago: {e.payment_id}</p>{e.reference&&<p className="patient-notes">{e.reference}</p>}</article>)}<div className="form-actions"><button className="text-button" disabled={eventPage===1} onClick={()=>setEventPage(p=>p-1)}>Movimientos anteriores</button><button className="text-button" disabled={eventPage*20>=snapshot.events.length} onClick={()=>setEventPage(p=>p+1)}>Más movimientos</button></div></details></section>}
 {saved&&<CashCount key={saved.id} closureId={saved.id} editable={editable} onDirty={setCountDirty}/>}<h2>Cortes guardados</h2>{!rows.length&&<p>No hay cortes guardados en esta página.</p>}{rows.map(r=><article className="clinical-entry" key={r.id}><strong>{r.branch} · {r.filters.from} al {r.filters.to}</strong><p>{r.author} · {new Date(r.created_at).toLocaleString('es-MX')}</p><button className="text-button" disabled={busy||countDirty} onClick={async()=>{if((notes||checked)&&!window.confirm('¿Descartar la revisión pendiente y abrir el corte guardado?'))return;setBusy(true);setError('');try{setSaved(await api<Saved>('cash-closures/'+r.id,'GET',undefined,15000));setPreview(null);setNotes('');setChecked(false);setEventPage(1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Ver corte guardado</button></article>)}<div className="form-actions"><button className="text-button" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Actualizar historial de cortes</button><button className="text-button" disabled={busy||page===1} onClick={()=>setPage(p=>p-1)}>Cortes recientes</button><button className="text-button" disabled={busy||!more} onClick={()=>setPage(p=>p+1)}>Cortes anteriores</button></div></div></>;
}

