'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { Building2,Clock,Plus,Search,Stethoscope,Tag } from 'lucide-react';
import type { Context } from '../lib/types';
import { Resource,type Choice } from './resource-picker';
import { api } from '../lib/api';
import { Empty,ErrorMessage,Field,Form,Heading,InlinePanel } from './ui';
type Kind='professionals'|'rooms'|'services';
interface Entry {id:string;name:string;active:boolean;version:number;relationship?:'unspecified'|'internal'|'external';professional_title?:string;training_institution?:string;external_organization?:string;practice_address?:string;specialty?:string;license?:string;specialty_license?:string;email?:string;phone?:string;branch_ids?:string[];branch_id?:string;number?:string;chair?:string;equipment?:string;notes?:string;code?:string;category?:string;duration_minutes?:number;price_minor?:number;cost_minor?:number;currency?:string;requires_tooth?:boolean;requires_consent?:boolean}
interface Price {price_minor:number;cost_minor:number;currency:string;version:number;created_at:string}
const labels={professionals:{title:'Profesionales',description:'Las personas que brindan atención en tu práctica.',single:'profesional',icon:Stethoscope},rooms:{title:'Consultorios',description:'Espacios de atención, organizados por sucursal.',single:'consultorio',icon:Building2},services:{title:'Servicios',description:'Un catálogo claro para planear la atención.',single:'servicio',icon:Tag}};
const relationships={unspecified:'Sin clasificar',internal:'Doctor interno',external:'Especialista externo'};
const categories=['Preventiva','Restaurativa','Endodoncia','Cirugía','Ortodoncia','Periodoncia','Implantología','Prótesis','Estética','Diagnóstico','Otros'];
function money(amount:number,currency:string){return new Intl.NumberFormat('es-MX',{style:'currency',currency}).format(amount/100);}
function minor(value:string){if(!/^\d+(\.\d{1,2})?$/.test(value))throw new Error('Introduce un importe positivo con hasta dos decimales.');const [whole,fraction='']=value.split('.');return Number(whole)*100+Number(fraction.padEnd(2,'0'));}
export function Catalogs({kind,context,initialSearch='',initialStatus='active',initialId}:{kind:Kind;context:Context;initialSearch?:string;initialStatus?:string;initialId?:string}){
 const loadSequence=useRef(0);
 const [relationship,setRelationship]=useState('all');
 const [roomEditor,setRoomEditor]=useState<Entry|null>(null);
 const [serviceEditor,setServiceEditor]=useState<Entry|null>(null);
 const [selectedId,setSelectedId]=useState(initialId);
 const config=labels[kind],canEdit=context.permissions.includes('catalogs.manage');
 const [items,setItems]=useState<Entry[]>([]),[query,setQuery]=useState(initialSearch),[search,setSearch]=useState(initialSearch),[status,setStatus]=useState(initialStatus),[page,setPage]=useState(1),[hasMore,setMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState<Entry|'new'|null>(null),[prices,setPrices]=useState<Price[]|null>(null);
 const load=useCallback(async()=>{const sequence=++loadSequence.current;setBusy(true);try{const data=await api<{items:Entry[];hasMore:boolean}>(`catalogs/${kind}?${new URLSearchParams({q:search,status,page:String(page),...(kind==='professionals'?{relationship}:{}),...(selectedId&&!search?{id:selectedId}:{})})}`);if(sequence!==loadSequence.current)return;setItems(data.items);setMore(data.hasMore);setError('');}catch(e){if(sequence===loadSequence.current)setError((e as Error).message);}finally{if(sequence===loadSequence.current)setBusy(false);}},[kind,search,status,page,selectedId,relationship]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{const timer=setTimeout(()=>{setSearch(query);setPage(1);},250);return()=>clearTimeout(timer);},[query]);
 return <><Heading eyebrow="OPERACIÓN · CATÁLOGOS" title={config.title} description={config.description} action={canEdit?<button className="button primary" onClick={()=>setEditing('new')}><Plus size={17}/>Nuevo {config.single}</button>:undefined}/>
 {editing&&<CatalogEditor key={editing==='new'?'new':editing.id} kind={kind} entry={editing==='new'?null:editing} context={context} close={()=>setEditing(null)} saved={async()=>{setEditing(null);await load();}}/>}
 {roomEditor&&<ProfessionalRooms key={roomEditor.id} entry={roomEditor} context={context} close={()=>setRoomEditor(null)} saved={async()=>{setRoomEditor(null);await load();}}/>}
 {serviceEditor&&<ProfessionalServices key={serviceEditor.id} entry={serviceEditor} branch={context.branches.find(b=>b.active)?.id||''} close={()=>setServiceEditor(null)} saved={async()=>{setServiceEditor(null);await load();}}/>}
 {prices&&<InlinePanel title="Historial de precios" onClose={()=>setPrices(null)}>{prices.map(p=><div className="invitation-row" key={p.version}><div><strong>{money(p.price_minor,p.currency)}</strong><small>Costo estimado: {money(p.cost_minor,p.currency)}</small></div><span className="muted">Versión {p.version} · {new Date(p.created_at).toLocaleString('es-MX')}</span></div>)}</InlinePanel>}
 {selectedId&&<p className="muted">Resultado de la búsqueda global · <button className="text-button" onClick={()=>{setSelectedId(undefined);setQuery('');setPage(1);}}>Ver todo el catálogo</button></p>}
 <div className="patients-toolbar"><label className="patients-search"><Search size={18}/><input aria-label={`Buscar ${config.title.toLowerCase()}`} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nombre"/></label><label className="patients-filter"><span className="sr-only">Estado del catálogo</span><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="active">Activos</option><option value="inactive">Inactivos</option><option value="all">Todos</option></select></label>{kind==='professionals'&&<label className="patients-filter"><span className="sr-only">Relación con el consultorio</span><select aria-label="Relación con el consultorio" value={relationship} onChange={e=>{setRelationship(e.target.value);setPage(1);}}><option value="all">Todos los profesionales</option>{Object.entries(relationships).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>}</div><ErrorMessage message={error}/>
 {busy?<p className="skeleton" role="status">Cargando catálogo…</p>:items.length?<div>{items.map(item=><article className="branch-row catalog-row" key={item.id}><span className="branch-icon"><config.icon size={24}/></span><div><h2>{item.name}<span className={`pill ${item.active?'green':''}`}>{item.active?'Activo':'Inactivo'}</span></h2>{kind==='professionals'?<><span className="pill">{relationships[item.relationship||'unspecified']}</span>{item.external_organization&&<p>{item.external_organization}</p>}<p>{item.specialty||'Especialidad sin registrar'} · {item.license?`Cédula ${item.license}`:'Cédula pendiente'}</p><small>{item.branch_ids?.map(id=>context.branches.find(b=>b.id===id)?.name||'Sucursal').join(' · ')||'Sin atención en sucursales · contacto externo'}</small>{item.email&&<small>{item.email}</small>}</>:kind==='rooms'?<><p>{context.branches.find(b=>b.id===item.branch_id)?.name} {item.number&&`· N.º ${item.number}`}</p><small>{item.chair||'Sillón sin identificar'}{item.equipment&&` · ${item.equipment}`}</small></>:<><p>{item.code} · {item.category} · <Clock size={14}/>{item.duration_minutes} min</p><small>{item.requires_tooth?'Requiere pieza dental':''}{item.requires_consent?' · Requiere consentimiento':''}</small></>}</div>{kind==='services'&&<strong className="catalog-price">{money(item.price_minor!,item.currency!)}</strong>}<div className="catalog-actions">{kind==='professionals'&&canEdit&&<button className="text-button" onClick={()=>setRoomEditor(item)}>Consultorios habilitados</button>}{kind==='professionals'&&canEdit&&<button className="text-button" onClick={()=>setServiceEditor(item)}>Servicios habilitados</button>}{canEdit&&<button className="button secondary" onClick={()=>setEditing(item)}>Editar {config.single}</button>}{kind==='services'&&canEdit&&<button className="text-button" onClick={async()=>{try{setPrices(await api<Price[]>(`catalogs/services/${item.id}/prices`));}catch(e){setError((e as Error).message);}}}>Historial de precios</button>}</div></article>)}</div>:!error?<Empty icon={<config.icon size={28}/>} title={`Aún no hay ${config.title.toLowerCase()}`} description={search?'Prueba con otro nombre.':`Añade tu primer ${config.single} para preparar tu operación.`}/>:null}
 <div className="patients-pagination"><span>Página {page} · Hasta 25 registros</span><div><button className="button secondary" disabled={page===1||busy} onClick={()=>setPage(p=>p-1)}>Anterior</button><button className="button secondary" disabled={!hasMore||busy} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div></div><p className="muted footnote">{kind==='professionals'?'Un profesional puede existir sin usuario ni relación laboral. Su registro no crea acceso al sistema.':kind==='rooms'?'Los consultorios se podrán reservar al incorporar la agenda.':'Los importes son precios de catálogo; no crean cobros ni planes de tratamiento.'}</p>
 </>;
}
function CatalogEditor({kind,entry:e,context,close,saved}:{kind:Kind;entry:Entry|null;context:Context;close:()=>void;saved:()=>Promise<void>}){
 const [relationship,setRelationship]=useState(e?.relationship||'unspecified');
 const [active,setActive]=useState(e?.active??true),[branches,setBranches]=useState<string[]>(e?.branch_ids||context.branches.filter(b=>b.active).slice(0,1).map(b=>b.id));
 return <InlinePanel title={`${e?'Editar':'Nuevo'} ${labels[kind].single}`} onClose={close}><Form label={e?'Guardar cambios':`Crear ${labels[kind].single}`} onSubmit={async values=>{
  const data:Record<string,unknown>={...values,active};
  if(kind==='professionals'){data.branch_ids=branches;data.relationship=relationship;}
  if(kind==='services'){
   data.price_minor=minor(values.price);data.cost_minor=minor(values.cost);delete data.price;delete data.cost;
   data.duration_minutes=Number(values.duration_minutes);data.currency=context.organization.currency;data.requires_tooth=values.requires_tooth==='true';data.requires_consent=values.requires_consent==='true';
  }
  if(e)data.version=e.version;
  await api(`catalogs/${kind}${e?`/${e.id}`:''}`,e?'PATCH':'POST',data);await saved();
 }}><div className="form-grid"><Field label="Nombre" name="name" value={e?.name} required minLength={2} maxLength={160}/>
 {kind==='professionals'&&<><label className="field"><span>Tipo de relación</span><select aria-label="Tipo de relación" value={relationship} onChange={event=>setRelationship(event.target.value as Entry['relationship']||'unspecified')}>{Object.entries(relationships).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><Field label="Título profesional" name="professional_title" value={e?.professional_title} maxLength={80}/><Field label="Institución de formación" name="training_institution" value={e?.training_institution} maxLength={160}/><Field label="Consultorio o institución externa" name="external_organization" value={e?.external_organization} maxLength={160}/><Field label="Dirección profesional" name="practice_address" value={e?.practice_address} maxLength={500}/><Field label="Especialidad" name="specialty" value={e?.specialty} maxLength={120}/><Field label="Cédula profesional" name="license" value={e?.license} maxLength={50}/><Field label="Cédula de especialidad" name="specialty_license" value={e?.specialty_license} maxLength={50}/><Field label="Correo electrónico" name="email" type="email" value={e?.email}/><Field label="Teléfono" name="phone" value={e?.phone} maxLength={30}/><fieldset className="permission-fieldset full-width"><legend>Sucursales de atención</legend><p>{relationship==='external'?'Marca las sucursales donde atiende. Si solo recibe referencias fuera del consultorio, desmarca todas.':'Selecciona al menos una sucursal.'}</p><div className="permissions-grid">{context.branches.map(b=><label className="check-field" key={b.id}><input type="checkbox" checked={branches.includes(b.id)} onChange={event=>setBranches(prior=>event.target.checked?[...prior,b.id]:prior.filter(id=>id!==b.id))}/><span>{b.name}{!b.active?' · Inactiva':''}</span></label>)}</div></fieldset></>}
 {kind==='rooms'&&<><label className="field"><span>Sucursal</span><select name="branch_id" defaultValue={e?.branch_id||context.branches.find(b=>b.active)?.id} required>{context.branches.map(b=><option key={b.id} value={b.id}>{b.name}{!b.active?' · Inactiva':''}</option>)}</select></label><Field label="Número" name="number" value={e?.number} maxLength={30}/><Field label="Identificador del sillón" name="chair" value={e?.chair} maxLength={80}/><Field label="Equipamiento" name="equipment" value={e?.equipment} maxLength={1000}/><Field label="Notas del consultorio" name="notes" value={e?.notes} maxLength={2000}/></>}
 {kind==='services'&&<><Field label="Código" name="code" value={e?.code} required maxLength={30} help="Mayúsculas, números, guion y guion bajo."/><label className="field"><span>Categoría</span><select name="category" defaultValue={e?.category||'Preventiva'}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><Field label="Especialidad" name="specialty" value={e?.specialty} maxLength={120}/><Field label="Duración en minutos" name="duration_minutes" type="number" value={String(e?.duration_minutes||30)} required/><Field label={`Precio (${context.organization.currency})`} name="price" value={((e?.price_minor||0)/100).toFixed(2)} required/><Field label={`Costo estimado (${context.organization.currency})`} name="cost" value={((e?.cost_minor||0)/100).toFixed(2)} required/><label className="field"><span>Requiere pieza dental</span><select name="requires_tooth" defaultValue={String(e?.requires_tooth||false)}><option value="false">No</option><option value="true">Sí</option></select></label><label className="field"><span>Requiere consentimiento</span><select name="requires_consent" defaultValue={String(e?.requires_consent||false)}><option value="false">No</option><option value="true">Sí</option></select></label></>}
 {e&&<><label className="field"><span>Estado del registro</span><select value={String(active)} onChange={event=>setActive(event.target.value==='true')}><option value="true">Activo</option><option value="false">Inactivo</option></select></label>{active!==e.active&&<Field label="Motivo del cambio de estado" name="reason" required maxLength={500}/>}</>}
 </div></Form></InlinePanel>;
}

function ProfessionalServices({entry,branch,close,saved}:{entry:Entry;branch:string;close:()=>void;saved:()=>Promise<void>}){
 const [data,setData]=useState<{version:number;restrict_services:boolean;services:(Choice&{active:boolean})[]}|null>(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;api<NonNullable<typeof data>>('catalogs/professionals/'+entry.id+'/services').then(r=>{if(live)setData(r);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[entry.id]);
 return <InlinePanel title={'Servicios de '+entry.name} onClose={close}><ErrorMessage message={error}/>{data?<Form label="Guardar servicios" onSubmit={async()=>{await api('catalogs/professionals/'+entry.id+'/services','PATCH',{version:data.version,restrict_services:data.restrict_services,service_ids:data.services.map(s=>s.id)});await saved();}}><label className="field"><span>Servicios que puede atender</span><select value={String(data.restrict_services)} onChange={e=>setData({...data,restrict_services:e.target.value==='true'})}><option value="false">Todos los servicios activos</option><option value="true">Solo los servicios seleccionados</option></select></label>{data.restrict_services&&<><Resource kind="services" branch={branch} label="Añadir servicio" required={false} value={null} onChange={s=>{if(s&&!data.services.some(item=>item.id===s.id))setData({...data,services:[...data.services,{...s,active:true}]});}}/>{data.services.map(s=><div className="invitation-row" key={s.id}><span>{s.name}{!s.active?' · Inactivo':''}</span><button type="button" className="text-button" onClick={()=>setData({...data,services:data.services.filter(item=>item.id!==s.id)})}>Quitar {s.name}</button></div>)}{!data.services.length&&<p>No podrá recibir citas hasta que añadas un servicio.</p>}</>}<p className="muted">No se pueden retirar servicios con citas pendientes. Los servicios inactivos no aparecen al agendar.</p></Form>:!error?<p role="status">Cargando servicios…</p>:null}</InlinePanel>;
}

function ProfessionalRooms({entry,context,close,saved}:{entry:Entry;context:Context;close:()=>void;saved:()=>Promise<void>}){
 const branches=context.branches.filter(b=>entry.branch_ids?.includes(b.id));
 const [branch,setBranch]=useState(branches.find(b=>b.active)?.id||branches[0]?.id||'');
 const [data,setData]=useState<{version:number;restrict_rooms:boolean;rooms:(Choice&{active:boolean;branch_id:string})[]}|null>(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;api<NonNullable<typeof data>>('catalogs/professionals/'+entry.id+'/rooms').then(r=>{if(live)setData(r);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[entry.id]);
 return <InlinePanel title={'Consultorios de '+entry.name} onClose={close}><ErrorMessage message={error}/>{data?<Form label="Guardar consultorios" onSubmit={async()=>{await api('catalogs/professionals/'+entry.id+'/rooms','PATCH',{version:data.version,restrict_rooms:data.restrict_rooms,room_ids:data.rooms.map(s=>s.id)});await saved();}}><label className="field"><span>Consultorios que puede utilizar</span><select value={String(data.restrict_rooms)} onChange={e=>setData({...data,restrict_rooms:e.target.value==='true'})}><option value="false">Todos los consultorios de sus sucursales</option><option value="true">Solo los consultorios seleccionados</option></select></label>{data.restrict_rooms&&<><label className="field"><span>Sucursal del consultorio</span><select value={branch} onChange={e=>setBranch(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}{!b.active?' · Inactiva':''}</option>)}</select></label><Resource key={branch} kind="rooms" branch={branch} label="Añadir consultorio" required={false} value={null} onChange={s=>{if(s&&!data.rooms.some(item=>item.id===s.id))setData({...data,rooms:[...data.rooms,{...s,active:true,branch_id:branch}]});}}/>{data.rooms.map(s=><div className="invitation-row" key={s.id}><span>{s.name} · {context.branches.find(b=>b.id===s.branch_id)?.name||'Sucursal'}{!s.active?' · Inactivo':''}</span><button type="button" className="text-button" onClick={()=>setData({...data,rooms:data.rooms.filter(item=>item.id!==s.id)})}>Quitar {s.name}</button></div>)}{!data.rooms.length&&<p>No podrá recibir citas hasta que añadas un consultorio.</p>}</>}<p className="muted">No se pueden retirar consultorios con citas pendientes. Los consultorios inactivos no aparecen al agendar.</p></Form>:!error?<p role="status">Cargando consultorios…</p>:null}</InlinePanel>;
}
