'use client';
import { useEffect,useRef,useState } from 'react';
import { ConditionsView,ConditionsEditor,type Conditions } from './clinical-conditions';
import { ClinicalAppointmentPicker,appointmentLabel,type ClinicalAppointment } from './clinical-appointment-picker';
import { api } from '../lib/api';
import { ErrorMessage,Section } from './ui';
type Summary={allergy_status:'unknown'|'none_reported'|'reported';allergies:string;history:string;medications:string;conditions?:Conditions};
type Entry={id:string;kind:'summary'|'note';version:number;payload:Summary&{content?:string;appointment?:ClinicalAppointment};author:string;created_at:string};
type RecordData={current:Entry|null;entries:Entry[];hasMore:boolean};
const empty:Summary={allergy_status:'unknown',allergies:'',history:'',medications:''};
const statuses={unknown:'Sin verificar',none_reported:'No refiere alergias',reported:'Alergias reportadas'};
function SummaryView({value}:{value:Summary}){return <><ConditionsView value={value.conditions} allergy={{status:value.allergy_status,detail:value.allergies}}/><dl className="clinical-summary"><dt>Alergias · {statuses[value.allergy_status]}</dt><dd>{value.allergies||'Sin detalle registrado'}</dd><dt>Antecedentes</dt><dd>{value.history||'Sin registrar'}</dd><dt>Medicamentos actuales</dt><dd>{value.medications||'Sin registrar'}</dd></dl></>;}
export function ClinicalRecord({patientId,editable}:{patientId:string;editable:boolean}){
 const [appointment,setAppointment]=useState<ClinicalAppointment|null>(null);
 const base='patients/'+patientId+'/clinical',request=useRef<{body:string;id:string}|null>(null);
 const [data,setData]=useState<RecordData|null>(null),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[adding,setAdding]=useState(false),[draft,setDraft]=useState<Summary>(empty),[version,setVersion]=useState(0),[content,setContent]=useState('');
 useEffect(()=>{let live=true;api<RecordData>(base+'?page='+page,'GET',undefined,15000).then(r=>{if(live){setData(r);setError('');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[base,page,revision]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(editing||adding){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[editing,adding]);
 async function save(kind:'summary'|'note'){
  const body=JSON.stringify(kind==='summary'?{kind,version,payload:draft}:{kind,payload:{content,...(appointment?{appointment_id:appointment.id}:{})}});if(!request.current||request.current.body!==body)request.current={body,id:crypto.randomUUID()};setBusy(true);setError('');setMessage('');
  try{await api(base,'POST',{...JSON.parse(body),request_id:request.current.id},15000);setEditing(false);setAdding(false);setContent('');setAppointment(null);setAppointment(null);setPage(1);setRevision(v=>v+1);request.current=null;setMessage(kind==='summary'?'Antecedentes guardados.':'Nota de consulta registrada.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 return <Section title="Expediente clínico" description="Antecedentes y notas de consulta. Cada registro conserva autor y fecha; las versiones anteriores permanecen en el historial."><ErrorMessage message={error}/>{error&&!data&&<button className="text-button" onClick={()=>setRevision(v=>v+1)}>Reintentar carga del expediente</button>}{message&&<p role="status" className="saved">{message}</p>}{!data&&!error&&<p>Cargando expediente…</p>}{data&&<>
 <div className={data.current?.payload.allergy_status==='reported'?'notice':'panel'}><strong>{statuses[data.current?.payload.allergy_status||'unknown']}</strong>{data.current?.payload.allergy_status==='reported'&&<p className="patient-notes">{data.current.payload.allergies}</p>}</div>
 {!editing&&<><SummaryView value={data.current?.payload||empty}/>{editable&&<button className="button secondary" disabled={adding||busy} onClick={()=>{setDraft(data.current?.payload||empty);setVersion(data.current?.version||0);setEditing(true);setMessage('');}}>Editar antecedentes</button>}</>}
 {editing&&<form className="form clinical-form" onSubmit={e=>{e.preventDefault();void save('summary');}}><label className="field"><span>Estado de alergias</span><select aria-label="Estado de alergias" value={draft.allergy_status} disabled={busy} onChange={e=>setDraft({...draft,allergy_status:e.target.value as Summary['allergy_status'],allergies:''})}>{Object.entries(statuses).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>{draft.allergy_status==='reported'&&<label className="field"><span>Alergias reportadas</span><textarea aria-label="Alergias reportadas" required maxLength={3000} value={draft.allergies} disabled={busy} onChange={e=>setDraft({...draft,allergies:e.target.value})}/></label>}{(['history','medications'] as const).map(key=><label className="field" key={key}><span>{key==='history'?'Antecedentes':'Medicamentos actuales'}</span><textarea aria-label={key==='history'?'Antecedentes':'Medicamentos actuales'} maxLength={key==='history'?6000:3000} disabled={busy} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<ConditionsEditor value={draft.conditions} disabled={busy} onChange={conditions=>setDraft({...draft,conditions})}/><div className="form-actions"><button className="button primary" disabled={busy} aria-busy={busy}>Guardar antecedentes</button><button type="button" className="text-button" disabled={busy} onClick={()=>{if(window.confirm('¿Descartar los cambios de antecedentes?'))setEditing(false);}}>Cancelar</button></div></form>}
 {!adding&&editable&&<button className="button secondary" disabled={editing||busy} onClick={()=>{setAdding(true);setMessage('');}}>Añadir nota de consulta</button>}
 {adding&&<form className="form clinical-form" onSubmit={e=>{e.preventDefault();void save('note');}}><ClinicalAppointmentPicker patientId={patientId} value={appointment} onChange={setAppointment} disabled={busy}/><label className="field"><span>Nota de consulta</span><textarea aria-label="Nota de consulta" required maxLength={10000} disabled={busy} value={content} onChange={e=>setContent(e.target.value)}/></label><p>La nota se registra con tu nombre y la fecha actual. Para corregirla después, añade una nueva nota aclaratoria.</p><div className="form-actions"><button className="button primary" disabled={busy||!content.trim()} aria-busy={busy}>Registrar nota</button><button className="text-button" type="button" disabled={busy} onClick={()=>{if(!content||window.confirm('¿Descartar esta nota?')){setAdding(false);setContent('');}}}>Cancelar nota</button></div></form>}
 <h3>Historial clínico</h3>{!data.entries.length&&<p>Todavía no hay registros clínicos.</p>}{data.entries.map(entry=><details key={entry.id} className="clinical-entry"><summary>{entry.kind==='summary'?'Antecedentes · versión '+entry.version:'Nota de consulta'} · {entry.author} · {new Date(entry.created_at).toLocaleString('es-MX')}</summary>{entry.kind==='summary'?<SummaryView value={entry.payload}/>:<>{entry.payload.appointment&&<p className="notice">Cita: {appointmentLabel(entry.payload.appointment)}</p>}<p className="patient-notes">{entry.payload.content}</p></>}</details>)}<div className="form-actions"><button className="text-button" disabled={editing||adding||busy} onClick={()=>setRevision(v=>v+1)}>Actualizar expediente</button>{page>1&&<button className="text-button" onClick={()=>setPage(p=>p-1)}>Registros recientes</button>}{data.hasMore&&<button className="text-button" onClick={()=>setPage(p=>p+1)}>Registros anteriores</button>}</div>
 </>}</Section>;
}
