'use client';
import { useEffect,useState } from 'react';
import { api } from '../lib/api';
import { ErrorMessage } from './ui';
export type ClinicalAppointment={id:string;starts_at:string;timezone:string;status:string;professional_name:string;service_name:string};
const states:Record<string,string>={pending:'Pendiente',confirmed:'Confirmada',arrived:'Llegó',in_consultation:'En consulta',completed:'Completada',cancelled:'Cancelada',no_show:'Inasistencia'};
export function appointmentLabel(a:ClinicalAppointment){return new Date(a.starts_at).toLocaleString('es-MX',{timeZone:a.timezone})+' · '+a.professional_name+' · '+a.service_name+' · '+(states[a.status]||a.status);}
export function ClinicalAppointmentPicker({patientId,value,onChange,disabled}:{patientId:string;value:ClinicalAppointment|null;onChange:(a:ClinicalAppointment|null)=>void;disabled:boolean}){
 const [page,setPage]=useState(1),[rows,setRows]=useState<ClinicalAppointment[]>([]),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let live=true;api<{items:ClinicalAppointment[];hasMore:boolean}>('patients/'+patientId+'/clinical/appointments?page='+page,'GET',undefined,15000).then(r=>{if(live){setRows(r.items);setMore(r.hasMore);setError('');}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[patientId,page,retry]);
 return <div><label className="field"><span>Cita relacionada (opcional)</span><select aria-label="Cita relacionada" disabled={disabled||loading} value={value?.id||''} onChange={e=>onChange(rows.find(a=>a.id===e.target.value)||null)}><option value="">Nota general, sin cita</option>{value&&!rows.some(a=>a.id===value.id)&&<option value={value.id}>{appointmentLabel(value)}</option>}{rows.map(a=><option key={a.id} value={a.id}>{appointmentLabel(a)}</option>)}</select></label>{loading&&<p role="status">Cargando citas…</p>}<ErrorMessage message={error}/>{error&&<button type="button" className="text-button" disabled={disabled||loading} onClick={()=>{setLoading(true);setRetry(v=>v+1);}}>Reintentar citas</button>}<div className="form-actions">{page>1&&<button type="button" className="text-button" disabled={disabled||loading} onClick={()=>{setLoading(true);setPage(p=>p-1);}}>Citas más recientes</button>}{more&&<button type="button" className="text-button" disabled={disabled||loading} onClick={()=>{setLoading(true);setPage(p=>p+1);}}>Citas anteriores</button>}</div><small>Se conservan la fecha y el profesional de la cita al registrar la nota.</small></div>;
}
