'use client';
import {useEffect,useRef,useState} from 'react';
import {api,downloadFile} from '../lib/api';
import {consentHtml,consentStates,type ConsentDocument,type ConsentStatus} from '../lib/consent-document';
import {ErrorMessage} from './ui';
type Event={id:string;version:number;status:ConsentStatus;reason:string;signer_name:string;signer_relationship:string;occurred_on:string;author:string;created_at:string;evidence:{filename:string}|null};
type Detail={consent:ConsentDocument;status:ConsentStatus;version:number;events:Event[]};
export function ConsentDetail({patientId,id,editable,onSaved,close}:{patientId:string;id:string;editable:boolean;onSaved:()=>void;close:()=>void}){
 const base='patients/'+patientId+'/consents/'+id;
 const [data,setData]=useState<Detail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[ready,setReady]=useState(false),[editing,setEditing]=useState(false),[message,setMessage]=useState('');
 const [status,setStatus]=useState('accepted'),[reason,setReason]=useState(''),[name,setName]=useState(''),[relationship,setRelationship]=useState(''),[date,setDate]=useState(''),[file,setFile]=useState<File|null>(null),[checked,setChecked]=useState(false);
 const request=useRef<{body:string;id:string}|null>(null),frame=useRef<HTMLIFrameElement>(null);
 useEffect(()=>{let live=true;api<Detail>(base,'GET',undefined,15000).then(r=>{if(live){setData(r);setError('');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[base,revision]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(editing){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[editing]);
 const leave=()=>!editing||window.confirm('¿Descartar la decisión sin registrar?');
 async function save(){if(!data)return;setBusy(true);setError('');try{
  let evidence;if(file){if(file.size>5*1024*1024)throw new Error('El archivo no puede superar 5 MiB.');const encoded=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('No pudimos leer el archivo. Selecciónalo de nuevo.'));reader.readAsDataURL(file);});evidence={filename:file.name,media_type:file.type,content_base64:encoded};}
  const payload={version:data.version,status,reason,signer_name:name,signer_relationship:relationship,occurred_on:date,...(evidence?{evidence}:{})};const body=JSON.stringify(payload);if(request.current?.body!==body)request.current={body,id:crypto.randomUUID()};
  await api(base+'/events','POST',{...payload,request_id:request.current!.id},30000);setEditing(false);setFile(null);setMessage('Decisión registrada. El historial se conserva.');setRevision(v=>v+1);onSaved();
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="panel prescription-review consent-detail"><div className="form-actions"><h3>Documento y decisión</h3><button className="text-button" disabled={busy} onClick={()=>{if(leave())close();}}>Cerrar documento</button></div><ErrorMessage message={error}/>{message&&<p role="status" className="saved">{message}</p>}{!data&&!error&&<p role="status">Cargando documento…</p>}{error&&<button className="text-button" disabled={busy} onClick={()=>{if(leave()){setEditing(false);setError('');setRevision(v=>v+1);}}}>Actualizar documento</button>}{data&&<><p role="status"><strong>{consentStates[data.status]}</strong></p><div className="form-actions"><button className="button secondary" disabled={!ready||busy} onClick={()=>{try{frame.current?.contentWindow?.focus();frame.current?.contentWindow?.print();}catch{setError('No se pudo abrir la impresión. Prueba en un navegador de escritorio.');}}}>Imprimir consentimiento / guardar PDF</button><small>Para descargar PDF, elige “Guardar como PDF” en la ventana de impresión.</small></div><iframe ref={frame} className="prescription-frame" title="Vista previa del consentimiento" sandbox="allow-same-origin allow-modals" srcDoc={consentHtml(data.consent,data.status)} onLoad={()=>setReady(true)}/>
 {editable&&data.status!=='voided'&&!editing&&<button className="button primary" onClick={()=>{setStatus(data.status==='pending'?'accepted':'voided');setReason('');setName('');setRelationship('');setFile(null);setChecked(false);setDate(new Intl.DateTimeFormat('en-CA',{timeZone:data.consent.snapshot.organization.timezone||'America/Mexico_City',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()));setMessage('');setEditing(true);request.current=null;}}>{data.status==='pending'?'Registrar decisión':'Anular consentimiento'}</button>}
 {editing&&<form className="form" onSubmit={e=>{e.preventDefault();void save();}}><fieldset className="budget-fields" disabled={busy}><legend>Registrar decisión del consentimiento</legend><label className="field"><span>Decisión</span><select value={status} onChange={e=>{setStatus(e.target.value);setChecked(false);setFile(null);}}>{data.status==='pending'&&<><option value="accepted">Aceptación con evidencia firmada</option><option value="rejected">Rechazo</option></>}<option value="voided">Anulación</option></select></label><label className="field"><span>Fecha de la decisión</span><input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field"><span>Motivo o constancia</span><textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{status==='accepted'&&<><label className="field"><span>Nombre de quien firma</span><input required maxLength={180} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Relación con el paciente</span><input required placeholder="El propio paciente, madre, tutor…" maxLength={100} value={relationship} onChange={e=>setRelationship(e.target.value)}/></label><label className="field"><span>Evidencia firmada (PDF, JPG, PNG o WebP · máximo 5 MiB)</span><input type="file" required accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e=>{setFile(e.target.files?.[0]||null);setChecked(false);}}/></label><label className="check-field"><input type="checkbox" required checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>Revisé que el archivo firmado corresponde a este paciente y documento.</span></label><p>Se conserva el archivo aportado; el sistema no verifica la autenticidad de las firmas.</p></>}<p>El registro no se puede borrar. Una anulación conserva el documento y su evidencia; para una nueva decisión prepara otro consentimiento.</p><div className="form-actions"><button className="button primary" disabled={busy||(status==='accepted'&&(!checked||!file))} aria-busy={busy}>{busy?'Registrando…':'Guardar decisión'}</button><button type="button" className="text-button" onClick={()=>{if(leave())setEditing(false);}}>Descartar decisión</button></div></fieldset></form>}
 <h4>Historial de decisiones</h4>{!data.events.length&&<p>Aún no hay decisiones registradas.</p>}{data.events.map(e=><article key={e.id} className="clinical-entry"><strong>{consentStates[e.status]} · {e.occurred_on}</strong><p className="patient-notes">{e.reason}</p>{e.signer_name&&<p>Firmante declarado: {e.signer_name} · {e.signer_relationship}</p>}<small>Registrado por {e.author} · {new Date(e.created_at).toLocaleString('es-MX')}</small>{e.evidence&&<button className="text-button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await downloadFile(base+'/events/'+e.id+'/evidence',e.evidence!.filename);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>Descargar evidencia: {e.evidence.filename}</button>}</article>)}</>}</div>;
}

