'use client';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ArrowRight, ShieldCheck, Eye, EyeOff, LoaderCircle } from 'lucide-react';
import { api } from '../lib/api';
import { Brand, ErrorMessage, Field, Form, Mark } from './ui';
const schema=z.object({email:z.email('Introduce un correo válido.'),password:z.string().min(1,'Introduce tu contraseña.'),code:z.string().optional()});
type Values=z.infer<typeof schema>;
export function Login({onLogin}:{onLogin:()=>Promise<void>}){
 const params=new URLSearchParams(typeof window==='undefined'?'':window.location.search);
 const [mode,setMode]=useState(params.get('flow')||'login'),[error,setError]=useState(''),[message,setMessage]=useState(''),[visible,setVisible]=useState(false);
 const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(schema)});
 async function login(values:Values){setError('');try{await api('auth/login','POST',values);await onLogin();}catch(e){setError((e as Error).message);}}
 return <div className="login-layout"><aside className="login-story"><Brand/><div className="login-copy"><span className="eyebrow">CUIDAR EMPIEZA CON CONFIANZA</span><h1>Más cerca de<br/>tu práctica.<br/><em>Más cerca de ti.</em></h1><p>Un espacio para organizar tu equipo y construir una mejor experiencia odontológica.</p><div className="tooth-art"><div className="art-ring ring-one"/><div className="art-ring ring-two"/><Mark/><span className="art-dot"/></div></div><div className="login-footer"><ShieldCheck size={18}/> Tu información, en un entorno seguro.</div></aside><main className="login-main"><div className="mobile-brand"><Brand/></div><div className="login-form"><span className="eyebrow">BIENVENIDO A ALIA DENTAL</span><h2>{mode==='login'?'Tu día comienza aquí.':mode==='forgot'?'Recupera tu acceso.':mode==='invite'?'Únete a tu equipo.':'Una nueva contraseña.'}</h2><p>{mode==='login'?'Ingresa a tu espacio de trabajo.':'Sigue estos pasos para continuar de forma segura.'}</p>{message&&<div className="notice" role="status">{message}</div>}
 {mode==='login'?<form className="form" onSubmit={handleSubmit(login)}><label className="field"><span>Correo electrónico</span><input type="email" autoComplete="username" placeholder="nombre@tuclinica.com" {...register('email')}/>{errors.email&&<small className="field-error">{errors.email.message}</small>}</label><label className="field"><span>Contraseña</span><div className="password-input"><input type={visible?'text':'password'} autoComplete="current-password" {...register('password')}/><button type="button" onClick={()=>setVisible(!visible)} aria-label={visible?'Ocultar contraseña':'Mostrar contraseña'}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{errors.password&&<small className="field-error">{errors.password.message}</small>}</label><label className="field"><span>Código de seguridad <small>(si activaste MFA)</small></span><input autoComplete="one-time-code" placeholder="Código de 6 dígitos o de recuperación" {...register('code')}/></label><button type="button" className="forgot" onClick={()=>{setMode('forgot');setError('');}}>¿Olvidaste tu contraseña?</button><ErrorMessage message={error}/><button className="button primary login-button" disabled={isSubmitting}>{isSubmitting?<LoaderCircle size={18} className="spin"/>:<>Iniciar sesión<ArrowRight size={18}/></>}</button></form>:
 <Form label={mode==='forgot'?'Enviar instrucciones':mode==='invite'?'Aceptar invitación':'Actualizar contraseña'} onSubmit={async values=>{if(mode==='forgot'){const result=await api<{message:string}>('auth/forgot-password','POST',values);setMessage(result.message);}else{await api(mode==='invite'?'auth/accept-invitation':'auth/reset-password','POST',{...values,token:params.get('token')});window.history.replaceState(null,'','/');setMode('login');setMessage('Listo. Ya puedes iniciar sesión.');}}}>{mode==='forgot'?<Field label="Correo electrónico" name="email" type="email" required/>:<>{mode==='invite'&&<Field label="Nombre completo" name="name" required/>}<Field label="Nueva contraseña" name="password" type="password" required minLength={12} maxLength={128} help="Usa al menos 12 caracteres."/>{mode==='reset'&&<Field label="Código MFA o de recuperación, si está activo" name="code"/>}{mode==='invite'&&<p className="muted">Si ya tienes una cuenta, inicia sesión con el correo invitado y abre de nuevo el enlace.</p>}</>}</Form>}
 {mode!=='login'&&<button className="text-button back-login" onClick={()=>{setMode('login');setError('');setMessage('');}}>Volver a iniciar sesión</button>}<div className="login-trust"><ShieldCheck size={17}/><span>Acceso privado · Sesiones protegidas</span></div></div><footer>ALIA DENTAL <span>Una solución de Alia Soluciones</span></footer></main></div>;
}
