'use client';
import {useEffect,useState} from 'react';
import {api} from '../lib/api';
import type {PatientPage,PatientSummary} from '../lib/patients';
import {Heading,ErrorMessage} from './ui';
type Feature={id:string;label:string;description:string};
export function ModuleHub({kind,can}:{kind:'records'|'treatments'|'cash'|'reports';can:(permission:string)=>boolean}){
 const titles={records:'Expedientes',treatments:'Tratamientos',cash:'Caja',reports:'Reportes'};
 const features:Feature[]=kind==='records'?(can('clinical_records.view')?[{id:'referrals',label:'Especialistas externos',description:'Remisiones, seguimiento e informes de regreso.'},{id:'laboratories',label:'Trabajos de laboratorio',description:'Solicitud, recepción y entrega con resultados.'},{id:'clinical',label:'Historia clínica',description:'Antecedentes, condiciones y notas por cita.'},{id:'photos',label:'Fotografías clínicas',description:'Imágenes y anotaciones del paciente.'},{id:'consents',label:'Consentimientos',description:'Documentos, decisiones y evidencia.'},{id:'prescriptions',label:'Recetas',description:'Borradores y preparación para firma.'}]:[]):kind==='treatments'?[...(can('clinical_records.view')?[{id:'odontogram',label:'Odontograma',description:'Piezas, superficies y diagnósticos.'},{id:'plan',label:'Plan de tratamiento',description:'Procedimientos y seguimiento.'}]:[]),...(can('budgets.view')?[{id:'budget',label:'Presupuestos',description:'Versiones, aceptación e impresión.'}]:[])]:kind==='cash'?[...(can('payments.view')?[{id:'payments',label:'Pagos y recibos',description:'Anticipos, abonos, saldo e historial del paciente.'}]:[]),...(can('professional_shares.view')?[{id:'shares',label:'Participación del doctor',description:'Porcentaje pactado sobre el tratamiento aceptado.'}]:[])]:[];
 const [target,setTarget]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('active'),[items,setItems]=useState<PatientSummary[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const selected=features.find(f=>f.id===target)||features[0],showPatients=can('patients.view')&&features.length>0;
 useEffect(()=>{if(!showPatients)return;let live=true;const timer=setTimeout(()=>{setLoading(true);api<PatientPage>('patients?'+new URLSearchParams({q:search.trim(),status,limit:'20'}),'GET',undefined,15000).then(r=>{if(live){setItems(r.items);setError('');}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});},200);return()=>{live=false;clearTimeout(timer);};},[search,status,showPatients]);
 return <><Heading eyebrow="TU PRÁCTICA" title={titles[kind]} description={kind==='reports'?'Consultas y reportes disponibles para tu clínica.':'Accede a las herramientas disponibles desde un solo lugar.'}/>{(kind==='cash'||kind==='reports')&&can('cash_closures.view')&&<article className="panel module-card"><h2>{kind==='cash'?'Cortes y arqueos':'Reporte de caja'}</h2><p>Consulta por sucursal, responsable y periodo. Revisa cortes guardados y sus arqueos por moneda.</p><button className="button secondary" onClick={()=>{window.location.hash='cash-closures';}}>Abrir cortes y arqueos</button></article>}{(kind==='reports'||kind==='cash')&&can('patients.view')&&can('professional_shares.view')&&<article className="panel module-card"><h2>Pagos y saldo por profesional</h2><p>Movimientos por periodo y saldo actual de sus asignaciones, separados por moneda.</p><button className="button secondary" onClick={()=>{window.location.hash='professional-report';}}>Abrir reporte profesional</button></article>}{kind==='reports'&&<p className="muted">Disponibles según permisos: caja y pagos por profesional. Los reportes generales clínicos, de productividad e inventario siguen pendientes.</p>}{showPatients&&<><div className="module-features" aria-label="Herramientas disponibles">{features.map(f=><button key={f.id} className="module-card" aria-pressed={selected?.id===f.id} onClick={()=>setTarget(f.id)}><strong>{f.label}</strong><span>{f.description}</span></button>)}</div><section className="panel"><h2>Selecciona un paciente · {selected?.label}</h2><p>Se abrirá la sección correspondiente de su ficha, con los mismos datos e historial.</p><div className="patients-toolbar"><label className="field"><span>Buscar paciente para {titles[kind].toLowerCase()}</span><input maxLength={100} value={search} onChange={e=>{setSearch(e.target.value);setLoading(true);setItems([]);}} placeholder="Nombre, teléfono o expediente"/></label><label className="field"><span>Estado del paciente</span><select aria-label="Estado del paciente" value={status} onChange={e=>{setStatus(e.target.value);setItems([]);setLoading(true);}}><option value="active">Activos</option><option value="inactive">Inactivos</option><option value="all">Todos</option></select></label></div><ErrorMessage message={error}/>{loading?<p role="status">Buscando pacientes…</p>:!items.length&&!error?<p>No hay pacientes con estos filtros.</p>:<div className="patient-directory">{items.map(p=><button className="patient-directory-row" key={p.id} onClick={()=>{window.location.hash='patients/'+p.id+'/'+selected.id;}}><span className="patient-directory-name"><strong>{p.first_name} {p.last_name}</strong><small>{p.record_number} · {p.active?'Activo':'Inactivo'}</small></span><span>Abrir {selected.label.toLowerCase()}</span></button>)}</div>}<small>Hasta 20 resultados. Escribe para filtrar.</small></section></>}</>;
}
