'use client';
import { useState } from 'react';
import { Building2, MapPin, Plus } from 'lucide-react';
import type { Branch, Context } from '../lib/types';
import { api } from '../lib/api';
import { Empty, Field, Form, Heading, InlinePanel, Section } from './ui';
export function OrganizationSettings({context,refresh}:{context:Context;refresh:()=>Promise<void>}){const o=context.organization;return <><Heading eyebrow="ADMINISTRACIÓN" title="Tu organización" description="La identidad y las preferencias de tu espacio de trabajo."/><Form onSubmit={async values=>{await api('organization','PATCH',values);await refresh();}}><Section title="Identidad" description="Así conocerá tu equipo a tu organización."><div className="form-grid"><Field label="Nombre comercial" name="name" value={o.name} required/><Field label="Razón social" name="legal_name" value={o.legal_name}/><Field label="RFC" name="rfc" value={o.rfc} maxLength={13}/><Field label="Prefijo de expedientes" name="record_prefix" value={o.record_prefix} required help="De 1 a 6 letras mayúsculas. Se utilizará a partir de la fase 2."/></div></Section><Section title="Contacto" description="Información administrativa de la organización."><div className="form-grid"><Field label="Correo electrónico" name="email" type="email" value={o.email}/><Field label="Teléfono" name="phone" value={o.phone}/><div className="full-width"><Field label="Dirección" name="address" value={o.address}/></div></div></Section><Section title="Preferencias regionales" description="Una referencia consistente para tu equipo."><div className="form-grid"><label className="field"><span>Zona horaria</span><select name="timezone" defaultValue={o.timezone}>{['America/Mexico_City','America/Merida','America/Cancun','America/Tijuana','America/Hermosillo','America/Monterrey','America/New_York','Europe/Madrid'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field"><span>Moneda</span><select name="currency" defaultValue={o.currency}><option value="MXN">MXN · Peso mexicano</option><option value="USD">USD · Dólar estadounidense</option><option value="EUR">EUR · Euro</option></select></label><label className="field"><span>Configuración regional</span><select name="locale" defaultValue={o.locale}><option value="es-MX">Español · México</option><option value="en-US">Inglés · Estados Unidos</option></select></label></div></Section></Form></>;}
export function Branches({context,refresh}:{context:Context;refresh:()=>Promise<void>}){
 const [editing,setEditing]=useState<Branch|'new'|null>(null);const current=editing==='new'?null:editing;
 return <><Heading eyebrow="TU ORGANIZACIÓN" title="Sucursales" description="Un lugar para cada parte de tu práctica." action={<button className="button primary" onClick={()=>setEditing('new')}><Plus size={18}/>Nueva sucursal</button>}/>{editing&&<InlinePanel title={current?'Editar sucursal':'Nueva sucursal'} onClose={()=>setEditing(null)}><Form key={current?.id||'new'} onSubmit={async values=>{await api(current?`branches/${current.id}`:'branches',current?'PATCH':'POST',{...values,active:values.active==='true'});await refresh();setEditing(null);}}><div className="form-grid"><Field label="Nombre" name="name" value={current?.name} required/><Field label="Teléfono" name="phone" value={current?.phone}/><Field label="Dirección" name="address" value={current?.address}/><label className="field"><span>Estado</span><select name="active" defaultValue={current?.active===false?'false':'true'}><option value="true">Activa</option><option value="false">Inactiva</option></select></label></div></Form></InlinePanel>}{context.branches.length?<div className="branch-list">{context.branches.map(b=><article className="branch-row" key={b.id}><span className="branch-icon"><Building2 size={26}/></span><div><h2>{b.name} <span className={`pill ${b.active?'green':''}`}>{b.active?'Activa':'Inactiva'}</span></h2><p><MapPin size={15}/>{b.address||'Dirección pendiente de registrar'}</p>{b.phone&&<small>{b.phone}</small>}</div><button className="button secondary" onClick={()=>setEditing(b)}>Editar sucursal</button></article>)}</div>:<Empty icon={<Building2/>} title="Tu primera sucursal empieza aquí" description="Añade tu consultorio o la primera ubicación de tu clínica."/>}<p className="muted footnote">Desactivar una sucursal conserva su información y la retira del selector de trabajo.</p></>;
}
