'use client';
import {useEffect,useRef,useState} from 'react';
import {api} from '../lib/api';
import {PaymentReceipt} from './payment-receipt';
import {ErrorMessage,Section} from './ui';
const kinds={advance:'Anticipo',installment:'Abono',settlement:'Liquidación'},methods={cash:'Efectivo',card:'Tarjeta',transfer:'Transferencia',other:'Otro'};
type Payment={id:string;amount_minor:number;refunded_minor:number;currency:string;kind:keyof typeof kinds;method:keyof typeof methods;branch_name:string;reference:string;notes:string;created_at:string;author:string;version:number;void_reason:string|null;voided_at:string|null;voided_by:string|null};
type Data={agreement:{id:string;version:number;title:string;currency:string;total_minor:number;paid_minor:number;balance_minor:number;credit_minor:number}|null;items:Payment[];hasMore:boolean;branches:{id:string;name:string}[]};
const money=(n:number,currency:string)=>new Intl.NumberFormat('es-MX',{style:'currency',currency}).format(n/100);
export function PatientPayments({patientId,canCreate,canVoid,active}:{patientId:string;canCreate:boolean;canVoid:boolean;active:boolean}){
 const [receipt,setReceipt]=useState<string|null>(null);const base='patients/'+patientId+'/payments';const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[voiding,setVoiding]=useState<Payment|null>(null);
 const [agreementId,setAgreementId]=useState(''),[amount,setAmount]=useState(''),[kind,setKind]=useState<keyof typeof kinds>('advance'),[method,setMethod]=useState<keyof typeof methods>('cash'),[branch,setBranch]=useState(''),[reference,setReference]=useState(''),[notes,setNotes]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const request=useRef<{body:string;id:string}|null>(null),dirty=editing||Boolean(voiding);
 useEffect(()=>{let live=true;api<Data>(base+'?page='+page,'GET',undefined,15000).then(r=>{if(live){setData(r);setError('');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[base,page,revision]);
 useEffect(()=>{const changed=()=>{if(!dirty)setRevision(v=>v+1);};window.addEventListener('alia-budget-changed',changed);return()=>window.removeEventListener('alia-budget-changed',changed);},[dirty]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function refresh(){if(dirty&&!window.confirm('¿Descartar la captura pendiente y actualizar el saldo?'))return;setEditing(false);setVoiding(null);setReceipt(null);setData(null);setRevision(v=>v+1);}
 function key(payload:unknown){const body=JSON.stringify(payload);if(request.current?.body!==body)request.current={body,id:crypto.randomUUID()};return request.current.id;}
 function saved(text:string){setEditing(false);setVoiding(null);setReceipt(null);setData(null);setPage(1);setRevision(v=>v+1);setMessage(text);}
 async function pay(){setBusy(true);setError('');try{if(!/^\d{1,11}(\.\d{1,2})?$/.test(amount))throw new Error('Escribe un importe positivo con hasta dos decimales y punto decimal.');const amount_minor=Math.round(Number(amount)*100);if(amount_minor<=0||!data?.agreement||amount_minor>data.agreement.balance_minor)throw new Error('El importe debe ser mayor que cero y no superar el saldo.');const payload={acceptance_id:agreementId,amount_minor,kind,method,branch_id:branch,reference,notes};await api(base,'POST',{...payload,request_id:key(payload)},15000);saved('Pago registrado. El movimiento se conserva en el historial.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function cancel(){if(!voiding)return;setBusy(true);setError('');try{const payload={paymentId:voiding.id,reason,reviewed:confirmed};await api(base+'/'+voiding.id+'/void','POST',{request_id:key(payload),reason,reviewed:confirmed},15000);saved('Registro anulado. El original y el motivo permanecen en el historial.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const a=data?.agreement;
 return <Section title="Pagos y saldo" description="Registra dinero recibido contra el presupuesto aceptado. Esta operación no cobra tarjetas ni realiza transferencias."><div className="consent-detail"><ErrorMessage message={error}/>{message&&<p role="status" className="saved">{message}</p>}<button className="text-button" disabled={busy} onClick={refresh}>Actualizar pagos y saldo</button>{!data&&!error&&<p role="status">Cargando pagos…</p>}{data&&<>{a?<><h3>{a.title} · Acuerdo versión {a.version}</h3><div className="payment-summary"><p>Total acordado<strong>{money(a.total_minor,a.currency)} {a.currency}</strong></p><p>Pagos vigentes<strong>{money(a.paid_minor,a.currency)}</strong></p><p>Saldo pendiente<strong>{money(a.balance_minor,a.currency)}</strong></p></div>{a.credit_minor>0&&<p className="saved">Saldo a favor: {money(a.credit_minor,a.currency)} {a.currency}</p>}{a.balance_minor===0&&<p className="saved">Sin saldo pendiente en este acuerdo.</p>}{canCreate&&active&&!dirty&&!receipt&&a.balance_minor>0&&<button className="button primary" disabled={busy} onClick={()=>{setAgreementId(a.id);setAmount('');setKind(a.paid_minor?'installment':'advance');setMethod('cash');setBranch(data.branches.length===1?data.branches[0].id:'');setReference('');setNotes('');setMessage('');request.current=null;setEditing(true);}}>Registrar pago recibido</button>}</>:<p>Primero registra la aceptación de un presupuesto. Después podrás capturar anticipos y abonos.</p>}
 {editing&&a&&<form className="form panel" onSubmit={e=>{e.preventDefault();void pay();}}><fieldset className="budget-fields" disabled={busy}><legend>Nuevo pago recibido · {a.currency}</legend><label className="field"><span>Tipo de pago</span><select aria-label="Tipo de pago" value={kind} onChange={e=>{const k=e.target.value as keyof typeof kinds;setKind(k);if(k==='settlement')setAmount((a.balance_minor/100).toFixed(2));}}>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field"><span>Importe recibido ({a.currency})</span><input inputMode="decimal" required maxLength={14} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field"><span>Método de pago</span><select aria-label="Método de pago" value={method} onChange={e=>setMethod(e.target.value as keyof typeof methods)}>{Object.entries(methods).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field"><span>Sucursal de cobro</span><select aria-label="Sucursal de cobro" required value={branch} onChange={e=>setBranch(e.target.value)}><option value="">Selecciona la sucursal</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="field"><span>Referencia del pago (opcional)</span><input maxLength={160} value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="field"><span>Observaciones del pago</span><textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><p>Captura solo dinero ya recibido. Se registra la fecha y hora actuales. No incluyas números completos de tarjeta ni códigos de seguridad.</p><div className="form-actions"><button className="button primary" aria-busy={busy}>{busy?'Registrando…':'Guardar pago recibido'}</button><button type="button" className="text-button" onClick={()=>{if(window.confirm('¿Descartar este pago sin guardar?'))setEditing(false);}}>Descartar pago</button></div></fieldset></form>}
 {voiding&&<form className="form panel" onSubmit={e=>{e.preventDefault();void cancel();}}><fieldset className="budget-fields" disabled={busy}><legend>Anular registro de {money(voiding.amount_minor,voiding.currency)}</legend><p>Solo para una captura errónea. El saldo se recalculará y el original seguirá visible. Esta acción no devuelve dinero ni sustituye una devolución real.</p><label className="field"><span>Motivo de anulación del pago</span><textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="check-field"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>Confirmo que corrijo un registro erróneo y que no estoy registrando una devolución.</span></label><div className="form-actions"><button className="button primary" disabled={!confirmed||busy} aria-busy={busy}>Confirmar anulación del registro</button><button type="button" className="text-button" onClick={()=>{if(window.confirm('¿Descartar la anulación sin registrar?'))setVoiding(null);}}>Conservar pago</button></div></fieldset></form>}
 {receipt&&<PaymentReceipt key={receipt} patientId={patientId} paymentId={receipt} close={()=>setReceipt(null)}/>}<h3>Historial de pagos</h3>{!data.items.length&&<p>No hay movimientos registrados.</p>}{data.items.map(p=><article key={p.id} className="clinical-entry"><strong>{kinds[p.kind]} · {money(p.amount_minor,p.currency)} {p.currency} · {p.voided_at?'Anulado':'Vigente'}</strong><p>{methods[p.method]} · {p.branch_name} · Acuerdo versión {p.version}</p><p>Folio: {p.id}</p>{p.refunded_minor>0&&<p>Devuelto: {money(p.refunded_minor,p.currency)} {p.currency}</p>}{p.reference&&<p>Referencia: {p.reference}</p>}{p.notes&&<p className="patient-notes">{p.notes}</p>}<button className="text-button" disabled={busy||dirty||Boolean(receipt)} onClick={()=>setReceipt(p.id)}>Ver recibo</button><small>Registrado por {p.author} · {new Date(p.created_at).toLocaleString('es-MX')}</small>{p.voided_at?<p className="patient-notes">Anulado por {p.voided_by} · {new Date(p.voided_at).toLocaleString('es-MX')}<br/>Motivo: {p.void_reason}</p>:canVoid&&!p.refunded_minor&&!dirty&&!receipt&&<button className="text-button" disabled={busy} onClick={()=>{setVoiding(p);setReason('');setConfirmed(false);setMessage('');request.current=null;}}>Anular registro erróneo</button>}</article>)}<div className="form-actions">{page>1&&<button className="text-button" disabled={busy||dirty||Boolean(receipt)} onClick={()=>{setData(null);setPage(p=>p-1);}}>Pagos más recientes</button>}{data.hasMore&&<button className="text-button" disabled={busy||dirty||Boolean(receipt)} onClick={()=>{setData(null);setPage(p=>p+1);}}>Pagos anteriores</button>}</div></>}</div></Section>;
}


