'use client';
import { useEffect,useRef,useState } from 'react';
import { PhotoEditor } from './photo-editor';
import { api,downloadFile } from '../lib/api';
import { ErrorMessage,Section } from './ui';
type Attachment={id:string;filename:string;display_name?:string;media_type:string;byte_size:number;created_at:string};
const maxBytes=10*1024*1024;
function encode(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('No se pudo leer el archivo. Selecciónalo de nuevo.'));reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.readAsDataURL(file);});}
export function PatientAttachments({patientId,editable,active,clinical=false}:{patientId:string;editable:boolean;active:boolean;clinical?:boolean}){
 const [displayName,setDisplayName]=useState('');
 const [editingPhoto,setEditingPhoto]=useState<Attachment|null>(null);
 const [items,setItems]=useState<Attachment[]>([]),[page,setPage]=useState(1),[more,setMore]=useState(false),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[listError,setListError]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[downloading,setDownloading]=useState<string|null>(null),[selected,setSelected]=useState<{file:File;requestId:string}|null>(null);
 const picker=useRef<HTMLInputElement>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{let live=true;setLoading(true);setListError('');api<{items:Attachment[];hasMore:boolean}>(`patients/${patientId}/attachments?page=${page}&clinical=${clinical}`).then(r=>{if(live){setItems(r.items);setMore(r.hasMore);}}).catch(e=>{if(live)setListError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[patientId,page,revision,clinical]);
 async function upload(){
  if(!selected||busy)return;setBusy(true);setError('');setMessage('');
  try{const file=selected.file,extension=file.name.split('.').pop()?.toLowerCase();const media=extension==='png'?'image/png':extension==='jpg'||extension==='jpeg'?'image/jpeg':extension==='webp'?'image/webp':extension==='pdf'?'application/pdf':'';
   if(!media||(clinical&&media==='application/pdf')||!file.size||file.size>maxBytes)throw new Error(clinical?'Selecciona una fotografía PNG, JPEG o WebP de hasta 10 MiB.':'Selecciona un PNG, JPEG, WebP o PDF de hasta 10 MiB, que no esté vacío.');
   const content=await encode(file);if(!mounted.current)return;
   await api(`patients/${patientId}/attachments`,'POST',{request_id:selected.requestId,clinical,display_name:displayName.trim(),filename:file.name,media_type:media,content_base64:content});
   if(mounted.current){setSelected(null);setDisplayName('');if(picker.current)picker.current.value='';setPage(1);setRevision(v=>v+1);setMessage('Archivo guardado correctamente.');}
  }catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setBusy(false);}
 }
 return <Section title={clinical?"Fotografías clínicas":"Archivos del paciente"} description={clinical?"Imágenes PNG, JPEG o WebP para documentar observaciones con flechas, círculos y notas. Hasta 10 MiB.":"Adjuntos administrativos privados. PNG, JPEG, WebP o PDF, hasta 10 MiB por archivo."}>{editingPhoto&&<PhotoEditor key={editingPhoto.id} patientId={patientId} photo={editingPhoto} onRename={name=>{setEditingPhoto(p=>p?{...p,display_name:name}:p);setRevision(v=>v+1);}} editable={editable&&active} close={()=>setEditingPhoto(null)}/>}
 {editable&&active&&<div className="form"><label className="field"><span>{clinical?'Seleccionar fotografía':'Seleccionar archivo'}</span><input ref={picker} aria-label={clinical?'Seleccionar fotografía':'Seleccionar archivo'} type="file" accept={clinical?'.png,.jpg,.jpeg,.webp':'.png,.jpg,.jpeg,.webp,.pdf'} disabled={busy} onChange={e=>{const file=e.target.files?.[0];setSelected(file?{file,requestId:crypto.randomUUID()}:null);setError('');setMessage('');}}/></label>{selected&&<label className="field"><span>Nombre del documento (opcional)</span><input aria-label="Nombre del documento" maxLength={100} value={displayName} disabled={busy} onChange={e=>setDisplayName(e.target.value)} placeholder="Ej. Vista frontal · primera consulta"/></label>}{selected&&<p style={{overflowWrap:'anywhere'}}>{selected.file.name} · {(selected.file.size/1024).toFixed(1)} KiB</p>}<div className="form-actions"><button type="button" className="button primary" disabled={!selected||busy} onClick={upload}>{busy?'Guardando archivo…':clinical?'Subir fotografía':'Subir archivo'}</button>{selected&&!busy&&<button type="button" className="text-button" onClick={()=>{setSelected(null);if(picker.current)picker.current.value='';setError('');}}>Quitar selección</button>}</div></div>}
 {editable&&!active&&<p>La ficha está inactiva. Puedes descargar sus archivos existentes.</p>}<ErrorMessage message={error}/>{message&&<p role="status">{message}</p>}<ErrorMessage message={listError}/>
 {loading?<p role="status">Cargando archivos…</p>:!listError&&!items.length?<p>Aún no hay archivos en esta ficha.</p>:!listError&&items.map(item=><div className="invitation-row" key={item.id}><div style={{minWidth:0,overflowWrap:'anywhere'}}><strong>{item.display_name||(clinical?'Fotografía clínica':item.filename)}</strong><p>{(item.byte_size/1024).toFixed(1)} KiB · {new Date(item.created_at).toLocaleDateString('es-MX')}</p></div><div className="form-actions">{clinical&&<button type="button" className="button secondary" onClick={()=>setEditingPhoto(item)}>Abrir anotaciones</button>}<button type="button" className="text-button" disabled={downloading!==null} onClick={async()=>{setDownloading(item.id);setError('');try{await downloadFile(`patients/${patientId}/attachments/${item.id}/content`,item.filename);}catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setDownloading(null);}}}>{downloading===item.id?'Descargando…':'Descargar'}</button></div></div>)}
 <div className="form-actions"><button type="button" className="text-button" disabled={loading} onClick={()=>setRevision(v=>v+1)}>Actualizar archivos</button>{(page>1||more)&&<><button type="button" className="button secondary" disabled={page===1||loading} onClick={()=>setPage(v=>v-1)}>Archivos anteriores</button><span>Página {page}</span><button type="button" className="button secondary" disabled={!more||loading} onClick={()=>setPage(v=>v+1)}>Más archivos</button></>}</div>
 </Section>;
}
