'use client';
import { useEffect,useState } from 'react';
import { api,privateBlob } from '../lib/api';
import { ErrorMessage } from './ui';
type ProfilePhoto={attachment_id:string|null;version:number;media_type?:string};
export function PatientProfilePhoto({patientId,initials,editable}:{patientId:string;initials:string;editable:boolean}){
 const [photo,setPhoto]=useState<ProfilePhoto|null>(null),[url,setUrl]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[selected,setSelected]=useState<{file:File;request:string;uploaded?:string}|null>(null),[preview,setPreview]=useState('');
 const base='patients/'+patientId+'/attachments';
 useEffect(()=>{let live=true,objectUrl='';setError('');api<ProfilePhoto>(base+'/profile-photo','GET',undefined,15000).then(async p=>{if(!live)return;setPhoto(p);if(!p.attachment_id){setUrl('');return;}const blob=await privateBlob(base+'/'+p.attachment_id+'/content');if(!live)return;objectUrl=URL.createObjectURL(new Blob([blob],{type:p.media_type}));setUrl(objectUrl);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[base,revision]);
 useEffect(()=>{if(!selected){setPreview('');return;}const next=URL.createObjectURL(selected.file);setPreview(next);return()=>URL.revokeObjectURL(next);},[selected]);
 async function save(remove=false){if(!photo||busy)return;setBusy(true);setError('');setMessage('');try{let id:string|null=null;if(!remove){if(!selected)return;id=selected.uploaded||null;if(!id){const ext=selected.file.name.split('.').pop()?.toLowerCase(),media=ext==='png'?'image/png':ext==='webp'?'image/webp':ext==='jpg'||ext==='jpeg'?'image/jpeg':'';if(!media||!selected.file.size||selected.file.size>10*1024*1024)throw new Error('Selecciona PNG, JPEG o WebP de hasta 10 MiB.');const content=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('No se pudo leer la fotografía.'));reader.readAsDataURL(selected.file);});const uploaded=await api<{id:string}>(base,'POST',{request_id:selected.request,filename:selected.file.name,display_name:'Fotografía de perfil',media_type:media,content_base64:content},15000);id=uploaded.id;setSelected({...selected,uploaded:id});}}
 await api(base+'/profile-photo','PATCH',{attachment_id:id,version:photo.version},15000);setSelected(null);setRevision(v=>v+1);setMessage(remove?'Foto de perfil retirada.':'Foto de perfil guardada.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="profile-photo"><span className="patient-avatar large">{url?<img src={url} alt="Foto de perfil del paciente" onError={()=>{setUrl('');setError('No se pudo mostrar la fotografía.');}}/>:initials}</span>{editable&&<details><summary>{photo?.attachment_id?'Cambiar foto de perfil':'Añadir foto de perfil'}</summary><p>PNG, JPEG o WebP · hasta 10 MiB</p><label className="field"><span>Fotografía de perfil</span><input key={revision} aria-label="Fotografía de perfil" type="file" accept=".png,.jpg,.jpeg,.webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];setSelected(file?{file,request:crypto.randomUUID()}:null);setError('');setMessage('');}}/></label>{preview&&<img className="profile-preview" src={preview} alt="Vista previa de la nueva foto"/>}<div className="form-actions"><button className="button primary" aria-busy={busy} disabled={!selected||!photo||busy} onClick={()=>void save()}>Guardar foto de perfil</button>{selected&&<button className="text-button" disabled={busy} onClick={()=>setSelected(null)}>Cancelar selección</button>}{photo?.attachment_id&&<button className="text-button" disabled={busy} onClick={()=>void save(true)}>Quitar foto de perfil</button>}</div><small>Quitar la foto restaura las iniciales. El archivo original se conserva en los adjuntos privados.</small></details>}<ErrorMessage message={error}/>{error&&<button className="text-button" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Actualizar foto de perfil</button>}{message&&<p role="status">{message}</p>}</div>;
}
