'use client';
import { useEffect,useState } from 'react';
import { api } from '../lib/api';
import {BudgetReview} from './budget-review';
import { ErrorMessage,Section } from './ui';
type Line={plan_item_id:string;title:string;tooth:string;quantity:number;unit_minor:number|null;discount_minor:number;total_minor?:number};
type Budget={version:number;plan_version:number;currency:string;title:string;items:Line[];total_minor:number};
type Data={accepted_version?:number|null;budget:Budget|null;latest:number;history:{version:number;title:string;author:string;created_at:string}[]};
type Draft={request_id:string;version:number;plan_version:number;currency:string;title:string;items:(Omit<Line,'quantity'|'unit_minor'|'discount_minor'> & {quantity:string;price:string;discount:string})[]};
const minor=(text:string)=>/^\d{1,9}(\.\d{1,2})?$/.test(text)?Math.round(Number(text)*100):NaN;
export function PatientBudget({patientId,editable}:{patientId:string;editable:boolean}){
 const [review,setReview]=useState<number|null>(null);const base='patients/'+patientId+'/budget';const [data,setData]=useState<Data|null>(null),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let live=true;api<Data>(base,'GET',undefined,15000).then(r=>{if(live)setData(r);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[base]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(draft){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[draft]);
 const money=(n:number,currency:string)=>new Intl.NumberFormat('es-MX',{style:'currency',currency}).format(n/100);
 async function load(version?:number){if(draft&&!window.confirm('¿Descartar el borrador del presupuesto?'))return;setBusy(true);setError('');try{setData(await api<Data>(base+(version?'?version='+version:''),'GET',undefined,15000));setDraft(null);setMessage('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function begin(source:{plan_version:number;currency:string;items:Line[]},title='Presupuesto de tratamiento'){
  setDraft({request_id:crypto.randomUUID(),version:data!.latest,plan_version:source.plan_version,currency:source.currency,title,items:source.items.map(i=>({...i,quantity:String(i.quantity),price:i.unit_minor===null?'':(i.unit_minor/100).toFixed(2),discount:(i.discount_minor/100).toFixed(2)}))});setMessage('');setError('');
 }
 async function prepare(){setBusy(true);setError('');try{const source=await api<{plan_version:number;currency:string;items:Line[]}>(base+'/source','GET',undefined,15000);if(!source.items.length)throw new Error('Guarda primero un plan de tratamiento con procedimientos sin cancelar.');begin(source);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function update(next:Draft){setDraft({...next,request_id:crypto.randomUUID()});setMessage('');}
 async function save(){if(!draft)return;setBusy(true);setError('');try{
  const items=draft.items.map(i=>({plan_item_id:i.plan_item_id,quantity:Number(i.quantity),unit_minor:minor(i.price),discount_minor:minor(i.discount)}));
  if(!items.length)throw new Error('Incluye al menos un procedimiento.');
  if(items.some(i=>!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>100||!Number.isFinite(i.unit_minor)||i.unit_minor>100000000||!Number.isFinite(i.discount_minor)||i.discount_minor>i.quantity*i.unit_minor))throw new Error('Revisa cantidades (1–100), precios (máximo 1,000,000) y descuentos. Usa hasta dos decimales y punto decimal.');
  const result=await api<{version:number}>(base,'POST',{...draft,items},15000);
  const savedItems=items.map((i,index)=>({...i,title:draft.items[index].title,tooth:draft.items[index].tooth,total_minor:i.quantity*i.unit_minor-i.discount_minor}));
  const budget={version:result.version,plan_version:draft.plan_version,currency:draft.currency,title:draft.title.trim(),items:savedItems,total_minor:savedItems.reduce((n,i)=>n+i.total_minor,0)};
  setData({accepted_version:data?.accepted_version,budget,latest:result.version,history:[{version:result.version,title:budget.title,author:'Esta sesión',created_at:new Date().toISOString()},...data!.history.filter(h=>h.version!==result.version)].slice(0,25)});setDraft(null);setMessage('Presupuesto guardado.');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const b=data?.budget;
 const draftTotals=draft?.items.map(i=>{const amount=Number(i.quantity)*minor(i.price)-minor(i.discount);return i.quantity&&Number.isInteger(Number(i.quantity))&&Number(i.quantity)>0&&amount>=0?amount:NaN;})||[];
 const draftTotal=draftTotals.length&&draftTotals.every(Number.isFinite)?draftTotals.reduce((a,b)=>a+b,0):null;
 return <Section title="Presupuestos" description="Prepara el desglose desde un plan guardado y conserva cada versión."><ErrorMessage message={error}/>{!data&&!error&&<p role="status">Cargando presupuesto…</p>}{!data&&error&&<button className="text-button" onClick={()=>void load()}>Reintentar presupuesto</button>}{data&&<>
 {!draft&&!review&&editable&&<div className="form-actions odonto-actions"><button className="button secondary" disabled={busy} onClick={()=>void prepare()}>Preparar desde el plan actual</button>{b&&b.version===data.latest&&<button className="text-button" disabled={busy} onClick={()=>begin(b,b.title)}>{data.accepted_version===b.version?'Crear nueva propuesta':'Editar presupuesto'}</button>}</div>}
 {draft?<form className="form panel" onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} className="budget-fields"><legend>Nuevo borrador · Plan versión {draft.plan_version} · {draft.currency}</legend><label className="field"><span>Nombre del presupuesto</span><input required maxLength={120} value={draft.title} onChange={e=>update({...draft,title:e.target.value})}/></label><p>Revisa los precios sugeridos del catálogo. Los procedimientos sin precio requieren captura manual. El descuento corresponde al total de cada renglón.</p>
 {draft.items.map((item,index)=><article className="treatment-item budget-line" key={item.plan_item_id}><h3>{index+1}. {item.title}</h3><small>{item.tooth?'Pieza '+item.tooth:'Procedimiento general'}</small><div className="form-grid">{(['quantity','price','discount'] as const).map((field)=><label className="field" key={field}><span>{field==='quantity'?'Cantidad':field==='price'?'Precio unitario ('+draft.currency+')':'Descuento del renglón ('+draft.currency+')'}</span><input aria-label={(field==='quantity'?'Cantidad':field==='price'?'Precio unitario':'Descuento')+' del procedimiento '+(index+1)} inputMode={field==='quantity'?'numeric':'decimal'} required value={item[field]} maxLength={12} onChange={e=>update({...draft,items:draft.items.map((i,j)=>j===index?{...i,[field]:e.target.value}:i)})}/></label>)}</div><button type="button" className="text-button" aria-label={'Retirar del presupuesto '+(index+1)} onClick={()=>update({...draft,items:draft.items.filter((_,j)=>j!==index)})}>Retirar del presupuesto</button></article>)}
 <p className="budget-total" role="status">Total del borrador: <strong>{draftTotal===null?'Completa los importes':money(draftTotal,draft.currency)}</strong></p><div className="form-actions odonto-actions"><button className="button primary" aria-busy={busy}>Guardar presupuesto</button><button type="button" className="text-button" onClick={()=>{if(window.confirm('¿Descartar el borrador del presupuesto?'))setDraft(null);}}>Descartar borrador</button></div></fieldset></form>:b?<><h3>{b.title}</h3><p>Versión {b.version} · Plan de origen: versión {b.plan_version} · {b.currency}</p>{b.items.map(i=><article className="treatment-item" key={i.plan_item_id}><div><strong>{i.title}</strong><p>{i.tooth?'Pieza '+i.tooth+' · ':''}{i.quantity} × {money(i.unit_minor!,b.currency)} · Descuento: {money(i.discount_minor,b.currency)}</p></div><strong>{money(i.total_minor!,b.currency)}</strong></article>)}<p className="budget-total">Total del presupuesto: <strong>{money(b.total_minor,b.currency)}</strong></p>{b.version!==data.latest&&<p>Versión histórica de solo lectura.</p>}</>:<p>Aún no hay un presupuesto guardado para este paciente.</p>}
 {!draft&&b&&!review&&<button className="button secondary" disabled={busy} onClick={()=>setReview(b.version)}>Ver documento y aceptación</button>}{review&&<BudgetReview key={review} patientId={patientId} version={review} editable={editable} onSaved={()=>{void load();window.dispatchEvent(new Event('alia-budget-changed'));}} close={()=>setReview(null)}/ >}{data.accepted_version&&<p>Acuerdo vigente: versión {data.accepted_version}. Las nuevas propuestas no lo sustituyen hasta registrar su aceptación. <button className="text-button" disabled={busy||Boolean(review)} onClick={()=>void load(data.accepted_version!)}>Ver versión acordada</button></p>}{message&&<p role="status" className="saved">{message}</p>}<details><summary>Historial de presupuestos</summary><label className="field"><span>Versión del presupuesto</span><select aria-label="Versión del presupuesto" disabled={busy||Boolean(review)} value={b?.version||0} onChange={e=>void load(Number(e.target.value))}>{!b&&<option value={0}>Sin registros</option>}{b&&!data.history.some(h=>h.version===b.version)&&<option value={b.version}>Versión {b.version} · {b.title}</option>}{data.history.map(h=><option key={h.version} value={h.version}>Versión {h.version} · {h.title} · {h.author} · {new Date(h.created_at).toLocaleString('es-MX')}</option>)}</select></label><button className="text-button" disabled={busy||Boolean(review)} onClick={()=>void load()}>Cargar presupuesto actual</button></details><p className="muted">Últimas 25 versiones. Guardar no registra pagos ni aceptación del paciente. Los importes del presupuesto no cambian al modificar el catálogo.</p>
 </>}</Section>;
}



