'use client';
import { Fragment,useLayoutEffect,useEffect,useId,useRef,useState } from 'react';
import type { PointerEvent,KeyboardEvent } from 'react';
import { MousePointer2,MoveUpRight,Circle,StickyNote,Undo2,Redo2,Trash2,Copy,Hand,Save } from 'lucide-react';
import { api,privateBlob } from '../lib/api';
import { ErrorMessage,InlinePanel } from './ui';
type Mark={id:string;kind:'arrow'|'circle'|'text';x:number;y:number;x2:number;y2:number;text:string;tooth:string;label?:{x:number;y:number}};
type Version={version:number;marks:Mark[];latest:number;history:{version:number;created_at:string;author:string}[]};
type Tool=Mark['kind']|'select'|'pan';
type Gesture={id:number;mode:'move'|'start'|'end'|'pan'|'label';before:Mark[];mark?:Mark;x:number;y:number;left:number;top:number;clearOnTap?:boolean;moved?:boolean};
const names={arrow:'Flecha',circle:'Círculo',text:'Nota'};
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
export function PhotoEditor({patientId,photo,editable,close,onRename}:{patientId:string;photo:{id:string;filename:string;display_name?:string;media_type:string};onRename:(name:string)=>void;editable:boolean;close:()=>void}){
 const base=`patients/${patientId}/photos/${photo.id}/annotations`,marker=useId().replace(/:/g,''),svg=useRef<SVGSVGElement>(null),viewport=useRef<HTMLDivElement>(null),gesture=useRef<Gesture|null>(null),current=useRef<Mark[]>([]);
 const touches=useRef(new Map<number,{x:number;y:number}>()),pinch=useRef<{distance:number;zoom:number;x:number;y:number}|null>(null),pinching=useRef(false),pendingScroll=useRef<{left:number;top:number}|null>(null),touchBefore=useRef<{marks:Mark[];past:Mark[][];future:Mark[][];selected:string|null;text:string;tooth:string}|null>(null);
 const [fullComments,setFullComments]=useState(false);
 const [name,setName]=useState(photo.display_name||''),[naming,setNaming]=useState(false),[nameBusy,setNameBusy]=useState(false),[nameError,setNameError]=useState('');
 const [canvasWidth,setCanvasWidth]=useState(1000);
 const [url,setUrl]=useState(''),[ratio,setRatio]=useState(1),[ready,setReady]=useState(false),[data,setData]=useState<Version|null>(null),[marks,setMarks]=useState<Mark[]>([]),[past,setPast]=useState<Mark[][]>([]),[future,setFuture]=useState<Mark[][]>([]),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[savedVersion,setSavedVersion]=useState<number|null>(null),[message,setMessage]=useState(''),[tool,setTool]=useState<Tool>('select'),[text,setText]=useState(''),[tooth,setTooth]=useState(''),[point,setPoint]=useState<{x:number;y:number}|null>(null),[zoom,setZoom]=useState(1),[visible,setVisible]=useState(true),[comments,setComments]=useState(true);
 useEffect(()=>{const el=svg.current;if(!el)return;const observer=new ResizeObserver(()=>setCanvasWidth(el.getBoundingClientRect().width||1000));observer.observe(el);return()=>observer.disconnect();},[ready]);
 const picked=marks.find(m=>m.id===selected),h=1000*ratio,canEdit=!!(editable&&data&&data.version===data.latest&&!busy&&ready),dirty=!!data&&JSON.stringify(marks)!==JSON.stringify(data.marks),draft=!!picked&&(text!==picked.text||tooth!==picked.tooth),unsaved=dirty||draft;
 useLayoutEffect(()=>{if(pendingScroll.current&&viewport.current){viewport.current.scrollLeft=pendingScroll.current.left;viewport.current.scrollTop=pendingScroll.current.top;pendingScroll.current=null;}},[zoom]);
 function compact(m:Mark){return canvasWidth/zoom<500&&!fullComments&&m.id!==selected;}
 function replace(next:Mark[]){current.current=next;setMarks(next);}
 function commit(next:Mark[]){if(JSON.stringify(next)===JSON.stringify(current.current))return;const before=current.current;setPast(p=>[...p.slice(-49),before]);setFuture([]);replace(next);setMessage('Cambios sin guardar');}
 function choose(m?:Mark){setSelected(m?.id||null);setText(m?.text||'');setTooth(m?.tooth||'');setPoint(null);}
 function leaveDraft(){return !draft||window.confirm('Hay un comentario sin aplicar. ¿Descartarlo?');}
 function clearSelection(){if(draft&&picked){if(tooth&&!/^([1-4][1-8]|[5-8][1-5])$/.test(tooth)){setError('Corrige la pieza dental antes de salir de la anotación.');return;}commit(marks.map(m=>m.id===picked.id?{...m,text:text.trim(),tooth}:m));}choose();}
 function select(m:Mark){if(!leaveDraft())return;choose(m);setTool('select');setVisible(true);}
 function history(direction:'undo'|'redo'){
  if(!canEdit||!leaveDraft())return;if(point){setPoint(null);return;}
  const source=direction==='undo'?past:future;if(!source.length)return;const next=source[source.length-1],before=current.current;
  if(direction==='undo'){setPast(source.slice(0,-1));setFuture(f=>[...f,before]);}else{setFuture(source.slice(0,-1));setPast(p=>[...p,before]);}replace(next);choose(next.find(m=>m.id===selected));setMessage(direction==='undo'?'Cambio deshecho':'Cambio rehecho');
 }
 function remove(){if(!canEdit||!picked)return;commit(marks.filter(m=>m.id!==picked.id));choose();setMessage('Anotación eliminada. Puedes recuperarla con Deshacer.');}
 function apply(){if(!picked||!canEdit)return;if(tooth&&!/^([1-4][1-8]|[5-8][1-5])$/.test(tooth)){setError('Selecciona una pieza FDI válida (11–18, 21–28, 31–38, 41–48, 51–55, 61–65, 71–75 o 81–85).');return;}const next={...picked,text:text.trim(),tooth};commit(marks.map(m=>m.id===picked.id?next:m));choose(next);setError('');setMessage('Comentario aplicado. Guarda los cambios para conservarlo.');}
 useEffect(()=>{let live=true,objectUrl='';Promise.all([privateBlob(`patients/${patientId}/attachments/${photo.id}/content`),api<Version>(base,'GET',undefined,15000)]).then(([blob,version])=>{if(!live)return;objectUrl=URL.createObjectURL(new Blob([blob],{type:photo.media_type}));setUrl(objectUrl);setData(version);current.current=version.marks;setMarks(version.marks);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[base,patientId,photo.id,photo.media_type]);
 useEffect(()=>{const prevent=(e:BeforeUnloadEvent)=>{if(unsaved){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[unsaved]);
 async function load(version?:number){if(unsaved&&!window.confirm('Hay cambios sin guardar. ¿Descartarlos para cambiar de versión?'))return;setBusy(true);setError('');try{const next=await api<Version>(base+(version?`?version=${version}`:''));setData(next);replace(next.marks);setPast([]);setFuture([]);choose();setMessage('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function position(e:PointerEvent<SVGSVGElement>){const rect=e.currentTarget.getBoundingClientRect();return {x:clamp((e.clientX-rect.left)/rect.width),y:clamp((e.clientY-rect.top)/rect.height)};}
 function labelBox(m:Mark){const scale=1000/canvasWidth,w=Math.min(1000,(compact(m)?95:220)*scale),height=compact(m)?32*scale:Math.min(h,(36+18*Math.min(4,Math.max(1,Math.ceil((m.id===selected?text:m.text).length/27))))*scale);return {x:Math.max(0,Math.min(1000-w,(m.label?.x??m.x)*1000)),y:Math.max(0,Math.min(h-height,m.label?m.label.y*h:m.kind==='text'?m.y*h:m.y*h-height-22*scale)),w,height};}
 function down(e:PointerEvent<SVGSVGElement>){
  if(e.pointerType==='touch'){
   e.currentTarget.setPointerCapture(e.pointerId);
   if(!touches.current.size)touchBefore.current={marks:current.current,past,future,selected,text,tooth};
   touches.current.set(e.pointerId,{x:e.clientX,y:e.clientY});
   if(touches.current.size>=2){const pts=[...touches.current.values()],rect=viewport.current!.getBoundingClientRect(),mid={x:(pts[0].x+pts[1].x)/2-rect.left,y:(pts[0].y+pts[1].y)/2-rect.top};
    if(!pinching.current){const before=touchBefore.current;if(before){replace(before.marks);setPast(before.past);setFuture(before.future);setSelected(before.selected);setText(before.text);setTooth(before.tooth);}gesture.current=null;setPoint(null);pinching.current=true;pinch.current={distance:Math.max(1,Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y)),zoom,x:viewport.current!.scrollLeft+mid.x,y:viewport.current!.scrollTop+mid.y};}return;
   }
  }
  if(e.button!==0||gesture.current||pinching.current)return;
  if(tool==='pan'||(e.pointerType==='touch'&&(tool==='select'||!canEdit)&&!(e.target as Element).closest('[data-mark]'))){e.currentTarget.setPointerCapture(e.pointerId);gesture.current={id:e.pointerId,mode:'pan',before:marks,x:e.clientX,y:e.clientY,left:viewport.current?.scrollLeft||0,top:viewport.current?.scrollTop||0,clearOnTap:!(e.target as Element).closest('[data-mark]')};return;}
  if(!visible)return;if(!canEdit){if(!busy){const id=(e.target as Element).closest('[data-mark]')?.getAttribute('data-mark'),mark=marks.find(m=>m.id===id);if(mark)select(mark);else clearSelection();}return;}const p=position(e);
  if(tool!=='select'){
   if(marks.length>=100){setError('Máximo 100 anotaciones por versión.');return;}
   if(tool!=='text'&&!point){setPoint(p);return;}
   const start=point||p,m:Mark={id:crypto.randomUUID(),kind:tool,x:start.x,y:start.y,x2:p.x,y2:p.y,text:'',tooth:''};commit([...marks,m]);choose(m);setTool('select');setMessage('Anotación creada. Arrástrala o añade un comentario en sus propiedades.');return;
  }
  const target=(e.target as Element).closest('[data-mark]'),m=marks.find(m=>m.id===target?.getAttribute('data-mark'));
  if(!m){clearSelection();return;}if(m.id!==selected&&!leaveDraft())return;
  if(m.id!==selected)choose(m);
  const handle=(e.target as Element).getAttribute('data-handle'),isLabel=!!(e.target as Element).closest('[data-label]'),box=labelBox(m);gesture.current={id:e.pointerId,mode:isLabel?'label':handle==='start'?'start':handle==='end'?'end':'move',before:marks,mark:isLabel?{...m,label:{x:box.x/1000,y:box.y/h}}:m,...p,left:0,top:0};e.currentTarget.setPointerCapture(e.pointerId);
 }
 function move(e:PointerEvent<SVGSVGElement>){
  if(e.pointerType==='touch'&&touches.current.has(e.pointerId))touches.current.set(e.pointerId,{x:e.clientX,y:e.clientY});
  if(pinching.current){const pts=[...touches.current.values()],start=pinch.current;if(pts.length>=2&&start&&viewport.current){const next=Math.max(1,Math.min(4,start.zoom*Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y)/start.distance)),rect=viewport.current.getBoundingClientRect();pendingScroll.current={left:start.x*next/start.zoom-((pts[0].x+pts[1].x)/2-rect.left),top:start.y*next/start.zoom-((pts[0].y+pts[1].y)/2-rect.top)};setZoom(next);if(next===zoom){viewport.current.scrollLeft=pendingScroll.current.left;viewport.current.scrollTop=pendingScroll.current.top;pendingScroll.current=null;}}return;}
  const g=gesture.current;if(!g||g.id!==e.pointerId)return;if(g.mode==='pan'){if(Math.hypot(e.clientX-g.x,e.clientY-g.y)>6)g.moved=true;viewport.current?.scrollTo(g.left-(e.clientX-g.x),g.top-(e.clientY-g.y));return;}const p=position(e),m=g.mark!;let next:Mark;
  if(g.mode==='label'){const label={x:clamp(m.label!.x+p.x-g.x),y:clamp(m.label!.y+p.y-g.y)};next=m.kind==='text'?{...m,x:label.x,y:label.y,x2:label.x,y2:label.y,label}:{...m,label};}else if(g.mode==='start')next=m.kind==='text'?{...m,x:p.x,y:p.y,x2:p.x,y2:p.y}:{...m,x:p.x,y:p.y};else if(g.mode==='end')next={...m,x2:p.x,y2:p.y};else{const dx=Math.max(-Math.min(m.x,m.x2),Math.min(1-Math.max(m.x,m.x2),p.x-g.x)),dy=Math.max(-Math.min(m.y,m.y2),Math.min(1-Math.max(m.y,m.y2),p.y-g.y));next={...m,x:m.x+dx,x2:m.x2+dx,y:m.y+dy,y2:m.y2+dy};}replace(g.before.map(item=>item.id===m.id?next:item));
 }
 function finish(e:PointerEvent<SVGSVGElement>,cancel=false){touches.current.delete(e.pointerId);if(pinching.current){if(!touches.current.size){pinching.current=false;pinch.current=null;touchBefore.current=null;}if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);return;}const g=gesture.current;if(!g||g.id!==e.pointerId)return;gesture.current=null;if(cancel)replace(g.before);else if(g.mode==='pan'&&g.clearOnTap&&!g.moved)clearSelection();else if(g.mode!=='pan'&&JSON.stringify(g.before)!==JSON.stringify(current.current)){setPast(p=>[...p.slice(-49),g.before]);setFuture([]);setMessage('Posición actualizada');}if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}
 function keys(e:KeyboardEvent<HTMLDivElement>){if((e.target as HTMLElement).closest('input,textarea,select'))return;if(e.key==='Escape'){setPoint(null);if(leaveDraft())choose();return;}if(!canEdit)return;
  if((e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();history(e.key.toLowerCase()==='y'||e.shiftKey?'redo':'undo');return;}
  if(picked&&(e.key==='Delete'||e.key==='Backspace')){e.preventDefault();remove();}
  if(picked&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const d=e.shiftKey?.02:.002,dx=e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0,dy=e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0;const mx=Math.max(-Math.min(picked.x,picked.x2),Math.min(1-Math.max(picked.x,picked.x2),dx)),my=Math.max(-Math.min(picked.y,picked.y2),Math.min(1-Math.max(picked.y,picked.y2),dy));commit(marks.map(m=>m.id===picked.id?{...m,x:m.x+mx,x2:m.x2+mx,y:m.y+my,y2:m.y2+my,...(m.kind==='text'?{label:{x:clamp((m.label?.x??m.x)+mx),y:clamp((m.label?.y??m.y)+my)}}:{})}:m));}
 }
 return <InlinePanel title={photo.display_name||'Fotografía clínica'} onClose={()=>{if(!unsaved||window.confirm('Hay cambios sin guardar. ¿Cerrar sin guardarlos?'))close();}}><div className="photo-studio" onKeyDown={keys}>
 <div className="studio-name">{editable&&<button className="text-button" onClick={()=>{setName(photo.display_name||'');setNaming(v=>!v);}}>Cambiar nombre</button>}{naming&&<div className="form"><label className="field"><span>Nombre de la fotografía</span><input aria-label="Nombre de la fotografía" maxLength={100} value={name} disabled={nameBusy} placeholder="Ej. Vista frontal · primera consulta" onChange={e=>setName(e.target.value)}/></label><div className="form-actions"><button className="button secondary" aria-busy={nameBusy} disabled={nameBusy||!name.trim()} onClick={async()=>{setNameBusy(true);setNameError('');try{await api('patients/'+patientId+'/attachments/'+photo.id+'/name','PATCH',{display_name:name.trim()},15000);onRename(name.trim());setNaming(false);}catch(e){setNameError((e as Error).message);}finally{setNameBusy(false);}}}>{nameBusy?'Guardando nombre…':'Guardar nombre'}</button><button className="text-button" disabled={nameBusy} onClick={()=>setNaming(false)}>Cancelar</button></div><ErrorMessage message={nameError}/></div>}<details className="studio-original"><summary>Archivo original</summary>{photo.filename}</details></div><div className="studio-top"><span className="studio-state">{busy?'Guardando, espera un momento…':error?'No se completó la operación. Revisa el aviso.':data&&data.version!==data.latest?'Versión histórica · solo lectura':unsaved?'● Cambios sin guardar':savedVersion?'✓ Cambios guardados · versión '+savedVersion:'✓ Sin cambios pendientes · original protegido'}</span>{editable&&<button className="button primary" aria-busy={busy} disabled={!canEdit||(!dirty&&!draft)||!!point} onClick={async()=>{if(draft&&tooth&&!/^([1-4][1-8]|[5-8][1-5])$/.test(tooth)){setError('La pieza dental no es válida. Corrígela antes de guardar.');return;}const snapshot=draft?marks.map(m=>m.id===selected?{...m,text:text.trim(),tooth}:m):marks;replace(snapshot);if(draft)choose(snapshot.find(m=>m.id===selected));setBusy(true);setError('');let confirmed=false;try{const result=await api<{version:number}>(base,'POST',{version:data!.version,marks:snapshot},15000);if(!Number.isInteger(result.version)||result.version<1)throw new Error('No se pudo confirmar el guardado. Tus cambios siguen aquí; vuelve a intentar.');confirmed=true;setSavedVersion(result.version);setData(previous=>previous?{...previous,version:result.version,latest:result.version,marks:snapshot,history:[{version:result.version,author:'Esta sesión',created_at:new Date().toISOString()},...previous.history].slice(0,25)}:previous);setMessage('Versión guardada.');const next=await api<Version>(base);setData(next);replace(next.marks);setPast([]);setFuture([]);choose(next.marks.find(m=>m.id===selected));setMessage('Versión guardada.');}catch(e){setError(confirmed?'Los cambios sí se guardaron. No pudimos actualizar el historial; puedes volver a abrir la foto.':(e as Error).message);}finally{setBusy(false);}}}><Save size={16}/>{busy?'Guardando…':'Guardar cambios'}</button>}</div>
 <ErrorMessage message={error}/>{savedVersion===data?.version&&!unsaved&&savedVersion!==null&&<p role="status" className="saved">Cambios guardados en la versión {savedVersion}. Puedes cerrar la fotografía.</p>}{!data&&!error&&<p role="status">Cargando fotografía…</p>}
 {data&&<><div className="studio-toolbar" role="toolbar" aria-label="Herramientas de fotografía">{([{key:'select',label:'Seleccionar',icon:MousePointer2},{key:'arrow',label:'Flecha',icon:MoveUpRight},{key:'circle',label:'Círculo',icon:Circle},{key:'text',label:'Nota',icon:StickyNote},{key:'pan',label:'Mover vista',icon:Hand}] as const).map(t=><button key={t.key} aria-pressed={tool===t.key} disabled={t.key!=='pan'&&!canEdit} onClick={()=>{if(!leaveDraft())return;setTool(t.key);setPoint(null);if(t.key!=='select')choose();setVisible(true);}}><t.icon size={18}/>{t.label}</button>)}<span className="studio-divider"/><button disabled={!canEdit||(!past.length&&!point)} onClick={()=>history('undo')} title="Ctrl/⌘ Z"><Undo2 size={18}/>Deshacer</button><button disabled={!canEdit||!future.length} onClick={()=>history('redo')} title="Ctrl/⌘ Mayús Z"><Redo2 size={18}/>Rehacer</button></div>
 <div className="studio-layout"><div className="studio-main"><div className="studio-viewbar"><label>Zoom <select aria-label="Zoom de fotografía" value={zoom} onChange={e=>{setZoom(Number(e.target.value));setPoint(null);}}><option value={1}>Ajustar</option><option value={1.5}>150%</option><option value={2}>200%</option><option value={3}>300%</option><option value={4}>400%</option>{![1,1.5,2,3,4].includes(zoom)&&<option value={zoom}>{Math.round(zoom*100)}%</option>}</select></label><button className="text-button" onClick={()=>{setVisible(v=>!v);setPoint(null);}}>{visible?'Ver original sin marcas':'Mostrar anotaciones'}</button><button className="text-button" aria-pressed={comments} onClick={()=>setComments(v=>!v)}>{comments?'Ocultar comentarios':'Mostrar comentarios'}</button>{canvasWidth/zoom<500&&<button className="text-button" aria-pressed={fullComments} onClick={()=>setFullComments(v=>!v)}>{fullComments?'Compactar tarjetas':'Expandir tarjetas'}</button>}</div>
 <div className="studio-canvas" ref={viewport}><div style={{position:'relative',width:`${zoom*100}%`,lineHeight:0}}>{url&&<img src={url} alt="Fotografía clínica original" draggable={false} style={{width:'100%',height:'auto',display:'block'}} onLoad={e=>{setRatio(e.currentTarget.naturalHeight/e.currentTarget.naturalWidth);setReady(true);}} onError={()=>{setReady(false);setError('El navegador no puede mostrar esta imagen. El original sigue disponible para descargar.');}}/>}
 {ready&&<svg ref={svg} tabIndex={0} role="img" aria-label="Lienzo de anotaciones" viewBox={`0 0 1000 ${h}`} onPointerDown={down} onPointerMove={move} onPointerUp={e=>finish(e)} onPointerCancel={e=>finish(e,true)} style={{position:'absolute',inset:0,width:'100%',height:'100%',touchAction:'none',cursor:tool==='pan'?'grab':tool==='select'?'default':'crosshair'}}><defs><marker id={marker} markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L0,6 L9,3 z" fill="#ffdd33"/></marker></defs>{visible&&marks.map((m,i)=>m.kind==='text'?null:<g key={m.id} data-mark={m.id} aria-label={`${names[m.kind]} ${i+1}`} fill="none" stroke="#ffdd33" strokeWidth={3} style={{cursor:tool==='select'?'move':undefined}}>{m.kind==='arrow'&&<><line x1={m.x*1000} y1={m.y*h} x2={m.x2*1000} y2={m.y2*h} stroke="transparent" strokeWidth={32}/><line x1={m.x*1000} y1={m.y*h} x2={m.x2*1000} y2={m.y2*h} markerEnd={`url(#${marker})`}/></>}{m.kind==='circle'&&<ellipse cx={(m.x+m.x2)*500} cy={(m.y+m.y2)*h/2} rx={Math.max(2,Math.abs(m.x2-m.x)*500)} ry={Math.max(2,Math.abs(m.y2-m.y)*h/2)} fill="transparent"/>}<text x={Math.min(m.x*1000,900)} y={Math.max(26,m.y*h-10)} stroke="#10252d" strokeWidth={4} paintOrder="stroke" fill="#ffdd33" fontSize={26}>{i+1}{m.tooth?' · '+m.tooth:''}</text>{selected===m.id&&canEdit&&tool==='select'&&<>{(['start','end'] as ('start'|'end')[]).map(handle=><Fragment key={handle}><circle data-handle={handle} cx={(handle==='start'?m.x:m.x2)*1000} cy={(handle==='start'?m.y:m.y2)*h} r={22000/canvasWidth} fill="transparent" stroke="none" style={{cursor:'crosshair'}}/><circle cx={(handle==='start'?m.x:m.x2)*1000} cy={(handle==='start'?m.y:m.y2)*h} r={7000/canvasWidth} fill="white" stroke="#18b6a4" strokeWidth={2000/canvasWidth} pointerEvents="none"/></Fragment> )}</>}</g>)}{visible&&marks.map((m,i)=>{const comment=m.id===selected?text:m.text,piece=m.id===selected?tooth:m.tooth;if(m.kind!=='text'&&(!comments||!comment.trim()))return null;const box=labelBox(m);return <foreignObject key={'label-'+m.id} data-mark={m.id} data-label="true" x={box.x} y={box.y} width={box.w} height={box.height}><div className="studio-comment" style={{fontSize:13*1000/canvasWidth,padding:8*1000/canvasWidth,borderWidth:2*1000/canvasWidth,borderColor:selected===m.id?'#18b6a4':'#dce7e8',cursor:canEdit&&tool==='select'?'move':'default'}} title={comment}><strong>{names[m.kind]} {i+1}{piece?' · Pieza '+piece:''}</strong><span style={{display:compact(m)?'none':undefined}}>{comment?(comment.length>100?comment.slice(0,97)+'…':comment):'Escribe tu nota en el panel'}</span></div></foreignObject>;})}{point&&<circle cx={point.x*1000} cy={point.y*h} r={9} fill="#ffdd33"/>}</svg>}</div></div>
 <p className="studio-hint">{!canEdit?'Consulta las anotaciones en la lista.':!visible?'Vista original. Activa las anotaciones para editarlas.':tool==='pan'?'Arrastra para recorrer la imagen ampliada.':point?'Toca el segundo punto. Deshacer cancela el inicio.':tool==='select'?'Selecciona una marca y arrástrala. Los tiradores blancos ajustan sus extremos. Arrastra el comentario para acomodarlo.':tool==='text'?'Toca la imagen para colocar una nota.':'Toca el inicio y el final para crear la marca.'}</p><p className="studio-hint">Usa dos dedos para ampliar o reducir. Arrastra el fondo con un dedo para desplazarte. Toca una tarjeta compacta para leerla y editarla.</p><p className="studio-feedback" role="status">{message}</p>
 </div><aside className="studio-inspector" aria-label="Propiedades de anotación"><h3>{picked?`${names[picked.kind]} ${marks.indexOf(picked)+1}`:'Anotaciones'}</h3>{picked?<><p className="studio-hint">{canEdit?(picked.kind==='text'?'Nota independiente: arrastra su tarjeta para colocarla donde quieras.':'El comentario pertenece a esta figura. Puedes mover su tarjeta por separado.'):'Anotación guardada · solo lectura'}</p><label className="field"><span>{picked.kind==='text'?'Texto de la nota':'Comentario de '+(picked.kind==='arrow'?'la flecha':'este círculo')+' (opcional)'}</span><textarea aria-label="Comentario de la anotación" rows={4} maxLength={300} value={text} disabled={!canEdit} onChange={e=>setText(e.target.value)} placeholder="Escribe tu observación…"/></label><label className="field"><span>Pieza dental (opcional)</span><input aria-label="Pieza dental" maxLength={2} inputMode="numeric" value={tooth} disabled={!canEdit} onChange={e=>setTooth(e.target.value)}/><small>Numeración FDI · permanente o temporal</small></label>{canEdit&&<><button className="button secondary" disabled={!draft} onClick={apply}>Aplicar comentario</button>{picked.kind!=='text'&&!!text&&<button className="text-button" onClick={()=>{const next={...picked,text:'',label:undefined};commit(marks.map(m=>m.id===picked.id?next:m));choose(next);}}>Quitar comentario sin borrar figura</button>}{draft&&<small>El comentario se incluirá al guardar.</small>}<div className="studio-object-actions"><button onClick={()=>{if(!leaveDraft())return;if(marks.length>=100){setError('Máximo 100 anotaciones.');return;}const dx=Math.min(.025,1-Math.max(picked.x,picked.x2)),dy=Math.min(.025,1-Math.max(picked.y,picked.y2)),copy={...picked,id:crypto.randomUUID(),x:picked.x+dx,x2:picked.x2+dx,y:picked.y+dy,y2:picked.y2+dy,...(picked.label?{label:{x:clamp(picked.label.x+dx),y:clamp(picked.label.y+dy)}}:{})};commit([...marks,copy]);choose(copy);}}><Copy size={16}/>Duplicar</button><button className="danger-text" onClick={remove}><Trash2 size={16}/>Eliminar</button></div></>}</>:<p className="studio-hint">Elige Flecha, Círculo o Nota y marca la imagen. Después selecciona cualquier anotación para editarla.</p>}
 <div className="studio-mark-list"><h4>En esta imagen <span>{marks.length}</span></h4>{!marks.length&&<p className="studio-hint">Todavía no hay anotaciones.</p>}{marks.map((m,i)=><button key={m.id} aria-pressed={m.id===selected} aria-label={`Seleccionar anotación ${i+1}`} onClick={()=>select(m)}><span className="studio-number">{i+1}</span><span><strong>{names[m.kind]}{m.tooth?' · Pieza '+m.tooth:''}</strong><small>{m.text||'Sin comentario'}</small></span></button>)}</div></aside></div>
 <details className="studio-history"><summary>Historial de versiones · {data.version?`versión ${data.version}`:'sin guardar'}</summary><label className="field"><span>Versión de anotaciones</span><select aria-label="Versión de anotaciones" disabled={busy} value={data.version} onChange={e=>void load(Number(e.target.value))}>{!data.version&&<option value={0}>Sin anotaciones</option>}{data.history.map(v=><option key={v.version} value={v.version}>Versión {v.version} · {v.author} · {new Date(v.created_at).toLocaleString('es-MX')}</option>)}</select></label><button className="text-button" disabled={busy} onClick={()=>void load()}>Volver a última versión</button><p className="studio-hint">El original permanece intacto. Se muestran las últimas 25 versiones.</p></details>{data.version!==data.latest&&<p className="studio-hint">Versión histórica de solo lectura. Vuelve a la última para editar.</p>}
 </> }</div></InlinePanel>;
}
