'use client';
import { useEffect,useRef,useState } from 'react';
import { PrescriptionReview } from './prescription-review';
import { api } from '../lib/api';
import { ErrorMessage,Section } from './ui';
type Professional={id:string;name:string;license:string;specialty:string;professional_title:string;practice_address:string};
const fields={name:'Medicamento',presentation:'Presentación',dose:'Dosis',route:'Vía',frequency:'Frecuencia',duration:'Duración',instructions:'Indicaciones'};
type Medicine=Record<keyof typeof fields,string>;
type Input={professional_id:string;title:string;medications:Medicine[];notes:string};
type Row={prepared_version?:number;id:string;version:number;input:Input;created_at:string;author:string;snapshot:{patient:{first_name:string;last_name:string;record_number:string;birth_date:string|null};professional:Professional;organization:{name:string;address:string;phone:string}}};
const blank=():Medicine=>({name:'',presentation:'',dose:'',route:'',frequency:'',duration:'',instructions:''});
export function PrescriptionDrafts({patientId,patientName,editable}:{patientId:string;patientName:string;editable:boolean}){
 const [review,setReview]=useState<{id:string;version:number}|null>(null);
 const base='patients/'+patientId+'/prescription-drafts';const [rows,setRows]=useState<Row[]>([]),[page,setPage]=useState(1),[more,setMore]=useState(false),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [draft,setDraft]=useState<{id:string;version:number;data:Input}|null>(null),[professional,setProfessional]=useState<Professional|null>(null),[q,setQ]=useState(''),[choices,setChoices]=useState<Professional[]>([]),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState(''),[hasMore,setHasMore]=useState(false);
 const request=useRef<{body:string;id:string}|null>(null);
 useEffect(()=>{let live=true;api<{items:Row[];hasMore:boolean}>(base+'?page='+page,'GET',undefined,15000).then(r=>{if(live){setRows(r.items);setMore(r.hasMore);setError('');}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[base,page,revision]);
 useEffect(()=>{let live=true;if(!draft)return;const timer=setTimeout(()=>{setSearching(true);api<{items:Professional[];hasMore:boolean}>(base+'/professionals?q='+encodeURIComponent(q),'GET',undefined,15000).then(r=>{if(live){setChoices(r.items);setHasMore(r.hasMore);setSearchError('');}}).catch(e=>{if(live)setSearchError(e.message);}).finally(()=>{if(live)setSearching(false);});},200);return()=>{live=false;clearTimeout(timer);};},[base,q,!!draft]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(draft){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[draft]);
 function begin(row?:Row){setDraft(row?{id:row.id,version:row.version,data:row.input}:{id:crypto.randomUUID(),version:0,data:{professional_id:'',title:'Receta en preparación',medications:[blank()],notes:''}});setProfessional(row?.snapshot.professional||null);setQ('');setMessage('');setError('');}
 async function save(){if(!draft)return;if(!draft.data.professional_id){setError('Selecciona al doctor responsable.');return;}const body=JSON.stringify(draft);if(request.current?.body!==body)request.current={body,id:crypto.randomUUID()};setBusy(true);setError('');try{await api(base,'POST',{...draft,request_id:request.current!.id},15000);setDraft(null);request.current=null;setPage(1);setRevision(v=>v+1);setMessage('Borrador de receta guardado.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Section title="Borradores de recetas" description="Prepara medicamentos e indicaciones para revisión del profesional."><p className="notice">Prepara, revisa e imprime. El documento queda pendiente de la firma autógrafa del doctor.</p>{review&&<PrescriptionReview key={review.id+review.version} patientId={patientId} id={review.id} version={review.version} editable={editable} onPrepared={()=>setRevision(v=>v+1)} close={()=>setReview(null)}/>}<ErrorMessage message={error}/>{message&&<p role="status" className="saved">{message}</p>}{!draft&&editable&&<button className="button secondary" disabled={busy} onClick={()=>begin()}>Nuevo borrador de receta</button>}
 {draft&&<form className="form panel" onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} className="budget-fields"><legend>Paciente: {patientName}</legend><label className="field"><span>Nombre del borrador</span><input required maxLength={120} value={draft.data.title} onChange={e=>setDraft({...draft,data:{...draft.data,title:e.target.value}})}/></label><label className="field"><span>Buscar doctor responsable</span><input value={q} maxLength={160} onChange={e=>{setQ(e.target.value);setChoices([]);setSearching(true);}} placeholder="Escribe para filtrar…"/></label><ErrorMessage message={searchError}/>{searching?<p role="status">Buscando profesionales…</p>:<div className="treatment-services">{choices.map(p=><button type="button" className="treatment-service-choice" key={p.id} aria-pressed={professional?.id===p.id} onClick={()=>{setProfessional(p);setDraft({...draft,data:{...draft.data,professional_id:p.id}});}}>{p.name} · {p.specialty||'Especialidad sin registrar'}</button>)}{!choices.length&&!searchError&&<p>No hay coincidencias.</p>}{hasMore&&<p>Escribe más para acotar resultados.</p>}</div>}{professional&&<p>Responsable: <strong>{professional.name}</strong> · Cédula: {professional.license||'Pendiente de registrar'} · {professional.practice_address||'Dirección profesional pendiente'}</p>}<p>Los datos actuales del paciente, clínica y doctor se completan al guardar. Las dosis e indicaciones las captura el profesional.</p>
 {draft.data.medications.map((m,index)=><article className="treatment-item budget-line" key={index}><h3>Medicamento {index+1}</h3><div className="form-grid">{Object.entries(fields).map(([key,label])=><label className="field" key={key}><span>{label}</span><input aria-label={label+' '+(index+1)} required={key==='name'} maxLength={key==='instructions'?1000:key==='route'?100:160} value={m[key as keyof Medicine]} onChange={e=>setDraft({...draft,data:{...draft.data,medications:draft.data.medications.map((item,i)=>i===index?{...item,[key]:e.target.value}:item)}})}/></label>)}</div><button type="button" className="text-button" disabled={draft.data.medications.length===1} onClick={()=>setDraft({...draft,data:{...draft.data,medications:draft.data.medications.filter((_,i)=>i!==index)}})}>Quitar medicamento {index+1}</button></article>)}<button type="button" className="button secondary" disabled={draft.data.medications.length>=20} onClick={()=>setDraft({...draft,data:{...draft.data,medications:[...draft.data.medications,blank()]}})}>Añadir medicamento</button><label className="field"><span>Indicaciones generales</span><textarea maxLength={3000} value={draft.data.notes} onChange={e=>setDraft({...draft,data:{...draft.data,notes:e.target.value}})}/></label><div className="form-actions"><button className="button primary" aria-busy={busy}>Guardar borrador de receta</button><button type="button" className="text-button" onClick={()=>{if(window.confirm('¿Descartar los cambios del borrador?'))setDraft(null);}}>Descartar cambios</button></div></fieldset></form>}
 {loading&&<p role="status">Cargando borradores…</p>}{!loading&&!rows.length&&!error&&<p>Aún no hay borradores guardados.</p>}{rows.map(r=><details className="clinical-entry" key={r.id+':'+r.version}><summary>{r.input.title} · versión {r.version} · {r.author} · {new Date(r.created_at).toLocaleString('es-MX')}</summary><p>{r.prepared_version===r.version?'Preparada para firma autógrafa':'Borrador sin emitir'}</p><button className="button secondary" disabled={!!draft||busy} onClick={()=>setReview({id:r.id,version:r.version})}>Revisar / imprimir versión {r.version}</button><p>{r.snapshot.organization.name} · {r.snapshot.organization.address}</p><p>Paciente: {r.snapshot.patient.first_name} {r.snapshot.patient.last_name} · {r.snapshot.patient.record_number} · Nacimiento: {r.snapshot.patient.birth_date?.slice(0,10)||'No registrado'}</p><p>Doctor: {r.snapshot.professional.name} · {r.snapshot.professional.professional_title} · Cédula: {r.snapshot.professional.license||'Sin registrar'} · {r.snapshot.professional.practice_address}</p>{r.input.medications.map((m,index)=><dl className="clinical-summary" key={index}>{Object.entries(fields).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{m[key as keyof Medicine]||'Pendiente'}</dd></div>)}</dl>)}<p className="patient-notes">{r.input.notes}</p>{editable&&<button className="text-button" disabled={!!draft||busy} onClick={()=>{setReview(null);if(r.prepared_version){begin({...r,id:crypto.randomUUID(),version:0});}else begin(r);}}>{r.prepared_version?'Copiar a nuevo borrador':'Editar este borrador'}</button>}</details>)}<div className="form-actions"><button className="text-button" disabled={!!draft||busy||loading} onClick={()=>{setLoading(true);setRevision(v=>v+1);}}>Actualizar borradores</button>{page>1&&<button className="text-button" disabled={!!draft||busy} onClick={()=>{setLoading(true);setPage(p=>p-1);}}>Más recientes</button>}{more&&<button className="text-button" disabled={!!draft||busy} onClick={()=>{setLoading(true);setPage(p=>p+1);}}>Versiones anteriores</button>}</div><small>Se conservan todas las versiones. Editar una versión anterior requiere cargar la última; cada guardado actualiza los datos del paciente y doctor en la nueva versión.</small></Section>;
}
