'use client';
import { useEffect,useRef,useState } from 'react';
import { api } from '../lib/api';
import { prescriptionHtml,type PrescriptionRow,type Preparation } from '../lib/prescription-document';
import { ErrorMessage } from './ui';
type Review={row:PrescriptionRow;latest:number;missing:string[];prepared:Preparation|null};
export function PrescriptionReview({patientId,id,version,editable,onPrepared,close}:{patientId:string;id:string;version:number;editable:boolean;onPrepared:()=>void;close:()=>void}){
 const base='patients/'+patientId+'/prescription-drafts';const [data,setData]=useState<Review|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[revision,setRevision]=useState(0),[frameReady,setFrameReady]=useState(false);const frame=useRef<HTMLIFrameElement>(null);
 useEffect(()=>{let live=true;api<Review>(base+'/'+id+'/'+version+'/review','GET',undefined,15000).then(r=>{if(live)setData(r);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[base,id,version,revision]);
 const prepared=data?.prepared?.version===version?data.prepared:null;
 return <div className="panel prescription-review"><div className="form-actions"><h3>Revisar receta</h3><button className="text-button" disabled={busy} onClick={close}>Cerrar revisión</button></div><ErrorMessage message={error}/>{!data&&!error&&<p role="status">Cargando revisión…</p>}{!data&&error&&<button className="text-button" onClick={()=>{setError('');setRevision(v=>v+1);}}>Reintentar revisión</button>}{data&&<>{prepared?<p className="saved" role="status">Preparada para firma autógrafa. Folio: {prepared.id}</p>:<><p>Revisa los datos y medicamentos antes de preparar. El documento seguirá pendiente de la revisión final y firma autógrafa del doctor.</p>{data.missing.length>0&&<div className="notice"><strong>Falta completar:</strong><ul>{data.missing.map(m=><li key={m}>{m}</li>)}</ul><p>Corrige el borrador o los datos del profesional y guarda una nueva versión antes de continuar.</p></div>}{data.latest!==version&&<p>Esta es una versión anterior. Abre la última versión para preparar.</p>}{data.prepared&&<p>Este borrador ya tiene otra versión preparada para firma.</p>}{editable&&!data.prepared&&data.latest===version&&!data.missing.length&&<><label className="check-field"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/><span>Revisé los datos y el desglose para preparar el documento. Entiendo que debe firmarlo el doctor y que este formato no es un recetario especial.</span></label><button className="button primary" disabled={busy||!confirmed} aria-busy={busy} onClick={async()=>{setBusy(true);setError('');try{const result=await api<Preparation>(base+'/'+id+'/prepare','POST',{version,reviewed:true},15000);setFrameReady(false);setData({...data,prepared:result});onPrepared();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Preparar para firma</button></>}</>}
 <div className="form-actions"><button className="button secondary" disabled={!frameReady||busy} onClick={()=>{try{frame.current?.contentWindow?.focus();frame.current?.contentWindow?.print();}catch{setError('No se pudo abrir la impresión. Prueba desde un navegador de escritorio.');}}}>{prepared?'Imprimir / guardar PDF':'Imprimir borrador'}</button><small>Elige “Guardar como PDF” en la ventana de impresión. Preparar conserva esta versión; para corregirla crea un borrador nuevo.</small></div><iframe className="prescription-frame" title="Vista previa de receta" ref={frame} sandbox="allow-same-origin allow-modals" srcDoc={prescriptionHtml(data.row,prepared)} onLoad={()=>setFrameReady(true)}/></>}</div>;
}
