'use client';
import {useEffect,useRef,useState} from 'react';
import {ProfessionalPaymentReceipt} from './professional-payment-receipt';
import {api} from '../lib/api';
import {ErrorMessage} from './ui';
type Row={id:string;amount_minor:number;kind:string;method:string;branch_name:string;reference:string;notes:string;author:string;created_at:string;professional_name:string;share_version:number;currency:string;voided_at:string|null;void_reason:string|null;voided_by:string|null};
type Data={share:{id:string;version:number;professional_name:string;amount_minor:number;paid_minor:number;balance_minor:number;currency:string}|null;items:Row[];hasMore:boolean;branches:{id:string;name:string}[]};
const methods:Record<string,string>={cash:'Efectivo',transfer:'Transferencia',other:'Otro'};
const money=(n:number,c:string)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:c}).format(n/100)+' '+c;
const minor=(v:string)=>/^\d{1,11}(\.\d{1,2})?$/.test(v)?Math.round(Number(v)*100):NaN;
export function ProfessionalPayments({patientId,canCreate,canVoid}:{patientId:string;canCreate:boolean;canVoid:boolean}){
 const [receiptId,setReceiptId]=useState<string|null>(null);const base='patients/'+patientId+'/professional-payments';const [data,setData]=useState<Data|null>(null),[revision,setRevision]=useState(0),[page,setPage]=useState(1),[editing,setEditing]=useState(false),[voiding,setVoiding]=useState<Row|null>(null),[amount,setAmount]=useState(''),[kind,setKind]=useState('installment'),[method,setMethod]=useState('transfer'),[branch,setBranch]=useState(''),[reference,setReference]=useState(''),[notes,setNotes]=useState(''),[reason,setReason]=useState(''),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const request=useRef<{body:string;id:string}|null>(null);const dirty=editing||Boolean(voiding);
 useEffect(()=>{let live=true;setData(null);api<Data>(base+'?page='+page,'GET',undefined,15000).then(r=>{if(live){setData(r);setError('');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[base,page,revision]);
 useEffect(()=>{const update=()=>{if(!dirty){setPage(1);setRevision(v=>v+1);}};window.addEventListener('alia-budget-changed',update);window.addEventListener('alia-share-changed',update);return()=>{window.removeEventListener('alia-budget-changed',update);window.removeEventListener('alia-share-changed',update);};},[dirty]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function start(){setAmount('');setKind('installment');setMethod('transfer');setBranch(data?.branches[0]?.id||'');setReference('');setNotes('');setChecked(false);setEditing(true);setMessage('');request.current=null;}
 async function save(){if(!data)return;setBusy(true);setError('');try{let path=base,payload:object;if(voiding){path+='/'+voiding.id+'/void';payload={reason,reviewed:checked};}else{const value=minor(amount);if(!Number.isSafeInteger(value)||value<=0||value>1000000000000)throw new Error('Captura un importe positivo con hasta dos decimales.');payload={share_id:data.share!.id,amount_minor:value,kind,method,branch_id:branch,reference,notes,reviewed:checked};}const body=JSON.stringify({path,payload});if(request.current?.body!==body)request.current={body,id:crypto.randomUUID()};await api(path,'POST',{...payload,request_id:request.current!.id},15000);setMessage(voiding?'Captura anulada. El original permanece en el historial.':'Pago al doctor registrado.');setEditing(false);setVoiding(null);setPage(1);setRevision(v=>v+1);window.dispatchEvent(new Event('alia-professional-payment-changed'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel professional-payments"><h2>Pagos al doctor</h2><p>Registra dinero ya entregado al profesional para este tratamiento. No ejecuta transferencias ni reduce el saldo del paciente. Los nuevos cortes incluyen estos egresos; el arqueo descuenta los pagos en efectivo. No los dupliques como ajustes manuales. Los cortes ya guardados se conservan.</p><ErrorMessage message={error}/>{message&&<p role="status" className="saved">{message}</p>}{!data&&!error&&<p role="status">Cargando pagos al doctor…</p>}<button className="text-button" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('¿Descartar la captura y actualizar los pagos al doctor?'))return;setEditing(false);setVoiding(null);setRevision(v=>v+1);}}>Actualizar pagos al doctor</button>{data&&<>{data.share?<><h3>{data.share.professional_name} · Asignación {data.share.version}</h3><div className="payment-summary"><p>Participación asignada<strong>{money(data.share.amount_minor,data.share.currency)}</strong></p><p>Pagado al doctor<strong>{money(data.share.paid_minor,data.share.currency)}</strong></p><p>Pendiente del doctor<strong>{money(data.share.balance_minor,data.share.currency)}</strong></p></div>{data.share.balance_minor===0&&<p>{data.share.amount_minor>0?'Participación liquidada según los registros vigentes.':'Participación de importe cero; no requiere pago.'}</p>}{canCreate&&!dirty&&data.share.balance_minor>0&&<button className="button secondary" onClick={start}>Registrar pago al doctor</button>}</>:<p>Asigna primero la participación del doctor sobre el acuerdo aceptado.</p>}
 {editing&&data.share&&<form className="form" onSubmit={e=>{e.preventDefault();void save();}}><fieldset className="budget-fields" disabled={busy}><legend>Pago entregado a {data.share.professional_name}</legend><div className="form-grid"><label className="field"><span>Tipo de pago al doctor</span><select aria-label="Tipo de pago al doctor" value={kind} onChange={e=>{setKind(e.target.value);if(e.target.value==='settlement')setAmount((data.share!.balance_minor/100).toFixed(2));setChecked(false);}}><option value="installment">Abono</option><option value="settlement">Liquidación del saldo</option></select></label><label className="field"><span>Importe pagado al doctor ({data.share.currency})</span><input inputMode="decimal" required maxLength={14} value={amount} onChange={e=>{setAmount(e.target.value);setChecked(false);}}/></label><label className="field"><span>Método de pago al doctor</span><select aria-label="Método de pago al doctor" value={method} onChange={e=>{setMethod(e.target.value);setChecked(false);}}>{Object.entries(methods).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label className="field"><span>Sucursal del pago al doctor</span><select aria-label="Sucursal del pago al doctor" required value={branch} onChange={e=>{setBranch(e.target.value);setChecked(false);}}><option value="">Selecciona sucursal</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><label className="field"><span>Referencia del pago al doctor</span><input maxLength={160} value={reference} onChange={e=>{setReference(e.target.value);setChecked(false);}}/></label><label className="field"><span>Observaciones del pago al doctor</span><textarea maxLength={2000} value={notes} onChange={e=>{setNotes(e.target.value);setChecked(false);}}/></label><label className="check-field"><input type="checkbox" required checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>Confirmo que este pago ya se entregó al doctor y revisé importe, método y sucursal.</span></label><div className="form-actions"><button className="button primary" disabled={busy||!checked} aria-busy={busy}>{busy?'Guardando…':'Guardar pago al doctor'}</button><button type="button" className="text-button" onClick={()=>{if(window.confirm('¿Descartar el pago sin guardar?'))setEditing(false);}}>Descartar pago al doctor</button></div></fieldset></form>}
 {voiding&&<form className="form" onSubmit={e=>{e.preventDefault();void save();}}><fieldset className="budget-fields" disabled={busy}><legend>Anular captura errónea</legend><p>{voiding.professional_name} · {money(voiding.amount_minor,voiding.currency)} · Folio: {voiding.id}</p><p>Solo corrige un registro erróneo. No devuelve dinero ni debe usarse para cambiar una participación ya pagada.</p><label className="field"><span>Motivo de anulación del pago al doctor</span><textarea required maxLength={2000} value={reason} onChange={e=>{setReason(e.target.value);setChecked(false);}}/></label><label className="check-field"><input type="checkbox" required checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>Confirmo que es una captura errónea, no una devolución de dinero.</span></label><div className="form-actions"><button className="button primary" disabled={!checked||busy} aria-busy={busy}>Confirmar anulación del pago al doctor</button><button type="button" className="text-button" onClick={()=>{if(window.confirm('¿Descartar la anulación sin guardar?'))setVoiding(null);}}>Descartar anulación</button></div></fieldset></form>}
 {receiptId&&<ProfessionalPaymentReceipt key={receiptId} patientId={patientId} paymentId={receiptId} close={()=>setReceiptId(null)}/>}<h3>Historial de pagos al doctor</h3>{!data.items.length&&<p>No hay pagos en esta página.</p>}{data.items.map(r=><article className="clinical-entry" key={r.id}><h4>{r.voided_at?'ANULADO · ':''}{r.kind==='settlement'?'Liquidación':'Abono'} · {money(r.amount_minor,r.currency)}</h4><p>{r.professional_name} · Asignación {r.share_version}<br/>{methods[r.method]} · {r.branch_name}<br/>{r.author} · {new Date(r.created_at).toLocaleString('es-MX')}<br/>Folio: {r.id}</p><button className="text-button" disabled={busy||dirty} onClick={()=>setReceiptId(r.id)}>Ver recibo del doctor</button>{r.reference&&<p className="patient-notes">Referencia: {r.reference}</p>}{r.notes&&<p className="patient-notes">{r.notes}</p>}{r.voided_at?<p className="patient-notes">Anulado por {r.voided_by} · {new Date(r.voided_at).toLocaleString('es-MX')}<br/>{r.void_reason}</p>:canVoid&&<button className="text-button" disabled={dirty||busy} onClick={()=>{setVoiding(r);setReason('');setChecked(false);setMessage('');request.current=null;}}>Anular captura de {money(r.amount_minor,r.currency)}</button>}</article>)}<div className="form-actions"><button className="text-button" disabled={dirty||busy||page===1} onClick={()=>setPage(v=>v-1)}>Pagos al doctor más recientes</button><button className="text-button" disabled={dirty||busy||!data.hasMore} onClick={()=>setPage(v=>v+1)}>Pagos al doctor anteriores</button></div></>}</section>;
}
