'use client';
import {useEffect,useRef,useState} from 'react';
import {api} from '../lib/api';
import {professionalReceiptHtml,type ProfessionalReceipt as Receipt} from '../lib/professional-receipt';
import {ErrorMessage} from './ui';
export function ProfessionalPaymentReceipt({patientId,paymentId,close}:{patientId:string;paymentId:string;close:()=>void}){
 const path='patients/'+patientId+'/professional-payments/'+paymentId+'/receipt';const [data,setData]=useState<Receipt|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[frameKey,setFrameKey]=useState(0);const frame=useRef<HTMLIFrameElement>(null),printPending=useRef(false);
 useEffect(()=>{let live=true;api<Receipt>(path,'GET',undefined,15000).then(r=>{if(live){setData(r);setError('');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[path,revision]);
 async function print(){setBusy(true);setError('');try{const latest=await api<Receipt>(path,'GET',undefined,15000);printPending.current=true;setData(latest);setFrameKey(v=>v+1);}catch(e){setError((e as Error).message);setBusy(false);}}
 return <div className="panel prescription-review consent-detail"><div className="form-actions"><h3>Recibo de pago al doctor</h3><button className="text-button" disabled={busy} onClick={close}>Cerrar recibo del doctor</button></div><ErrorMessage message={error}/>{error&&<button className="text-button" disabled={busy} onClick={()=>{setData(null);setRevision(v=>v+1);setError('');}}>Reintentar recibo</button>}{!data&&!error&&<p role="status">Cargando recibo…</p>}{data&&<><p role="status">{data.voided_at?'Registro anulado. La impresión mostrará la anulación.':'Pago registrado. Puedes imprimir o guardar una copia PDF.'}</p><div className="form-actions"><button className="button primary" disabled={busy} aria-busy={busy} onClick={()=>void print()}>{busy?'Preparando recibo…':'Imprimir recibo del doctor / guardar PDF'}</button><small>Antes de imprimir se consulta de nuevo si el pago fue anulado. En el diálogo, elige “Guardar como PDF” para descargarlo.</small></div><iframe key={frameKey} ref={frame} title="Vista previa del recibo del doctor" className="prescription-frame" sandbox="allow-same-origin allow-modals" srcDoc={professionalReceiptHtml(data)} onLoad={()=>{if(printPending.current){printPending.current=false;try{frame.current?.contentWindow?.focus();frame.current?.contentWindow?.print();}catch{setError('No se pudo abrir la impresión. Prueba en un navegador de escritorio.');}finally{setBusy(false);}}}}/></>}</div>;
}
