'use client';
import { useEffect,useState,useId } from 'react';
import { api } from '../lib/api';
import { ErrorMessage } from './ui';
export type Choice={id:string;name:string;duration_minutes?:number;description?:string};
export function Resource({kind,branch,label,value,onChange,professionalId,required=true}:{professionalId?:string;required?:boolean;kind:'professionals'|'rooms'|'services'|'patients';branch:string;label:string;value:Choice|null;onChange:(value:Choice|null)=>void}){
 const id=useId(),[search,setSearch]=useState(value?.name||''),[items,setItems]=useState<Choice[]>([]),[error,setError]=useState(''),[more,setMore]=useState(false),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[active,setActive]=useState(-1);
 useEffect(()=>{if(!open)return;let live=true;const timer=setTimeout(()=>{
  const promise=kind==='patients'?api<{items:{id:string;first_name:string;last_name:string;record_number:string;phone:string}[];nextCursor:string|null}>('patients?q='+encodeURIComponent(search)+'&limit=20').then(r=>({items:r.items.map(p=>({id:p.id,name:p.first_name+' '+p.last_name+' · '+p.record_number,description:p.phone?'Tel. '+p.phone:'Sin teléfono registrado'})),hasMore:!!r.nextCursor})):api<Record<string,Choice[]>&{hasMore:boolean}>('appointments/options?branch_id='+branch+'&q='+encodeURIComponent(search)+(professionalId?'&professional_id='+professionalId:'')).then(r=>({items:r[kind],hasMore:r.hasMore}));
  promise.then(r=>{if(live){setItems(r.items);setMore(r.hasMore);}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});
 },200);return()=>{live=false;clearTimeout(timer);};},[kind,branch,search,open,professionalId]);
 function show(){setOpen(true);setLoading(true);setItems([]);setActive(-1);setError('');}
 function choose(item:Choice){onChange(item);setSearch(item.name);setOpen(false);setActive(-1);}
 return <div className="field resource-picker" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}><label htmlFor={id}>{label} {required&&<span className="required">*</span>}</label><input id={id} role="combobox" aria-expanded={open} aria-controls={id+'-list'} aria-autocomplete="list" aria-activedescendant={open&&active>=0?id+'-'+active:undefined} autoComplete="off" required={required} value={value?.name??search} placeholder={kind==='patients'?'Nombre, teléfono o expediente…':'Escribe para buscar…'} onFocus={()=>{if(!open){setSearch('');show();}}} onChange={e=>{onChange(null);setSearch(e.target.value);show();}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(!open){setSearch('');show();}else setActive(i=>items.length?(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length:-1);}if(e.key==='Enter'&&open){e.preventDefault();if(active>=0&&items[active])choose(items[active]);}}}/>{open&&<div className="resource-results"><div id={id+'-list'} role="listbox" aria-label={'Resultados de '+label.toLowerCase()}>{items.map((item,index)=><button type="button" role="option" aria-selected={value?.id===item.id} id={id+'-'+index} className={active===index?'highlighted':''} key={item.id} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(item)}><strong>{item.name}</strong>{item.description&&<small>{item.description}</small>}{item.duration_minutes&&<small>{item.duration_minutes} minutos</small>}</button>)}</div>{loading?<p role="status">Buscando…</p>:!items.length&&!error?<p role="status">No encontramos coincidencias. Prueba otro nombre{kind==='patients'?' o registra un paciente nuevo':''}.</p>:null}{more&&<p>Escribe más para acotar los resultados.</p>}<ErrorMessage message={error}/></div>}{value&&<small className="selected-resource">Seleccionado · escribe para cambiar</small>}</div>;
}
