'use client';
import { useCallback, useEffect, useState } from 'react';
import { Check, KeyRound, Monitor, ShieldCheck } from 'lucide-react';
import { api } from '../lib/api';
import type { Me } from '../lib/types';
import { ErrorMessage, Field, Form, Heading, Section } from './ui';
interface Session {id:string;user_agent:string;ip:string;created_at:string;last_seen_at:string;expires_at:string;current:boolean}
export function Security({me,refreshMe,signedOut}:{me:Me;refreshMe:()=>Promise<void>;signedOut:()=>void}){
 const [sessions,setSessions]=useState<Session[]>([]),[error,setError]=useState(''),[setup,setSetup]=useState<{secret:string;uri:string}|null>(null),[codes,setCodes]=useState<string[]>([]),[confirm,setConfirm]=useState(false);
 const load=useCallback(async()=>setSessions(await api<Session[]>('auth/sessions')),[]);useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 return <><Heading eyebrow="MI CUENTA" title="Seguridad y acceso" description="Tú decides cómo proteger tu cuenta."/><div className="identity-strip"><span className="avatar">{me.user.name[0]}</span><div><strong>{me.user.name}</strong><span>{me.user.email}</span></div><span className="pill green">Cuenta activa</span></div><ErrorMessage message={error}/>
 <Section title="Verificación en dos pasos" description="Usa una aplicación de autenticación para añadir protección a tu contraseña."><div className="security-state"><ShieldCheck size={25}/><div><strong>{me.mfaEnabled?'Tu cuenta tiene doble protección':'Añade una capa de seguridad'}</strong><p>{me.mfaEnabled?'La verificación en dos pasos está activa.':'Compatible con aplicaciones TOTP de autenticación.'}</p></div><span className={`pill ${me.mfaEnabled?'green':''}`}>{me.mfaEnabled?'Activa':'Sin activar'}</span></div>
 {codes.length>0&&<div className="recovery-box" role="status"><h3>Guarda tus códigos de recuperación</h3><p>Solo se muestran una vez. Cada código permite un acceso y luego deja de funcionar. Guárdalos en un lugar privado.</p><div className="recovery-codes">{codes.map(code=><code key={code}>{code}</code>)}</div><button className="button secondary" onClick={()=>setCodes([])}><Check size={16}/>Ya los guardé</button></div>}
 {!me.mfaEnabled?setup?<><p className="muted">Añade una cuenta en tu aplicación e introduce esta clave. Después escribe el código de seis dígitos.</p><code className="secret-key">{setup.secret}</code><Form label="Activar verificación" onSubmit={async values=>{const result=await api<{codes:string[]}>('auth/mfa/enable','POST',values);setCodes(result.codes);setSetup(null);await refreshMe();await load();}}><Field label="Código de la aplicación" name="code" required minLength={6} maxLength={6}/></Form></>:<Form label="Configurar verificación" onSubmit={async values=>setSetup(await api('auth/mfa/setup','POST',values))}><Field label="Confirma tu contraseña" name="password" type="password" required/></Form>:<><button className="text-button danger-text" onClick={()=>setConfirm(!confirm)}>Desactivar verificación en dos pasos</button>{confirm&&<Form label="Desactivar verificación" onSubmit={async values=>{await api('auth/mfa/disable','POST',values);setConfirm(false);setCodes([]);await refreshMe();await load();}}><p className="muted">Tu cuenta quedará protegida únicamente por contraseña. Las otras sesiones se cerrarán.</p><Field label="Contraseña" name="password" type="password" required/><Field label="Código TOTP o de recuperación" name="code" required/></Form>}</>}
 </Section><Section title="Contraseña" description="Al cambiarla se cerrarán todas tus sesiones, incluida esta."><Form label="Actualizar contraseña" onSubmit={async values=>{await api('auth/change-password','POST',values);signedOut();}}><div className="form-grid"><Field label="Contraseña actual" name="current" type="password" required/><Field label="Nueva contraseña" name="password" type="password" required minLength={12} maxLength={128} help="Mínimo 12 caracteres."/></div></Form></Section>
 <Section title="Sesiones activas" description="Revisa los dispositivos con acceso. Cierra cualquier sesión que no reconozcas.">{sessions.map(s=><div className="session-row" key={s.id}><Monitor size={23}/><div><strong>{s.user_agent.includes('Mobile')?'Dispositivo móvil':'Navegador web'} {s.current&&<span className="pill green">Esta sesión</span>}</strong><small>{s.ip} · Última actividad: {new Date(s.last_seen_at).toLocaleString('es-MX')}</small><details><summary>Detalles del dispositivo</summary><p className="device-agent">{s.user_agent}</p><small>Vence: {new Date(s.expires_at).toLocaleString('es-MX')}</small></details></div><button className="text-button" onClick={async()=>{try{await api(`auth/sessions/${s.id}`,'DELETE');if(s.current)signedOut();else await load();}catch(e){setError((e as Error).message);}}}>Cerrar sesión</button></div>)}</Section><div className="notice"><KeyRound size={18}/> Los códigos de recuperación sustituyen al segundo factor; consérvalos separados de tu contraseña.</div></>;
}
