'use client';
import { useCallback, useEffect, useState } from 'react';
import { Mail, Plus, ShieldCheck, Users } from 'lucide-react';
import { api } from '../lib/api';
import type { Member, Role } from '../lib/types';
import { Empty, ErrorMessage, Field, Form, Heading, InlinePanel } from './ui';
interface Invitation {id:string;email:string;role:string;expires_at:string;accepted_at:string|null;delivery_status:string|null}
export function Team({view,can,refreshContext}:{view:'team'|'roles';can:(permission:string)=>boolean;refreshContext:()=>Promise<void>}){
 const [members,setMembers]=useState<Member[]>([]),[roles,setRoles]=useState<Role[]>([]),[permissions,setPermissions]=useState<{code:string;description:string}[]>([]),[invitations,setInvitations]=useState<Invitation[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editMember,setEditMember]=useState<Member|null>(null),[editRole,setEditRole]=useState<Role|'new'|null>(null),[selected,setSelected]=useState<string[]>([]),[invite,setInvite]=useState(false);
 const manage=can('users.manage');
 const load=useCallback(async()=>{const [m,r,p,i]=await Promise.all([api<Member[]>('members'),api<Role[]>('roles'),api<{code:string;description:string}[]>('permissions'),manage?api<Invitation[]>('invitations'):Promise.resolve([])]);setMembers(m);setRoles(r);setPermissions(p);setInvitations(i);setLoading(false);},[manage]);
 useEffect(()=>{load().catch(e=>{setError(e.message);setLoading(false);});},[load]);
 const currentRole=editRole==='new'?null:editRole;
 return <><Heading eyebrow="PERSONAS Y ACCESOS" title={view==='team'?'Tu equipo':'Roles y permisos'} description={view==='team'?'Cada persona, conectada a tu práctica.':'El acceso correcto para cada responsabilidad.'} action={view==='team'&&manage?<button className="button primary" onClick={()=>{setInvite(true);setEditMember(null);}}><Mail size={17}/>Invitar persona</button>:view==='roles'&&can('roles.manage')?<button className="button primary" onClick={()=>{setEditRole('new');setSelected(['organizations.view']);}}><Plus size={18}/>Crear rol</button>:undefined}/><ErrorMessage message={error}/>
 {invite&&<InlinePanel title="Invita a tu equipo" onClose={()=>setInvite(false)}><p className="muted">Enviaremos un enlace personal, válido durante 48 horas.</p><Form label="Enviar invitación" onSubmit={async v=>{await api('invitations','POST',v);await load();setInvite(false);}}><div className="form-grid"><Field label="Correo electrónico" name="email" type="email" required/><label className="field"><span>Rol en la organización</span><select name="role_id" required>{roles.filter(r=>r.permissions.every(can)).map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label></div></Form></InlinePanel>}
 {editMember&&<InlinePanel title={`Acceso de ${editMember.name}`} onClose={()=>setEditMember(null)}><Form onSubmit={async v=>{await api(`members/${editMember.id}`,'PATCH',{role_id:v.role_id,active:v.active==='true'});await load();await refreshContext();setEditMember(null);}}><div className="form-grid"><label className="field"><span>Rol</span><select name="role_id" defaultValue={editMember.role_id}>{roles.filter(r=>r.permissions.every(can)).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="field"><span>Acceso</span><select name="active" defaultValue={String(editMember.active)}><option value="true">Activo</option><option value="false">Suspendido en esta organización</option></select></label></div><p className="muted">Suspender el acceso impide las siguientes operaciones en esta organización y conserva el historial.</p></Form></InlinePanel>}
 {editRole&&<InlinePanel title={currentRole?`Editar ${currentRole.name}`:'Nuevo rol personalizado'} onClose={()=>setEditRole(null)}><Form key={currentRole?.id||'new'} onSubmit={async v=>{await api(currentRole?`roles/${currentRole.id}`:'roles',currentRole?'PATCH':'POST',{name:v.name,permissions:selected});await load();await refreshContext();setEditRole(null);}}><Field label="Nombre del rol" name="name" value={currentRole?.name} required/><fieldset className="permission-fieldset"><legend>Permisos del rol</legend><div className="permissions-grid">{permissions.filter(p=>can(p.code)).map(p=><label key={p.code} className="check-field"><input type="checkbox" checked={selected.includes(p.code)} onChange={e=>setSelected(s=>e.target.checked?[...s,p.code]:s.filter(c=>c!==p.code))}/><span>{p.description}<small>{p.code}</small></span></label>)}</div></fieldset></Form></InlinePanel>}
 {loading?<div className="skeleton">Cargando equipo…</div>:view==='team'?<><div className="table-wrap"><table><thead><tr><th>Persona</th><th>Rol</th><th>Acceso</th>{manage&&<th><span className="sr-only">Acciones</span></th>}</tr></thead><tbody>{members.map(m=><tr key={m.id}><td><div className="person-cell"><span className="avatar muted-avatar">{m.name.replace(/^(Dra?\.\s*)/,'').split(' ').slice(0,2).map(v=>v[0]).join('')}</span><div><strong>{m.name}</strong><small>{m.email}</small></div></div></td><td>{m.role}</td><td><span className={`pill ${m.active?'green':''}`}>{m.active?'Activo':'Suspendido'}</span></td>{manage&&<td><button className="text-button" onClick={()=>{setEditMember(m);setInvite(false);}}>Editar acceso</button></td>}</tr>)}</tbody></table></div>{!members.length&&<Empty icon={<Users/>} title="El equipo comienza contigo" description="Invita a las personas que colaboran en tu práctica."/>}{manage&&<section className="invitations"><h2>Invitaciones recientes</h2>{invitations.length?invitations.map(i=><div className="invitation-row" key={i.id}><Mail size={18}/><div><strong>{i.email}</strong><small>{i.role}</small></div><span className="pill">{i.accepted_at?'Aceptada':new Date(i.expires_at)<new Date()?'Vencida':i.delivery_status==='pending'?'Correo en cola':i.delivery_status==='failed'?'Error de envío':i.delivery_status==='cancelled'?'Cancelada':'Pendiente de aceptar'}</span>{!i.accepted_at&&new Date(i.expires_at)>new Date()&&<button className="text-button danger-text" onClick={async()=>{try{await api(`invitations/${i.id}`,'DELETE');await load();}catch(e){setError((e as Error).message);}}}>Revocar</button>}</div>):<p className="muted">Aún no has enviado invitaciones.</p>}</section>}</>:<div className="roles-list">{roles.map(r=><article className="role-row" key={r.id}><span className="setup-icon"><ShieldCheck size={22}/></span><div><h2>{r.name}<span className="pill">{r.system?'Rol base':'Personalizado'}</span></h2><details><summary>{r.permissions.length} permisos · Ver detalle</summary><ul>{r.permissions.map(p=><li key={p}>{permissions.find(x=>x.code===p)?.description||p}</li>)}</ul></details></div>{!r.system&&can('roles.manage')&&<button className="button secondary" onClick={()=>{setEditRole(r);setSelected(r.permissions);}}>Editar rol</button>}</article>)}</div>}
 </>;
}
