'use client';
import { useEffect,useState } from 'react';
import { TreatmentServicePicker } from './treatment-service-picker';
import { api } from '../lib/api';
import { ErrorMessage,Section } from './ui';
const states={proposed:'Propuesto',in_progress:'En curso',completed:'Realizado',cancelled:'Cancelado'};
type Item={id:string;service_id?:string;service_requires_tooth?:boolean;service_name?:string;tooth:string;title:string;status:keyof typeof states;notes:string};
type Data={version:number;latest:number;items:Item[];history:{version:number;author:string;created_at:string}[]};
const blank=():Item=>({id:crypto.randomUUID(),tooth:'',title:'',status:'proposed',notes:''});
export function TreatmentPlan({patientId,editable}:{patientId:string;editable:boolean}){
 const base='patients/'+patientId+'/treatment-plan';const [choosing,setChoosing]=useState(false);const [data,setData]=useState<Data|null>(null),[items,setItems]=useState<Item[]>([]),[draft,setDraft]=useState<Item|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const dirty=!!data&&JSON.stringify(items)!==JSON.stringify(data.items),canEdit=editable&&!!data&&data.version===data.latest&&!busy;
 useEffect(()=>{let live=true;api<Data>(base,'GET',undefined,15000).then(r=>{if(live){setData(r);setItems(r.items);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[base]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty||draft){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,draft]);
 async function load(version?:number){if((dirty||draft)&&!window.confirm('¿Descartar los cambios sin guardar del plan?'))return;setBusy(true);setError('');try{const next=await api<Data>(base+(version?'?version='+version:''),'GET',undefined,15000);setData(next);setItems(next.items);setDraft(null);setMessage('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function apply(){if(!draft)return;if(!draft.title.trim()){setError('Escribe el procedimiento.');return;}if(draft.service_requires_tooth&&!draft.tooth){setError('Este servicio requiere una pieza dental.');return;}if(draft.tooth&&!/^([1-4][1-8]|[5-8][1-5])$/.test(draft.tooth)){setError('La pieza FDI no es válida.');return;}const item={...draft,title:draft.title.trim(),notes:draft.notes.trim()},exists=items.some(i=>i.id===item.id);if(!exists&&items.length>=100){setError('Máximo 100 procedimientos por plan.');return;}setItems(exists?items.map(i=>i.id===item.id?item:i):[...items,item]);setDraft(null);setError('');setMessage('Cambio añadido al borrador. Guarda el plan para conservarlo.');}
 return <Section title="Plan de tratamiento" description="Procedimientos registrados por el profesional. Este plan es clínico; no genera presupuestos, cobros ni citas."><ErrorMessage message={error}/>{!data&&!error&&<p>Cargando plan…</p>}{error&&!data&&<button className="text-button" onClick={()=>void load()}>Reintentar plan</button>}{data&&<><div className="form-actions odonto-actions"><span>{dirty||draft?'Cambios sin guardar':data.version?'Versión '+data.version+' guardada':'Sin plan registrado'}</span>{canEdit&&<button className="button secondary" disabled={!!draft||items.length>=100} onClick={()=>{setChoosing(false);setDraft(blank());setMessage('');}}>Añadir procedimiento</button>}{editable&&<button className="button primary" aria-busy={busy} disabled={!canEdit||!dirty||!!draft} onClick={async()=>{setBusy(true);setError('');try{const r=await api<{version:number}>(base,'POST',{version:data.version,items},15000);setData({...data,version:r.version,latest:r.version,items,history:[{version:r.version,author:'Esta sesión',created_at:new Date().toISOString()},...data.history.filter(h=>h.version!==r.version)].slice(0,25)});setMessage('Plan de tratamiento guardado.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Guardar plan</button>}</div>
 {draft&&<form className="form clinical-form panel" onSubmit={e=>{e.preventDefault();apply();}}><h3>{items.some(i=>i.id===draft.id)?'Editar procedimiento':'Nuevo procedimiento'}</h3><div className="form-actions odonto-actions"><button type="button" className="button secondary" onClick={()=>setChoosing(v=>!v)}>{choosing?'Cerrar catálogo':'Elegir del catálogo'}</button>{draft.service_id&&<button type="button" className="text-button" onClick={()=>{const {service_id,service_name,service_requires_tooth,...manual}=draft;void service_id;void service_name;void service_requires_tooth;setDraft(manual);}}>Usar como procedimiento manual</button>}</div>{draft.service_name&&<p>Servicio vinculado: <strong>{draft.service_name}</strong></p>}{choosing&&<TreatmentServicePicker patientId={patientId} onSelect={service=>{setDraft({...draft,service_id:service.id,service_requires_tooth:service.requires_tooth,service_name:service.name,title:service.name});setChoosing(false);}}/>}<label className="field"><span>Procedimiento</span><input aria-label="Procedimiento" maxLength={160} required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="form-grid"><label className="field"><span>{draft.service_requires_tooth?'Pieza dental (requerida)':'Pieza dental (opcional)'}</span><input aria-label="Pieza del procedimiento" required={!!draft.service_requires_tooth} inputMode="numeric" maxLength={2} value={draft.tooth} onChange={e=>setDraft({...draft,tooth:e.target.value})}/><small>{draft.service_requires_tooth?'El servicio seleccionado requiere una pieza FDI.':'Deja vacío para un procedimiento general.'}</small></label><label className="field"><span>Estado del procedimiento</span><select aria-label="Estado del procedimiento" value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Item['status']})}>{Object.entries(states).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><label className="field"><span>Notas del procedimiento</span><textarea aria-label="Notas del procedimiento" maxLength={500} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="form-actions odonto-actions"><button className="button secondary">Aplicar al plan</button><button type="button" className="text-button" onClick={()=>{if(window.confirm('¿Descartar esta edición del procedimiento?'))setDraft(null);}}>Cancelar edición</button></div><small>Aplicar actualiza el borrador; Guardar plan registra la versión.</small></form>}
 {!items.length&&<p>Aún no hay procedimientos en este plan.</p>}{items.map((item,i)=><article className="treatment-item" key={item.id}><div><h3>{i+1}. {item.title}</h3>{item.service_name&&<small>Catálogo: {item.service_name}</small>}<p>{item.tooth?'Pieza '+item.tooth:'Procedimiento general'} · <strong>{states[item.status]}</strong></p>{item.notes&&<p className="patient-notes">{item.notes}</p>}</div>{canEdit&&<button className="text-button" disabled={!!draft} aria-label={'Editar procedimiento '+(i+1)} onClick={()=>{setChoosing(false);setDraft({...item});setMessage('');}}>Editar</button>}</article>)}{message&&<p role="status" className="saved">{message}</p>}
 <details><summary>Historial del plan</summary><label className="field"><span>Versión del plan</span><select aria-label="Versión del plan" value={data.version} disabled={busy} onChange={e=>void load(Number(e.target.value))}>{!data.version&&<option value={0}>Sin registros</option>}{data.history.map(h=><option key={h.version} value={h.version}>Versión {h.version} · {h.author} · {new Date(h.created_at).toLocaleString('es-MX')}</option>)}</select></label><button className="text-button" disabled={busy} onClick={()=>void load()}>Cargar plan actual</button><p>Últimas 25 versiones. Para retirar un procedimiento, cambia su estado a Cancelado.</p></details>{data.version!==data.latest&&<p>Versión histórica de solo lectura.</p>}
 </>}</Section>;
}
