'use client';
import { useState, type ReactNode, type FormEvent } from 'react';
import { ArrowRight, Check, LoaderCircle, X } from 'lucide-react';
export function Mark(){return <svg width="36" height="40" viewBox="0 0 36 40" fill="none" aria-hidden="true"><path d="M18 7C12 2 3 6 4 15c1 6 4 18 8 20 3 1 2-12 6-12s3 13 6 12c4-2 7-14 8-20C33 6 24 2 18 7Z" stroke="currentColor" strokeWidth="2.5"/><path d="m13 13 5 3 5-3" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/></svg>;}
export function Brand(){return <div className="brand"><span className="brand-mark"><Mark/></span><div>ALIA <strong>DENTAL</strong><small>POR ALIA SOLUCIONES</small></div></div>;}
export function ErrorMessage({message}:{message:string}){return message?<div className="error" role="alert">{message}</div>:null;}
export function Empty({icon,title,description,action}:{icon:ReactNode;title:string;description:string;action?:ReactNode}){return <div className="empty"><span className="empty-icon">{icon}</span><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function Heading({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:ReactNode}){return <header className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1><p>{description}</p></div>{action}</header>;}
export function Form({children,onSubmit,label='Guardar cambios',className='',onDone,disabled=false}:{children:ReactNode;onSubmit:(values:Record<string,string>)=>Promise<unknown>;label?:string;className?:string;onDone?:()=>void;disabled?:boolean}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy||disabled)return;const values=Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string,string>;setBusy(true);setError('');setSaved(false);try{await onSubmit(values);setSaved(true);onDone?.();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className={`form ${className}`} onSubmit={submit} onChange={()=>setSaved(false)}>{children}<ErrorMessage message={error}/><div className="form-actions"><button className="button primary" disabled={busy||disabled}>{busy?<LoaderCircle size={17} className="spin"/>:saved?<Check size={17}/>:null}{busy?'Guardando…':label}</button>{saved&&<span className="saved" role="status">Guardado correctamente</span>}</div></form>;
}
export function Field({label,name,value='',type='text',required=false,placeholder,help,minLength,maxLength}:{label:string;name:string;value?:string;type?:string;required?:boolean;placeholder?:string;help?:string;minLength?:number;maxLength?:number}){return <label className="field"><span>{label}{required&&<span className="required"> *</span>}</span><input aria-label={label} name={name} defaultValue={value} type={type} required={required} placeholder={placeholder} minLength={minLength} maxLength={maxLength} autoComplete={type==='password'?'new-password':undefined}/>{help&&<small>{help}</small>}</label>;}
export function Section({title,description,children}:{title:string;description?:string;children:ReactNode}){return <section className="section"><div className="section-intro"><h2>{title}</h2>{description&&<p>{description}</p>}</div><div className="section-body">{children}</div></section>;}
export function LinkButton({children,onClick}:{children:ReactNode;onClick:()=>void}){return <button className="text-button" onClick={onClick}>{children}<ArrowRight size={16}/></button>;}
export function InlinePanel({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <section className="panel editor"><div className="panel-heading"><h2>{title}</h2><button className="icon-button" aria-label="Cerrar formulario" onClick={onClose}><X size={20}/></button></div>{children}</section>;}
