'use client';
import { Temporal } from '@js-temporal/polyfill';
import { useCallback, useEffect, useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { Activity, ArrowRight, Building2, CalendarDays, Check, ChevronDown, Command, CreditCard, FileClock, FileHeart, FlaskConical, Home, Layers, LayoutGrid, LogOut, Menu, Package, Search, ShieldCheck, Users, X } from 'lucide-react';
import { api, ApiError, setContext } from '../lib/api';
import type { Context, Me } from '../lib/types';
import { Brand, Empty, ErrorMessage, Field, Form, Heading, InlinePanel } from './ui';
import { Login } from './login';
import { OrganizationSettings, Branches } from './organization';
import { Team } from './team';
import { Security } from './security';
import { Audit } from './audit';
import { InvitationAcceptance } from './invitation';
import { Patients, PatientQuickSearch } from './patients';
import { OperationalSearch } from './operational-search';
import {Laboratories} from './laboratories';
import {Inventory} from './inventory';
import {ProfessionalReport} from './professional-report';
import {ModuleHub} from './module-hub';
import {CashClosures} from './cash-closures';
import { ConsentTemplates } from './consent-templates';
import { Catalogs } from './catalogs';
import { navigationKey,readNavigation,saveNavigation } from '../lib/agenda-navigation';
import { Appointments } from './appointments';
type View='laboratories'|'inventory'|'professional-report'|'records'|'treatments'|'cash'|'reports'|'cash-closures'|'consent-templates'|'agenda'|'professionals'|'rooms'|'services'|'patients'|'home'|'organization'|'branches'|'team'|'roles'|'security'|'audit';
const routes:{id:View;label:string;icon:typeof Home;permission?:string}[]=[{id:'laboratories',label:'Laboratorios',icon:FlaskConical,permission:'catalogs.view'},{id:'inventory',label:'Inventario',icon:Package,permission:'inventory.view'},{id:'professional-report',label:'Reporte profesional',icon:Layers,permission:'professional_shares.view'},{id:'records',label:'Expedientes',icon:FileHeart},{id:'treatments',label:'Tratamientos',icon:Activity},{id:'cash',label:'Caja',icon:CreditCard},{id:'reports',label:'Reportes',icon:Layers},{id:'cash-closures',label:'Corte de caja',icon:CreditCard,permission:'cash_closures.view'},{id:'consent-templates',label:'Plantillas de consentimiento',icon:FileHeart,permission:'catalogs.view'},{id:'agenda',label:'Agenda',icon:CalendarDays,permission:'appointments.view'},{id:'professionals',label:'Profesionales',icon:Users,permission:'catalogs.view'},{id:'rooms',label:'Consultorios',icon:LayoutGrid,permission:'catalogs.view'},{id:'services',label:'Servicios',icon:Activity,permission:'catalogs.view'},{id:'patients',label:'Pacientes',icon:Users,permission:'patients.view'},{id:'home',label:'Inicio',icon:Home},{id:'team',label:'Equipo',icon:Users,permission:'users.view'},{id:'organization',label:'Organización',icon:Building2,permission:'settings.manage'},{id:'branches',label:'Sucursales',icon:LayoutGrid,permission:'settings.manage'},{id:'roles',label:'Roles y permisos',icon:ShieldCheck,permission:'users.view'},{id:'audit',label:'Auditoría',icon:FileClock,permission:'audit.view'},{id:'security',label:'Mi seguridad',icon:ShieldCheck}];
const future: [string,typeof Home][]=[];
export function Workspace(){
 const [me,setMe]=useState<Me|null>(null),[org,setOrg]=useState(''),[context,setData]=useState<Context|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[view,setView]=useState<View>('home'),[mobile,setMobile]=useState(false),[palette,setPalette]=useState(false),[search,setSearch]=useState(''),[newOrg,setNewOrg]=useState(false),[branch,setBranch]=useState('');
 const [searchTarget,setSearchTarget]=useState<{kind:string;id:string;name:string;date?:string;active?:boolean;nonce:number}|null>(null);
 const refreshMe=useCallback(async()=>{const data=await api<Me>('auth/me');setContext(data.csrf,'');setMe(data);setOrg(prior=>data.organizations.some(o=>o.id===prior)?prior:data.organizations[0]?.id||'');setLoading(false);},[]);
 useEffect(()=>{refreshMe().catch(e=>{if(!(e instanceof ApiError&&e.status===401))setError(e.message);setLoading(false);});},[refreshMe]);
 const refresh=useCallback(async()=>{if(!me||!org)return;setContext(me.csrf,org);const value=await api<Context>('organization');setData(value);setBranch(prior=>value.branches.some(b=>b.id===prior)?prior:value.branches.find(b=>b.active)?.id||'');},[me,org]);
 useEffect(()=>{setData(null);setError('');let active=true;if(me&&org){setContext(me.csrf,org);api<Context>('organization').then(value=>{if(active){setData(value);const saved=readNavigation(navigationKey(me.user.id,org)).branch;setBranch(value.branches.find(b=>b.active&&b.id===saved)?.id||value.branches.find(b=>b.active)?.id||'');}}).catch(e=>{if(active)setError(e.message);});}return()=>{active=false;};},[me,org]);
 useEffect(()=>{const read=()=>{const hash=window.location.hash.slice(1).split('/')[0];if(routes.some(r=>r.id===hash))setView(hash as View);};read();window.addEventListener('hashchange',read);const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(v=>!v);}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('hashchange',read);};},[]);
 useEffect(()=>{if(me&&context?.organization.id===org&&context.branches.some(b=>b.active&&b.id===branch))saveNavigation(navigationKey(me.user.id,org),{branch});},[me,context,org,branch]);
 function navigate(id:View){setSearchTarget(null);setView(id);window.location.hash=id;setMobile(false);setPalette(false);setSearch('');}
 if(loading)return <div className="loading-screen"><Brand/><p>Preparando tu espacio…</p></div>;
 if(!me)return <><ErrorMessage message={error}/><Login onLogin={refreshMe}/></>;
 const can=(p?:string)=>!p||!!context?.permissions.includes(p);
 const routeAllowed=(r:(typeof routes)[number])=>r.id==='records'?can('patients.view')&&can('clinical_records.view'):r.id==='treatments'?can('patients.view')&&(can('clinical_records.view')||can('budgets.view')):r.id==='cash'?(can('patients.view')&&(can('payments.view')||can('professional_shares.view')))||can('cash_closures.view'):r.id==='professional-report'?can('patients.view')&&can('professional_shares.view'):r.id==='reports'?can('cash_closures.view')||(can('patients.view')&&can('professional_shares.view')):can(r.permission);
 const allowedRoutes=routes.filter(routeAllowed);
 const selected=routes.find(r=>r.id===view);
 return <div className="app-shell"><a className="skip-link" href="#main">Saltar al contenido</a>{mobile&&<button className="sidebar-scrim" aria-label="Cerrar navegación" onClick={()=>setMobile(false)}/>}
 <aside className={`sidebar ${mobile?'open':''}`}><Brand/><div className="workspace-label">ESPACIO DE TRABAJO</div><nav aria-label="Navegación principal"><button className={`nav-item ${view==='home'?'active':''}`} onClick={()=>navigate('home')}><Home size={19}/>Inicio{view==='home'&&<span className="active-dot"/>}</button><>{can('patients.view')&&<button className={`nav-item ${view==='patients'?'active':''}`} onClick={()=>navigate('patients')}><Users size={19}/>Pacientes</button>}</>{can('appointments.view')&&<button className={`nav-item ${view==='agenda'?'active':''}`} onClick={()=>navigate('agenda')}><CalendarDays size={19}/>Agenda</button>}{allowedRoutes.filter(r=>['records','treatments','cash','reports','inventory','laboratories'].includes(r.id)).map(r=><button key={r.id} className={`nav-item ${view===r.id?'active':''}`} onClick={()=>navigate(r.id)}><r.icon size={19}/>{r.label}</button>)}{can('users.view')&&<button className={`nav-item ${view==='team'?'active':''}`} onClick={()=>navigate('team')}><Users size={19}/>Equipo</button>}<div className="future-nav">{future.map(([label,Icon])=><div className="nav-item unavailable" key={label} title="Pendiente de implementación"><Icon size={19}/>{label}<span className="pending-label">Pendiente</span></div>)}</div></nav><div className="nav-divider"/><div className="workspace-label">ADMINISTRACIÓN</div><nav aria-label="Administración">{allowedRoutes.filter(r=>!['home','team','patients','agenda','records','treatments','cash','reports','inventory','laboratories'].includes(r.id)).map(r=><button key={r.id} className={`nav-item ${view===r.id?'active':''}`} onClick={()=>navigate(r.id)}><r.icon size={18}/>{r.label}</button>)}</nav><div className="sidebar-bottom"><small>© {new Date().getFullYear()} Alia Soluciones</small></div></aside>
 <div className="app-body"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Abrir navegación" onClick={()=>setMobile(true)}><Menu size={22}/></button><div className="organization-switch"><Building2 size={19}/><label className="sr-only" htmlFor="org-select">Organización activa</label><select id="org-select" value={org} onChange={e=>{setOrg(e.target.value);navigate('home');}}>{me.organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><ChevronDown size={14}/></div><div className="topbar-divider"/><label className="branch-switch"><span className="sr-only">Sucursal activa</span><select aria-label="Sucursal activa" value={branch} onChange={e=>setBranch(e.target.value)}>{context?.branches.filter(b=>b.active).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div className="topbar-end"><button className="search-trigger" onClick={()=>setPalette(true)}><Search size={18}/><span>Buscar una acción…</span><kbd>⌘ K</kbd></button><button className="avatar" aria-label="Abrir seguridad de mi cuenta" onClick={()=>navigate('security')}>{me.user.name.replace(/^(Dra?\.\s*)/,'').split(' ').slice(0,2).map(w=>w[0]).join('')}</button><button className="icon-button logout" aria-label="Cerrar sesión" onClick={async()=>{try{await api('auth/logout','POST');setMe(null);setData(null);setContext('','');}catch(e){setError((e as Error).message);}}}><LogOut size={18}/></button></div></header>
 <main id="main" className="main-content"><InvitationAcceptance refresh={refreshMe}/><ErrorMessage message={error}/>{!org?<Empty icon={<Building2 size={30}/>} title="Crea tu primer espacio" description="Organiza tu práctica independiente o tu clínica." action={<button className="button primary" onClick={()=>setNewOrg(true)}>Crear organización</button>}/>:!context?<div className="skeleton">Cargando organización…</div>:selected&&!routeAllowed(selected)?<Empty icon={<ShieldCheck/>} title="Acceso restringido" description="Tu rol no tiene permiso para ver esta sección."/>:<div key={`${org}-${view}`}>
 {(['records','treatments','cash','reports'] as const).map(kind=>view===kind?<ModuleHub key={kind} kind={kind} can={can}/>:null)}
 {view==='laboratories'&&<Laboratories editable={can('catalogs.manage')}/>} {view==='inventory'&&<Inventory editable={can('inventory.edit')}/>} {view==='professional-report'&&<ProfessionalReport/>}
 {view==='cash-closures'&&<CashClosures editable={can('cash_closures.create')}/>} 
 {view==='consent-templates'&&<ConsentTemplates editable={can('catalogs.manage')}/>}
 {view==='home'&&<><Heading title={`Hola, ${me.user.name.replace(/^(Dra?\.\s*)/,'').split(' ')[0]}.`} description="" action={<span className="date-label">{new Intl.DateTimeFormat('es-MX',{weekday:'long',day:'numeric',month:'long',timeZone:context.organization.timezone}).format(new Date())}</span>}/>
 <div className="stats-row"><div><span>Sucursales activas</span><strong>{context.branches.filter(b=>b.active).length.toString().padStart(2,'0')}</strong></div><div><span>Miembros del equipo</span><strong>{context.counts.members.toString().padStart(2,'0')}</strong></div><div><span>Roles disponibles</span><strong>{context.counts.roles}</strong></div><div><span>Tu acceso</span><strong className="role-stat">{me.organizations.find(o=>o.id===org)?.role}</strong><small>{me.mfaEnabled?'Verificación en dos pasos activa':'Activa la verificación en dos pasos'}</small></div></div>
 <div className="home-settings"><section className="setup-section"><div className="section-title"><h2>Configuración</h2></div>{[{icon:Building2,title:'Organización',description:'Datos generales, zona horaria y moneda.',view:'organization' as View,done:!!context.organization.legal_name,permission:'settings.manage'},{icon:LayoutGrid,title:'Sucursales',description:'Ubicaciones donde sucede el cuidado.',view:'branches' as View,done:context.branches.length>0,permission:'settings.manage'},{icon:Users,title:'Equipo',description:'Cada persona con el acceso que necesita.',view:'team' as View,done:context.counts.members>1,permission:'users.view'},{icon:ShieldCheck,title:'Seguridad',description:'Añade una segunda capa de seguridad.',view:'security' as View,done:me.mfaEnabled}].filter(i=>can(i.permission)).map(item=><button className="setup-item" key={item.title} onClick={()=>navigate(item.view)}><span className={`setup-icon ${item.done?'complete':''}`}><item.icon size={22}/></span><span><strong>{item.title}</strong></span>{item.done?<Check size={18} className="check"/>:<ArrowRight size={18}/>}</button>)}</section></div><div className="workspace-footer"><button className="text-button" onClick={()=>setNewOrg(true)}>Crear otra organización<ArrowRight size={15}/></button></div></>}
 {view==='agenda'&&<Appointments navigationStorageKey={navigationKey(me.user.id,org)} key={`${branch}-${searchTarget?.nonce||0}`} context={context} branch={branch} initialDate={searchTarget?.kind==='appointments'?searchTarget.date:undefined}/>} {(view==='professionals'||view==='rooms'||view==='services')&&<Catalogs key={`${view}-${searchTarget?.nonce||0}`} kind={view} context={context} initialId={searchTarget?.kind===view?searchTarget.id:undefined} initialStatus={searchTarget?.kind===view?'all':undefined}/>} {view==='patients'&&<Patients can={can} openAppointment={appointment=>{setBranch(appointment.branch_id);setSearchTarget({kind:'appointments',id:appointment.id,name:'',date:Temporal.Instant.from(appointment.starts_at).toZonedDateTimeISO(context.organization.timezone).toPlainDate().toString(),nonce:Date.now()});setView('agenda');window.location.hash='agenda';}}/>} {view==='organization'&&<OrganizationSettings context={context} refresh={async()=>{await refresh();await refreshMe();}}/>}{view==='branches'&&<Branches context={context} refresh={refresh}/>}{(view==='team'||view==='roles')&&<Team view={view} can={can} refreshContext={refresh}/>}{view==='security'&&<Security me={me} refreshMe={refreshMe} signedOut={()=>{setMe(null);setContext('','');}}/>}{view==='audit'&&<Audit/>}</div>}
 {newOrg&&<InlinePanel title="Nueva organización" onClose={()=>setNewOrg(false)}><p className="muted">Tendrá su propio equipo, sucursales y permisos.</p><Form label="Crear organización" onSubmit={async values=>{const result=await api<{id:string}>('organizations','POST',values);await refreshMe();setOrg(result.id);setNewOrg(false);navigate('home');}}><Field label="Nombre comercial" name="name" required minLength={2}/><Field label="Primera sucursal o consultorio" name="branch" required minLength={2}/></Form></InlinePanel>}
 </main><footer className="app-footer"><span>ALIA DENTAL <span>por Alia Soluciones</span></span></footer></div>
 <Dialog.Root open={palette} onOpenChange={setPalette}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="command-dialog"><Dialog.Title className="sr-only">Buscar acciones</Dialog.Title><Dialog.Description className="sr-only">Navega por la configuración de tu espacio.</Dialog.Description><div className="command-search"><Search size={21}/><input aria-label="Buscar una acción" placeholder="¿Qué necesitas hacer?" value={search} onChange={e=>setSearch(e.target.value)}/><Dialog.Close className="icon-button" aria-label="Cerrar búsqueda"><X size={18}/></Dialog.Close></div><div className="command-results">{can('patients.view')&&<PatientQuickSearch search={search} open={id=>{setView('patients');window.location.hash=`patients/${id}`;setPalette(false);setSearch('');}}/>}{context&&<OperationalSearch key={org} search={search} zone={context.organization.timezone} open={(kind,item)=>{setSearchTarget({kind,id:item.id,name:item.name,date:item.date,active:item.active,nonce:Date.now()});if(item.branch_id)setBranch(item.branch_id);const target=kind==='appointments'?'agenda':kind;setView(target);window.location.hash=target;setPalette(false);setSearch('');setMobile(false);}}/>}{allowedRoutes.filter(r=>r.label.toLowerCase().includes(search.toLowerCase())).map(r=><button onClick={()=>navigate(r.id)} key={r.id}><r.icon size={19}/>{r.label}<ArrowRight size={16}/></button>)}</div><div className="command-footer"><Command size={14}/> Acciones, pacientes y operación</div></Dialog.Content></Dialog.Portal></Dialog.Root></div>;
}



